-- Explications trop télégraphiques, complétées.
-- À coller dans Supabase → SQL Editor → Run.

update questions set explication = '476, 1492, 1789, 1914 : quatre bornes classiques du découpage de l''histoire occidentale.' where id = 'Q0012';
update questions set explication = '1804, 1814, 1852, 1870 : la France a changé sept fois de régime en moins d''un siècle.' where id = 'Q0030';
update questions set explication = '23 paires, dont une seule détermine le sexe. Le chiffre n''a rien à voir avec la complexité : le blé en a 42.' where id = 'Q0085';
update questions set explication = 'Face à Kate Winslet. L''acteur avait 22 ans et a d''abord refusé le rôle, qu''il jugeait trop sage.' where id = 'Q0125';
update questions set explication = 'Sorti en 1993, le film a été le plus gros succès du box-office jusqu''à Titanic.' where id = 'Q0136';
update questions set explication = '1939, 1960, 1977, 1997 : près de soixante ans d''histoire du cinéma.' where id = 'Q0142';
update questions set explication = 'Né en 1756, il composait dès l''âge de cinq ans et a parcouru l''Europe enfant, exhibé par son père.' where id = 'Q0161';
update questions set explication = 'Groupe de Liverpool, séparé en 1970 après seulement huit ans de disques.' where id = 'Q0162';
update questions set explication = 'Chanson de 1959, écrite après une rupture ; Brel disait pourtant que ce n''était pas une chanson d''amour.' where id = 'Q0177';
update questions set explication = 'Créé à Paris en 1875 : un échec à la création, trois mois avant la mort du compositeur.' where id = 'Q0184';
update questions set explication = '1685, 1756, 1770, 1862 : du baroque à l''impressionnisme.' where id = 'Q0186';
update questions set explication = '« Deuce » en anglais : il faut alors deux points d''écart pour emporter le jeu.' where id = 'Q0196';
update questions set explication = '1992, 2000, 2008, 2021 : Tokyo 2020 a été reportée d''un an à cause de la pandémie.' where id = 'Q0207';
update questions set explication = 'Gagné par Maurice Garin, sur six étapes seulement, dont certaines de plus de 400 km.' where id = 'Q0216';
update questions set explication = 'Publié en 1862, alors que l''auteur était en exil à Guernesey depuis dix ans.' where id = 'Q0224';
update questions set explication = 'En 1888, à Arles, après une dispute avec Gauguin : il s''est tranché une partie de l''oreille gauche.' where id = 'Q0230';
update questions set explication = 'De 1508 à 1512, allongé sur un échafaudage : il se considérait sculpteur, pas peintre.' where id = 'Q0236';
update questions set explication = '1622, 1802, 1840, 1913 : trois siècles de littérature française.' where id = 'Q0237';
update questions set explication = 'Inaugurée en 1989, la pyramide de verre a d''abord été très critiquée avant de devenir un symbole du musée.' where id = 'Q0244';
update questions set explication = 'Écrit en 1870, à 16 ans : le poème évoque un jeune soldat mort, découvert à la dernière ligne.' where id = 'Q0249';
update questions set explication = 'Recette mexicaine dont le nom vient du nahuatl « ahuacamolli », la sauce à l''avocat.' where id = 'Q0255';
update questions set explication = '60 × 60. La division du temps par soixante nous vient des Babyloniens, qui comptaient en base 60.' where id = 'Q0294';
update questions set explication = 'Une faute très courante. Même règle pour « hormis » ; en revanche, « malgré » n''en prend jamais non plus.' where id = 'Q0295';
update questions set explication = '10⁻⁹, 10⁻⁶, 10⁻³, 10³ : chaque préfixe change l''échelle d''un facteur mille.' where id = 'Q0314';
update questions set explication = '2, 3, 5, 7, 11, 13… Un nombre premier n''est divisible que par 1 et par lui-même ; il en existe une infinité.' where id = 'Q0316';
update questions set explication = 'En 52 av. J.-C., à Alésia. Emmené à Rome, il y fut exécuté six ans plus tard.' where id = 'Q0320';
update questions set explication = 'Mission Apollo 11, le 21 juillet 1969 heure française : environ 600 millions de personnes ont suivi en direct.' where id = 'Q0323';
update questions set explication = '1944, 1962, 1989, 2002 : du Débarquement à l''arrivée de l''euro en pièces et billets.' where id = 'Q0328';
update questions set explication = 'Au XVIe siècle : sous son règne, l''empire s''étendait de Budapest à Bagdad.' where id = 'Q0332';
update questions set explication = 'Nelson y trouva la mort, au moment même où sa flotte l''emportait au large de l''Espagne.' where id = 'Q0335';
update questions set explication = 'Du latin « ferrum ». C''est l''élément le plus abondant de la Terre, noyau compris.' where id = 'Q0377';
update questions set explication = '24 titres du Grand Chelem, devant Rafael Nadal et Roger Federer.' where id = 'Q0421';
update questions set explication = 'En 1930, en Uruguay, qui fêtait le centenaire de son indépendance — et qui a gagné le tournoi.' where id = 'Q0424';
update questions set explication = 'Scar, son frère, est l''oncle de Simba — et le nom signifie « cicatrice » en anglais.' where id = 'Q0428';
update questions set explication = 'Sorti en 1973, le film a été tourné en pleine crise diplomatique et est resté l''un des plus vus de l''acteur.' where id = 'Q0436';
update questions set explication = '1982, 1993, 1997, 2009 : quatre films qui ont chacun battu des records d''entrées.' where id = 'Q0438';
update questions set explication = 'Sol, ré, la, mi — accordées de quinte en quinte, contrairement à la guitare.' where id = 'Q0452';
update questions set explication = '1956, 1965, 1975, 1991 : du rock''n''roll naissant au grunge.' where id = 'Q0457';
update questions set explication = '1622, 1694, 1802, 1895 : de Molière aux écrivains du XXe siècle.' where id = 'Q0478';
update questions set explication = 'Peintre norvégien, 1893. Il en existe quatre versions ; deux ont été volées, puis retrouvées.' where id = 'Q0482';
update questions set explication = 'Exposé au Louvre. Peint en 1819, il montre le naufrage d''une frégate française et a fait scandale.' where id = 'Q0485';
update questions set explication = 'Au début du XIVe siècle, en toscan et non en latin : ce choix a fait naître l''italien littéraire.' where id = 'Q0486';
update questions set explication = 'Spécialité de Valence, à l''origine un plat de riziculteurs cuit au feu de bois, avec lapin et haricots.' where id = 'Q0491';
update questions set explication = 'Cocktail cubain à base de rhum, de menthe et de citron vert, popularisé à La Havane.' where id = 'Q0494';
update questions set explication = 'Soupe froide andalouse, née comme plat de paysans à base de pain rassis, d''huile et d''ail.' where id = 'Q0500';
update questions set explication = '8 × 8 cases, alternativement claires et sombres, avec toujours une case blanche à droite de chaque joueur.' where id = 'Q0515';
update questions set explication = '24 × 60. La journée de 24 heures vient des Égyptiens, qui découpaient le jour et la nuit en douze parts.' where id = 'Q0516';
update questions set explication = '8 pions et 8 pièces : roi, dame, deux tours, deux fous et deux cavaliers.' where id = 'Q0519';
update questions set explication = 'A, E, I, O, U et Y. Le y est appelé « i grec » parce qu''il vient de l''alphabet grec.' where id = 'Q0661';
