-- Explications ajoutées aux questions qui n'en avaient pas.
-- À coller dans Supabase → SQL Editor → Run. Rien d'autre n'est modifié.

update questions set explication = 'Rome est la seule capitale au monde à abriter un État étranger : le Vatican, 44 hectares.' where id = 'Q0032' and coalesce(explication, '') = '';
update questions set explication = 'La façade atlantique française court sur près de 2 000 km, du Pays basque à la pointe bretonne.' where id = 'Q0035' and coalesce(explication, '') = '';
update questions set explication = 'C''est la capitale la plus haute d''Europe de l''Ouest, à 650 m d''altitude.' where id = 'Q0037' and coalesce(explication, '') = '';
update questions set explication = 'La Tamise reste soumise aux marées jusqu''à Teddington, à 90 km de la mer.' where id = 'Q0042' and coalesce(explication, '') = '';
update questions set explication = 'Fondée en 1070, la ville a donné son nom au pays tout entier.' where id = 'Q0044' and coalesce(explication, '') = '';
update questions set explication = 'Elle boucle son orbite en 88 jours, mais une seule de ses journées dure 176 jours terrestres.' where id = 'Q0063' and coalesce(explication, '') = '';
update questions set explication = 'Moyen mnémotechnique : « Me Voici Tout Mouillé, Je Suis Une Nouille ».' where id = 'Q0074' and coalesce(explication, '') = '';
update questions set explication = 'Une petite part de l''ADN se loge aussi dans les mitochondries, transmises uniquement par la mère.' where id = 'Q0080' and coalesce(explication, '') = '';
update questions set explication = 'Sa charge sert d''unité de référence à toute l''électricité : −1,602 × 10⁻¹⁹ coulomb.' where id = 'Q0082' and coalesce(explication, '') = '';
update questions set explication = 'Un virus est environ cent fois plus petit qu''une bactérie : il a fallu le microscope électronique pour le voir.' where id = 'Q0087' and coalesce(explication, '') = '';
update questions set explication = 'C''est pourtant le seul félin réellement social : il vit en groupes, appelés troupes.' where id = 'Q0097' and coalesce(explication, '') = '';
update questions set explication = 'Il pèse environ 40 kg à la naissance et double son poids en six semaines.' where id = 'Q0098' and coalesce(explication, '') = '';
update questions set explication = 'Un chêne peut en produire 50 000 par an, mais seulement à partir d''une vingtaine d''années.' where id = 'Q0104' and coalesce(explication, '') = '';
update questions set explication = 'L''ours, le cochon et l''humain le sont : leur dentition mêle incisives, canines et molaires.' where id = 'Q0105' and coalesce(explication, '') = '';
update questions set explication = 'Il change de couleur pour communiquer et régler sa température, bien plus que pour se camoufler.' where id = 'Q0109' and coalesce(explication, '') = '';
update questions set explication = 'Un éléphant d''Afrique adulte atteint 6 tonnes, le poids de quatre voitures.' where id = 'Q0110' and coalesce(explication, '') = '';
update questions set explication = 'Son nom rend hommage à Buzz Aldrin, deuxième homme à marcher sur la Lune.' where id = 'Q0129' and coalesce(explication, '') = '';
update questions set explication = 'Il s''appelait Sméagol avant que l''anneau ne le ronge pendant près de cinq siècles.' where id = 'Q0137' and coalesce(explication, '') = '';
update questions set explication = 'Hollywood parlait de « la folie de Disney » : le film a rapporté huit millions de dollars en pleine Dépression.' where id = 'Q0145' and coalesce(explication, '') = '';
update questions set explication = 'Le rôle avait d''abord été proposé à Emily Watson, qui ne parlait pas assez français.' where id = 'Q0153' and coalesce(explication, '') = '';
update questions set explication = 'Elle en a écrit les paroles en 1945 ; la chanson s''est vendue à des millions d''exemplaires dans le monde.' where id = 'Q0159' and coalesce(explication, '') = '';
update questions set explication = 'Accordées mi, la, ré, sol, si, mi — de la plus grave à la plus aiguë.' where id = 'Q0160' and coalesce(explication, '') = '';
update questions set explication = 'Un piano compte 88 touches : 52 blanches et 36 noires.' where id = 'Q0163' and coalesce(explication, '') = '';
update questions set explication = 'Son album Thriller (1982) reste le plus vendu de l''histoire, avec plus de 60 millions d''exemplaires.' where id = 'Q0164' and coalesce(explication, '') = '';
update questions set explication = 'Il a enregistré plus de 700 chansons sans jamais en composer une seule.' where id = 'Q0165' and coalesce(explication, '') = '';
update questions set explication = 'Le surnom vient de son tube de 1962 ; sa carrière a duré 57 ans.' where id = 'Q0166' and coalesce(explication, '') = '';
update questions set explication = 'Cette victoire a lancé le groupe : la chanson compare une déclaration d''amour à la reddition de Napoléon.' where id = 'Q0170' and coalesce(explication, '') = '';
update questions set explication = 'Créé entre amis en 1992, le festival accueille aujourd''hui plus de 250 000 personnes en quatre jours.' where id = 'Q0176' and coalesce(explication, '') = '';
update questions set explication = 'Né à Paris de parents chinois, il a joué devant huit présidents américains.' where id = 'Q0178' and coalesce(explication, '') = '';
update questions set explication = 'Son nom de scène vient de son cousin par alliance, le danseur américain Lee Halliday.' where id = 'Q0182' and coalesce(explication, '') = '';
update questions set explication = 'Le surnom viendrait de « satchel mouth », « bouche en sacoche ».' where id = 'Q0188' and coalesce(explication, '') = '';
update questions set explication = 'Le chiffre est fixé depuis 1897 ; avant, chaque club négociait l''effectif avant le match.' where id = 'Q0190' and coalesce(explication, '') = '';
update questions set explication = 'Le volant dépasse 400 km/h en smash : la vitesse la plus élevée de tous les sports de raquette.' where id = 'Q0191' and coalesce(explication, '') = '';
update questions set explication = 'Il ne valait aucun point à l''origine : il donnait seulement le droit d''« essayer » de tirer au but.' where id = 'Q0195' and coalesce(explication, '') = '';
update questions set explication = 'Le tournoi porte le nom d''un aviateur, premier à traverser la Méditerranée en 1913.' where id = 'Q0197' and coalesce(explication, '') = '';
update questions set explication = 'Champion du monde 1998 et Ballon d''or, il avait marqué deux buts de la tête en finale.' where id = 'Q0200' and coalesce(explication, '') = '';
update questions set explication = 'Le chiffre vient du parcours de St Andrews, en Écosse, ramené à 18 trous en 1764.' where id = 'Q0204' and coalesce(explication, '') = '';
update questions set explication = 'Les pierres sont taillées dans le granit d''une seule île écossaise, Ailsa Craig.' where id = 'Q0210' and coalesce(explication, '') = '';
update questions set explication = 'Il a égalé Michael Schumacher en 2020 et détient le record de victoires en Grand Prix.' where id = 'Q0213' and coalesce(explication, '') = '';
update questions set explication = 'Le marathon fait 42,195 km : la distance a été fixée aux Jeux de Londres, en 1908.' where id = 'Q0215' and coalesce(explication, '') = '';
update questions set explication = 'Six joueurs, qui tournent d''une position à chaque point gagné sur le service adverse.' where id = 'Q0222' and coalesce(explication, '') = '';
update questions set explication = 'Elle est protégée par une vitre blindée depuis son vol en 1911, qui l''a rendue mondialement célèbre.' where id = 'Q0225' and coalesce(explication, '') = '';
update questions set explication = 'Chez Perrault, la pantoufle est bien « de verre » : l''histoire d''une erreur de traduction avec « vair » est une légende.' where id = 'Q0226' and coalesce(explication, '') = '';
update questions set explication = 'Ils n''ont reçu leurs prénoms qu''au cinéma, chez Disney : les frères Grimm les laissaient anonymes.' where id = 'Q0228' and coalesce(explication, '') = '';
update questions set explication = 'Écrite vers 1595, la pièce s''inspire d''un récit italien publié quelques décennies plus tôt.' where id = 'Q0234' and coalesce(explication, '') = '';
update questions set explication = 'La statue faisait partie de « La Porte de l''Enfer » : le penseur y représentait Dante.' where id = 'Q0239' and coalesce(explication, '') = '';
update questions set explication = 'L''artiste disait s''être inspiré d''un camembert fondant au soleil.' where id = 'Q0241' and coalesce(explication, '') = '';
update questions set explication = 'À 44 ans, il est le deuxième plus jeune lauréat de littérature après Kipling.' where id = 'Q0242' and coalesce(explication, '') = '';
update questions set explication = 'Sur ses 143 tableaux, 55 sont des autoportraits : « je me peins parce que je suis souvent seule ».' where id = 'Q0245' and coalesce(explication, '') = '';
update questions set explication = 'Monet a offert ces huit panneaux à la France au lendemain de l''armistice de 1918.' where id = 'Q0247' and coalesce(explication, '') = '';
update questions set explication = 'Elle prenait un nom d''homme pour être publiée, et fumait le cigare en public, ce qui faisait scandale.' where id = 'Q0251' and coalesce(explication, '') = '';
update questions set explication = 'À l''origine, le riz vinaigré servait à conserver le poisson, et se jetait avant de manger.' where id = 'Q0257' and coalesce(explication, '') = '';
update questions set explication = 'Le sarrasin, base des galettes salées, est arrivé dans la région au XVe siècle.' where id = 'Q0260' and coalesce(explication, '') = '';
update questions set explication = 'Le chou fermente six semaines dans le sel : c''est la fermentation, pas le vin, qui l''acidifie.' where id = 'Q0264' and coalesce(explication, '') = '';
update questions set explication = 'La même épice colore la moutarde américaine ; sa teinte vient de la curcumine.' where id = 'Q0265' and coalesce(explication, '') = '';
update questions set explication = 'Le repas gastronomique des Français est inscrit au patrimoine immatériel de l''Unesco depuis 2010.' where id = 'Q0266' and coalesce(explication, '') = '';
update questions set explication = 'C''était le plat des pêcheurs, fait des poissons de roche invendus.' where id = 'Q0271' and coalesce(explication, '') = '';
update questions set explication = 'Le plat a été popularisé dans les années 1980 par le syndicat du fromage, pour écouler la production.' where id = 'Q0272' and coalesce(explication, '') = '';
update questions set explication = 'Trois minutes pour un blanc pris et un jaune coulant ; six minutes donnent un œuf mollet.' where id = 'Q0274' and coalesce(explication, '') = '';
update questions set explication = 'Ce poisson existe depuis plus de 200 millions d''années ; plusieurs espèces sont aujourd''hui menacées.' where id = 'Q0275' and coalesce(explication, '') = '';
update questions set explication = 'Depuis 2002, seul le fromage grec au lait de brebis peut porter ce nom dans l''Union européenne.' where id = 'Q0281' and coalesce(explication, '') = '';
update questions set explication = 'Protégé dès 1411 par Charles VI, il a obtenu la première appellation d''origine française en 1925.' where id = 'Q0282' and coalesce(explication, '') = '';
update questions set explication = 'Un jour s''ajoute tous les quatre ans, sauf les années séculaires non divisibles par 400 : 1900 ne l''était pas, 2000 si.' where id = 'Q0287' and coalesce(explication, '') = '';
update questions set explication = 'En peinture seulement : en lumière, mélanger ces deux couleurs donnerait du blanc.' where id = 'Q0288' and coalesce(explication, '') = '';
update questions set explication = 'Le w et le k, longtemps réservés aux mots étrangers, n''y figurent officiellement que depuis le XIXe siècle.' where id = 'Q0290' and coalesce(explication, '') = '';
update questions set explication = 'Le mot vient du latin avarus, « avide », de la même racine qu''avidité.' where id = 'Q0291' and coalesce(explication, '') = '';
update questions set explication = 'Même règle pour journal, animal ou vitrail — mais bal, carnaval et festival prennent un s.' where id = 'Q0292' and coalesce(explication, '') = '';
update questions set explication = 'Présenté par Steve Jobs en janvier 2007, il n''avait ni copier-coller ni boutique d''applications.' where id = 'Q0293' and coalesce(explication, '') = '';
update questions set explication = 'L''oiseau s''appelait Larry, en hommage au basketteur Larry Bird. Le réseau est devenu X en 2023.' where id = 'Q0297' and coalesce(explication, '') = '';
update questions set explication = 'Chaque marche multiplie par 1 024, et non par 1 000 : l''informatique compte en puissances de deux.' where id = 'Q0302' and coalesce(explication, '') = '';
update questions set explication = 'Attention au faux ami : le « billion » américain vaut un milliard, pas mille milliards.' where id = 'Q0304' and coalesce(explication, '') = '';
update questions set explication = 'C''est l''une des phobies les plus répandues : près d''une personne sur vingt en souffre.' where id = 'Q0305' and coalesce(explication, '') = '';
update questions set explication = 'Le point-virgule relie deux propositions d''une même phrase : la seconde garde donc sa minuscule.' where id = 'Q0310' and coalesce(explication, '') = '';
update questions set explication = 'Il n''a pas inventé l''ampoule, mais le premier filament assez durable pour la vendre : 1 200 heures avec du bambou carbonisé.' where id = 'Q0311' and coalesce(explication, '') = '';
update questions set explication = 'Le mot « drakkar » est une invention du XIXe siècle : eux disaient « langskip », navire long.' where id = 'Q0318' and coalesce(explication, '') = '';
update questions set explication = 'Dernière souveraine de l''Égypte des Ptolémées, elle parlait neuf langues et descendait d''une lignée grecque.' where id = 'Q0330' and coalesce(explication, '') = '';
update questions set explication = 'Ils fondent l''idée moderne d''État souverain, base du droit international actuel.' where id = 'Q0334' and coalesce(explication, '') = '';
update questions set explication = 'La City, cœur financier, ne fait qu''un mille carré et possède son propre maire, distinct de celui de la ville.' where id = 'Q0337' and coalesce(explication, '') = '';
update questions set explication = 'Bonn a tenu ce rôle de 1949 à 1990 ; le parlement n''est revenu qu''en 1999.' where id = 'Q0340' and coalesce(explication, '') = '';
update questions set explication = 'Détruite par le séisme de 1755, la ville a été rebâtie sur un plan quadrillé antisismique.' where id = 'Q0341' and coalesce(explication, '') = '';
update questions set explication = 'Longue de 430 km, la chaîne abrite l''Andorre, seul pays entièrement pyrénéen.' where id = 'Q0343' and coalesce(explication, '') = '';
update questions set explication = 'C''est la capitale administrative ; Casablanca, bien plus peuplée, est la capitale économique.' where id = 'Q0350' and coalesce(explication, '') = '';
update questions set explication = 'La Russie couvre à elle seule 11 % des terres émergées, sur onze fuseaux horaires.' where id = 'Q0354' and coalesce(explication, '') = '';
update questions set explication = 'C''est la capitale la plus froide du monde : −25 °C de moyenne en janvier.' where id = 'Q0355' and coalesce(explication, '') = '';
update questions set explication = 'La glace flotte parce qu''en gelant l''eau gagne environ 9 % de volume — une exception rare dans la nature.' where id = 'Q0360' and coalesce(explication, '') = '';
update questions set explication = 'Déployée, leur surface d''échange couvrirait un terrain de tennis.' where id = 'Q0362' and coalesce(explication, '') = '';
update questions set explication = 'Sous pression normale : en altitude ou dans l''eau salée, le point de congélation change.' where id = 'Q0363' and coalesce(explication, '') = '';
update questions set explication = 'Soit environ 7 % du poids du corps ; le cœur en fait circuler l''équivalent chaque minute.' where id = 'Q0370' and coalesce(explication, '') = '';
update questions set explication = 'Du nom de James Watt. Un cheval-vapeur vaut 736 watts.' where id = 'Q0371' and coalesce(explication, '') = '';
update questions set explication = 'Jupiter est si grosse que toutes les autres planètes tiendraient à l''intérieur.' where id = 'Q0372' and coalesce(explication, '') = '';
update questions set explication = 'Newton l''a formulée en 1687 ; Einstein l''a réinterprétée en 1915 comme une courbure de l''espace-temps.' where id = 'Q0373' and coalesce(explication, '') = '';
update questions set explication = 'Il l''a essayé sur Joseph Meister, 9 ans, mordu par un chien enragé — alors qu''il n''était pas médecin.' where id = 'Q0375' and coalesce(explication, '') = '';
update questions set explication = 'Il faut butiner 4 millions de fleurs pour produire un kilo de miel.' where id = 'Q0382' and coalesce(explication, '') = '';
update questions set explication = 'Six pattes et trois parties du corps : c''est ce qui le distingue de l''araignée, qui en a huit.' where id = 'Q0383' and coalesce(explication, '') = '';
update questions set explication = 'Elle compte environ 40 000 muscles ; le bras humain en a moins de 800.' where id = 'Q0384' and coalesce(explication, '') = '';
update questions set explication = 'Les chats adultes ne s''en servent presque qu''avec les humains : entre eux, ils communiquent autrement.' where id = 'Q0385' and coalesce(explication, '') = '';
update questions set explication = 'Il se met debout dans l''heure qui suit sa naissance.' where id = 'Q0386' and coalesce(explication, '') = '';
update questions set explication = 'Jusqu''à 4 m au garrot. La baleine bleue est plus grande, mais elle est marine.' where id = 'Q0387' and coalesce(explication, '') = '';
update questions set explication = 'L''image vient du récit biblique du Déluge ; Picasso l''a popularisée en 1949 pour le Congrès de la paix.' where id = 'Q0388' and coalesce(explication, '') = '';
update questions set explication = 'L''autruche atteint 2,70 m, le colibri d''Elena 5 cm : c''est le plus petit oiseau du monde.' where id = 'Q0389' and coalesce(explication, '') = '';
update questions set explication = 'Les chats d''intérieur vivent souvent 18 à 20 ans ; le record homologué est de 38 ans.' where id = 'Q0392' and coalesce(explication, '') = '';
update questions set explication = 'Seul conifère européen à perdre ses aiguilles, il dore les Alpes en octobre avant de se dénuder.' where id = 'Q0398' and coalesce(explication, '') = '';
update questions set explication = 'Ses ailes battent jusqu''à 80 fois par seconde, en dessinant un huit.' where id = 'Q0399' and coalesce(explication, '') = '';
update questions set explication = 'Cinq joueurs — mais l''inventeur du basket en avait prévu neuf par équipe lors du premier match, en 1891.' where id = 'Q0403' and coalesce(explication, '') = '';
update questions set explication = 'Le ballon était à l''origine une vessie de porc, naturellement ovale.' where id = 'Q0404' and coalesce(explication, '') = '';
update questions set explication = 'Toucher la balle avec la main ou le corps fait perdre le point, même par accident.' where id = 'Q0405' and coalesce(explication, '') = '';
update questions set explication = 'France, Angleterre, Écosse, Irlande, Pays de Galles, et l''Italie entrée en 2000.' where id = 'Q0406' and coalesce(explication, '') = '';
update questions set explication = 'Quatre titres individuels en cinq jours : du jamais-vu depuis Michael Phelps.' where id = 'Q0414' and coalesce(explication, '') = '';
update questions set explication = '50 m sur 25, huit à dix couloirs, et 2 m de profondeur minimum.' where id = 'Q0415' and coalesce(explication, '') = '';
update questions set explication = 'Le ballon de basket fait 24 cm de diamètre, la balle de golf 4,3 cm.' where id = 'Q0416' and coalesce(explication, '') = '';
update questions set explication = 'Il a porté le record du monde à 6,16 m en 2014, battant celui de Bubka vieux de 21 ans.' where id = 'Q0418' and coalesce(explication, '') = '';
update questions set explication = 'Quinze titres, dont les cinq premières éditions consécutives à partir de 1956.' where id = 'Q0420' and coalesce(explication, '') = '';
update questions set explication = 'Le personnage devait être à l''origine un pantin de ventriloque, jugé trop inquiétant.' where id = 'Q0426' and coalesce(explication, '') = '';
update questions set explication = 'Le mot vient de l''allemand « Schreck », la frayeur.' where id = 'Q0427' and coalesce(explication, '') = '';
update questions set explication = 'Le studio refusait l''acteur, jugé trop risqué : son essai filmé a emporté la décision.' where id = 'Q0429' and coalesce(explication, '') = '';
update questions set explication = 'Son vrai nom, Tom Elvis Jedusor en français, est l''anagramme de « Je suis Voldemort ».' where id = 'Q0430' and coalesce(explication, '') = '';
update questions set explication = 'Il a plongé douze fois sur l''épave réelle : les images du navire englouti sont authentiques.' where id = 'Q0432' and coalesce(explication, '') = '';
update questions set explication = 'Créée en 1955 ; auparavant, le festival remettait un Grand Prix.' where id = 'Q0433' and coalesce(explication, '') = '';
update questions set explication = 'Le studio était un département de Lucasfilm, racheté par Steve Jobs pour 5 millions de dollars en 1986.' where id = 'Q0440' and coalesce(explication, '') = '';
update questions set explication = 'La catégorie venait d''être créée : le film a devancé Monstres et Cie.' where id = 'Q0443' and coalesce(explication, '') = '';
update questions set explication = 'L''archet est monté avec environ 150 crins de cheval, frottés de colophane.' where id = 'Q0446' and coalesce(explication, '') = '';
update questions set explication = 'La batterie moderne est née à La Nouvelle-Orléans vers 1900, pour qu''un seul musicien tienne plusieurs percussions.' where id = 'Q0447' and coalesce(explication, '') = '';
update questions set explication = 'Le clip de 14 minutes, réalisé par John Landis, a coûté 500 000 dollars : un record à l''époque.' where id = 'Q0448' and coalesce(explication, '') = '';
update questions set explication = 'Puis trio, quatuor, quintette… la série se poursuit jusqu''au nonette, à neuf musiciens.' where id = 'Q0449' and coalesce(explication, '') = '';
update questions set explication = 'Le surnom vient de ses débuts : c''est lui qui récupérait le cachet du groupe et le partageait.' where id = 'Q0450' and coalesce(explication, '') = '';
update questions set explication = 'Le nom est formé des initiales des quatre prénoms : Agnetha, Björn, Benny, Anni-Frid.' where id = 'Q0451' and coalesce(explication, '') = '';
update questions set explication = 'Gaucher, il jouait une guitare de droitier retournée et recordée à l''envers.' where id = 'Q0455' and coalesce(explication, '') = '';
update questions set explication = 'Le manuscrit, retrouvé quarante ans après sa mort, était peut-être dédié à Thérèse : l''écriture du compositeur était illisible.' where id = 'Q0456' and coalesce(explication, '') = '';
update questions set explication = 'Il a composé presque exclusivement pour le piano et donné très peu de concerts publics : une trentaine en vingt ans.' where id = 'Q0458' and coalesce(explication, '') = '';
update questions set explication = 'Yoko Ono a été officiellement reconnue coautrice de la chanson en 2017, quarante-six ans après.' where id = 'Q0459' and coalesce(explication, '') = '';
update questions set explication = 'Le nom de scène vient de « Radio Ga Ga », la chanson de Queen.' where id = 'Q0460' and coalesce(explication, '') = '';
update questions set explication = 'Le ballet a été un échec à sa création en 1877 : il n''a triomphé qu''après la mort du compositeur.' where id = 'Q0463' and coalesce(explication, '') = '';
update questions set explication = 'L''auteur travaillait avec des collaborateurs, dont Auguste Maquet, pour tenir le rythme des feuilletons.' where id = 'Q0467' and coalesce(explication, '') = '';
update questions set explication = 'La fable reprend un texte d''Ésope, écrit en grec vingt-deux siècles plus tôt.' where id = 'Q0468' and coalesce(explication, '') = '';
update questions set explication = 'L''éditeur lui a imposé ses initiales, craignant que les garçons n''achètent pas un livre signé par une femme.' where id = 'Q0469' and coalesce(explication, '') = '';
update questions set explication = 'Chez Perrault, en 1697, l''histoire finit mal : ce sont les frères Grimm qui ont ajouté le chasseur.' where id = 'Q0470' and coalesce(explication, '') = '';
update questions set explication = 'Phileas Fogg gagne son pari grâce au décalage horaire : un jour gagné en franchissant le méridien.' where id = 'Q0471' and coalesce(explication, '') = '';
update questions set explication = 'Haute de 55 cm, la statue possède une garde-robe de près de mille costumes.' where id = 'Q0472' and coalesce(explication, '') = '';
update questions set explication = 'Hergé l''aurait baptisé d''après le surnom d''une amie, Marie-Louise ; en anglais, il s''appelle Snowy.' where id = 'Q0474' and coalesce(explication, '') = '';
update questions set explication = 'L''auteur a écrit 75 romans et 28 nouvelles avec ce personnage, parfois en onze jours.' where id = 'Q0475' and coalesce(explication, '') = '';
update questions set explication = 'Il en a peint plusieurs versions pour décorer la chambre de Gauguin, à Arles.' where id = 'Q0476' and coalesce(explication, '') = '';
update questions set explication = 'Le roman a valu à son auteur un procès pour outrage aux bonnes mœurs en 1857 : il a été acquitté.' where id = 'Q0479' and coalesce(explication, '') = '';
update questions set explication = 'Botaniquement, c''est une baie, et le bananier est une herbe géante, pas un arbre.' where id = 'Q0487' and coalesce(explication, '') = '';
update questions set explication = 'Il faut environ 400 fèves pour obtenir un kilo de chocolat.' where id = 'Q0488' and coalesce(explication, '') = '';
update questions set explication = 'Elle produit du gaz carbonique en digérant les sucres : ce sont ces bulles qui font gonfler la pâte.' where id = 'Q0489' and coalesce(explication, '') = '';
update questions set explication = 'Compter par douze vient des Babyloniens, qui comptaient les phalanges de quatre doigts avec le pouce.' where id = 'Q0490' and coalesce(explication, '') = '';
update questions set explication = 'Blanc, rouge, vert : la pizza aurait été créée en 1889 aux couleurs du drapeau italien, pour la reine Marguerite.' where id = 'Q0492' and coalesce(explication, '') = '';
update questions set explication = 'L''appellation désigne une recette, pas une origine : la plupart des graines viennent aujourd''hui du Canada.' where id = 'Q0495' and coalesce(explication, '') = '';
update questions set explication = 'Le mot signifie simplement « pois chiche » en arabe.' where id = 'Q0496' and coalesce(explication, '') = '';
update questions set explication = 'Né en Vénétie dans les années 1960, son nom signifie « remonte-moi ».' where id = 'Q0497' and coalesce(explication, '') = '';
update questions set explication = 'À cœur, on passe d''environ 50 °C pour un bleu à 70 °C pour un bien cuit.' where id = 'Q0498' and coalesce(explication, '') = '';
update questions set explication = 'Il faut 450 litres de lait pour une meule de 40 kg, affinée au moins quatre mois.' where id = 'Q0501' and coalesce(explication, '') = '';
update questions set explication = 'C''est l''épice la plus chère du monde : il faut 150 000 fleurs pour en obtenir un kilo.' where id = 'Q0504' and coalesce(explication, '') = '';
update questions set explication = 'Trois côtés, trois angles, et une somme d''angles toujours égale à 180°.' where id = 'Q0507' and coalesce(explication, '') = '';
update questions set explication = 'Le calendrier romain n''en comptait que dix : septembre à décembre gardent les noms des 7e au 10e mois.' where id = 'Q0508' and coalesce(explication, '') = '';
update questions set explication = 'Un siècle va de l''an 1 à l''an 100 : le XXIe a donc commencé le 1er janvier 2001.' where id = 'Q0509' and coalesce(explication, '') = '';
update questions set explication = 'Ajouter du blanc éclaircit sans changer la teinte : on parle de nuance pastel.' where id = 'Q0510' and coalesce(explication, '') = '';
update questions set explication = 'La seconde est la seule définie par la physique : 9 192 631 770 vibrations d''un atome de césium.' where id = 'Q0511' and coalesce(explication, '') = '';
update questions set explication = 'Le mot est attesté dès le XVIe siècle, bien avant les débats récents sur la féminisation.' where id = 'Q0513' and coalesce(explication, '') = '';
update questions set explication = 'Matt Groening a donné aux personnages les prénoms de sa propre famille, sauf Bart, anagramme de « brat », le garnement.' where id = 'Q0514' and coalesce(explication, '') = '';
update questions set explication = 'C''est la plus ancienne monnaie encore en circulation : elle a plus de 1 200 ans.' where id = 'Q0517' and coalesce(explication, '') = '';
update questions set explication = 'Du grec penta, cinq. Le bâtiment du Pentagone, à Washington, en a la forme.' where id = 'Q0518' and coalesce(explication, '') = '';
update questions set explication = 'Le mot a été forgé en 1944 par Donald Watson, avec les premières et dernières lettres de « vegetarian ».' where id = 'Q0520' and coalesce(explication, '') = '';
update questions set explication = 'Chaque degré multiplie l''énergie libérée par environ 32 : une magnitude 7 est mille fois plus puissante qu''une 5.' where id = 'Q0521' and coalesce(explication, '') = '';
update questions set explication = 'Vrai en géométrie plane seulement : tracé sur une sphère, un triangle dépasse les 180°.' where id = 'Q0525' and coalesce(explication, '') = '';
update questions set explication = 'Extrait de l''album Cosmopolitanie (2014) du rappeur marseillais.' where id = 'Q1173' and coalesce(explication, '') = '';

-- 166 questions complétées
