-- Explications enrichies : les blind tests n'indiquaient qu'une année.
-- À coller dans Supabase → SQL Editor → Run. Seule la colonne « explication » change.

update questions set explication = 'Le 21 septembre, au lendemain de la victoire de Valmy : la royauté était abolie la veille.' where id = 'Q0331';
update questions set explication = 'Ératosthène l''avait déjà estimée à 250 000 stades, il y a plus de 2 200 ans, à moins de 2 % près.' where id = 'Q0356';
update questions set explication = 'Soit un peu plus d''une seconde-lumière : c''est le temps que met un signal radio pour l''atteindre.' where id = 'Q0380';
update questions set explication = '2017 : le titre le plus écouté de la décennie sur Spotify, extrait de l''album « ÷ ».' where id = 'Q1117';
update questions set explication = '1986. Le riff de synthé avait été composé des années plus tôt, comme simple introduction de concert.' where id = 'Q1118';
update questions set explication = '1976. Le groupe l''a chantée pour la première fois lors du gala donné la veille du mariage du roi de Suède.' where id = 'Q1120';
update questions set explication = '1978. Les gestes qui dessinent les lettres ont été inventés par le public d''une émission de télévision, pas par le groupe.' where id = 'Q1121';
update questions set explication = '1978. D''abord sortie en face B du disque, la chanson est devenue un hymne grâce aux radios.' where id = 'Q1122';
update questions set explication = '1991. Le titre vient d''un déodorant : une amie l''avait écrit sur un mur, Kurt Cobain y a vu une formule.' where id = 'Q1126';
update questions set explication = '2014. Le morceau a demandé des mois d''enregistrement et a remporté le Grammy du disque de l''année.' where id = 'Q1127';
update questions set explication = '2010, premier extrait de l''album « 21 », écrit après une rupture.' where id = 'Q1128';
update questions set explication = '2008. Le titre est emprunté à un tableau de Frida Kahlo peint peu avant sa mort.' where id = 'Q1131';
update questions set explication = '2013. Le mélange de folk et d''électro avait dérouté le public à la première scène, avant de faire le tour du monde.' where id = 'Q1133';
update questions set explication = '2009. Le clip a été l''un des tout premiers à dépasser le milliard de vues sur YouTube.' where id = 'Q1134';
update questions set explication = '2002, extrait de « The Eminem Show », l''album le plus vendu de l''année aux États-Unis.' where id = 'Q1135';
update questions set explication = '2001, sur « Hybrid Theory », l''album de rock le plus vendu des années 2000.' where id = 'Q1136';
update questions set explication = '2017. Le chanteur y raconte la maladie chronique dont il souffre.' where id = 'Q1139';
update questions set explication = '1982. Le groupe hésitait à la sortir : elle est devenue son seul numéro un américain.' where id = 'Q1141';
update questions set explication = '2011, en duo avec Kimbra. La mélodie reprend un morceau de guitare du Brésilien Luiz Bonfá.' where id = 'Q1144';
update questions set explication = '1981. Relancée trente ans plus tard par la série Glee, elle est devenue l''un des titres du XXe siècle les plus téléchargés.' where id = 'Q1146';
update questions set explication = '2007, avec Jay-Z. La chanson avait d''abord été proposée à Britney Spears, qui l''a refusée.' where id = 'Q1147';
update questions set explication = '2013, premier extrait de l''album « Prism ».' where id = 'Q1148';
update questions set explication = '2011. Le morceau est bâti sur un extrait d''Etta James, « Something''s Got a Hold on Me ».' where id = 'Q1150';
update questions set explication = '2009. Le Belge l''a enregistrée chez lui ; Kanye West en a signé un remix l''année suivante.' where id = 'Q1156';
update questions set explication = '1960. Piaf l''a dédiée à la Légion étrangère, qui en a fait l''un de ses chants.' where id = 'Q1157';
update questions set explication = '1998, l''année de ses concerts au Stade de France.' where id = 'Q1158';
update questions set explication = '2013. La chanson évoque le père du chanteur, disparu dans le génocide rwandais.' where id = 'Q1159';
update questions set explication = '2013, premier single de la chanteuse : le clip a dépassé le milliard de vues.' where id = 'Q1160';
update questions set explication = '2018. « Djadja » désigne un menteur ; le titre a été numéro un aux Pays-Bas.' where id = 'Q1161';
update questions set explication = '1977. Le clip a été tourné quelques mois avant la mort accidentelle du chanteur, en mars 1978.' where id = 'Q1163';
update questions set explication = '2010, premier succès de la chanteuse, après des années passées à chanter dans la rue.' where id = 'Q1165';
update questions set explication = '2019. Le titre fait écho au mouvement #MeToo et au mot-clé « Balance ton porc ».' where id = 'Q1167';
update questions set explication = '1984, sur l''album « Positif ».' where id = 'Q1168';
update questions set explication = '1979, en pleine vague disco : l''un des plus gros succès de la chanteuse.' where id = 'Q1169';
update questions set explication = '2015. La chanteuse s''était fait connaître à la télévision, puis au cinéma dans « La Famille Bélier ».' where id = 'Q1170';
update questions set explication = '2016, titre phare de l''album « L''Attrape-rêves ».' where id = 'Q1171';
update questions set explication = '2016, extrait de l''album « Vianney ».' where id = 'Q1172';
update questions set explication = 'Henry Mancini, 1963 : le thème au saxophone ténor a été récompensé par trois Grammy Awards.' where id = 'Q1179';
update questions set explication = '« Hakuna Matata » (1994), signée Elton John et Tim Rice, nommée à l''Oscar de la meilleure chanson.' where id = 'Q1180';
update questions set explication = 'Alan Silvestri, 1985 : il a ensuite composé la musique des trois films de la trilogie.' where id = 'Q1189';
update questions set explication = '« This Is Me » (2017), récompensée par le Golden Globe de la meilleure chanson.' where id = 'Q1192';
update questions set explication = 'Ennio Morricone, 1966. La musique a été composée avant le tournage, pour être diffusée sur le plateau.' where id = 'Q1200';
update questions set explication = 'Nino Rota, 1972. La musique a été écartée des Oscars parce que le compositeur avait réutilisé l''un de ses thèmes.' where id = 'Q1202';
update questions set explication = 'Kenny Loggins, 1984 : trois semaines en tête des ventes aux États-Unis.' where id = 'Q1207';
update questions set explication = 'Amélie Poulain (2001). Le réalisateur avait découvert sa musique en voiture et a repris des morceaux déjà composés.' where id = 'Q1219';
update questions set explication = 'Interstellar (2014). Nolan lui avait seulement remis une lettre sur la paternité, sans parler d''espace.' where id = 'Q1220';
update questions set explication = 'Titanic (1997) : « My Heart Will Go On », que James Cameron ne voulait pas au départ dans son film.' where id = 'Q1221';
update questions set explication = 'Le Parrain (1972), musique de Nino Rota, dont la valse sicilienne est devenue indissociable du film.' where id = 'Q1222';
update questions set explication = '1957, chanson-titre du film où Elvis exécute sa fameuse chorégraphie de prison.' where id = 'Q1224';
update questions set explication = '1958. C''est le seul morceau de rock embarqué sur le disque d''or de la sonde Voyager, en 1977.' where id = 'Q1225';
update questions set explication = '1961. Le titre est redevenu un tube en 1986 grâce au film du même nom.' where id = 'Q1226';
update questions set explication = '1963. John Lennon l''a enregistrée en une prise, la voix éraillée, en fin de journée de studio.' where id = 'Q1227';
update questions set explication = '1964. Le groupe l''a mise en boîte en une seule prise, en un quart d''heure.' where id = 'Q1228';
update questions set explication = '1965. Keith Richards a trouvé le riff en dormant : un magnétophone posé près du lit tournait.' where id = 'Q1229';
update questions set explication = '1967 : un échec aux États-Unis à sa sortie, mais un numéro un au Royaume-Uni.' where id = 'Q1231';
update questions set explication = '1962, son premier succès, adapté d''un titre américain des Everly Brothers.' where id = 'Q1234';
update questions set explication = '1962. Elle avait 18 ans ; le disque s''est vendu à plus de deux millions d''exemplaires.' where id = 'Q1235';
update questions set explication = '1964, écrite pour le film d''Yves Robert « Les Copains ».' where id = 'Q1236';
update questions set explication = '1964, extraite du film « Cherchez l''idole ».' where id = 'Q1237';
update questions set explication = '1965. Aznavour y chante le Montmartre de ses débuts ; il l''a interprétée jusqu''à ses derniers concerts.' where id = 'Q1238';
update questions set explication = '1966, sur des paroles de Jacques Lanzmann qui moquaient déjà l''égocentrisme.' where id = 'Q1240';
update questions set explication = '1969. C''est l''adaptation française d''une chanson anglaise, « Waterloo Road ».' where id = 'Q1241';
update questions set explication = '1972. Le texte de Bernie Taupin décrit un astronaute comme un simple salarié.' where id = 'Q1242';
update questions set explication = '1972. Le riff est joué au clavinet ; Jeff Beck devait à l''origine enregistrer le morceau.' where id = 'Q1243';
update questions set explication = '1976. Le solo final, long de plusieurs minutes, est régulièrement cité parmi les plus grands du rock.' where id = 'Q1244';
update questions set explication = '1977. Entièrement produite au synthétiseur par Giorgio Moroder, elle a ouvert la voie à la musique électronique.' where id = 'Q1245';
update questions set explication = '1978, écrite par Freddie Mercury : elle est devenue un classique des stades bien après sa sortie.' where id = 'Q1246';
update questions set explication = '1978. Le « 21 septembre » du refrain a été choisi parce qu''il sonnait bien, sans autre raison.' where id = 'Q1247';
update questions set explication = '1978. La chanson raconte à sa façon la vie du moine qui fascinait la cour du tsar.' where id = 'Q1248';
update questions set explication = '1979. Le groupe punk new-yorkais s''est mis au disco, au grand dam d''une partie de son public.' where id = 'Q1250';
update questions set explication = '1979. Le chœur d''enfants vient d''une école londonienne, enregistrée en une après-midi.' where id = 'Q1251';
update questions set explication = '1972, avec le Big Bazar, la troupe que le chanteur avait fondée.' where id = 'Q1252';
update questions set explication = '1972 : plus d''un million d''exemplaires vendus.' where id = 'Q1253';
update questions set explication = '1973, l''un de ses plus gros succès, composé avec Jacques Revaux.' where id = 'Q1254';
update questions set explication = '1973, sur une musique d''Alice Dona ; Dalida l''a reprise la même année.' where id = 'Q1255';
update questions set explication = '1975. C''est l''adaptation d''une chanson italienne, « Africa », du groupe Albatros.' where id = 'Q1256';
update questions set explication = '1975. Elle a été reprise en chœur par des générations d''écoliers.' where id = 'Q1257';
update questions set explication = '1977. La voix du disque n''est pas la sienne mais celle du producteur, ce qu''un tribunal a confirmé en 2010.' where id = 'Q1258';
update questions set explication = '1977, sur une musique de Laurent Voulzy, son complice de toujours.' where id = 'Q1259';
update questions set explication = '1977, premier single du groupe : le mot désigne la vitre percée des guichets.' where id = 'Q1260';
update questions set explication = '1979. Cabrel l''a aussi enregistrée en espagnol ; elle reste l''une des chansons les plus diffusées en France.' where id = 'Q1261';
update questions set explication = '1979, produite par Nile Rodgers et Bernard Edwards, du groupe Chic.' where id = 'Q1262';
update questions set explication = '1980, sur « Uprising », l''un des derniers albums parus de son vivant.' where id = 'Q1263';
update questions set explication = '1981, écrite par son père et son frère, tous deux musiciens.' where id = 'Q1264';
update questions set explication = '1983. La chanson avait été écrite par un homme : la chanteuse en a réécrit les paroles pour en faire un hymne féminin.' where id = 'Q1265';
update questions set explication = '1983. Le solo de guitare est signé Eddie Van Halen, qui a refusé d''être payé.' where id = 'Q1266';
update questions set explication = '1983, écrite par Jim Steinman, qui la destinait d''abord à une comédie musicale de vampires.' where id = 'Q1267';
update questions set explication = '1984. Jamais numéro un à sa sortie, la chanson y est enfin parvenue au Royaume-Uni en 2021.' where id = 'Q1268';
update questions set explication = '1984. Le clip, où le groupe se travestit, a été interdit d''antenne par MTV aux États-Unis.' where id = 'Q1269';
update questions set explication = '1987, premier numéro un américain du groupe irlandais.' where id = 'Q1270';
update questions set explication = '1987. La chanteuse trouvait le morceau trop léger avant d''en faire son plus grand succès dansant.' where id = 'Q1271';
update questions set explication = '1989. Le clip a coûté à la chanteuse son contrat publicitaire avec Pepsi.' where id = 'Q1272';
update questions set explication = '1989. La chanson avait d''abord été enregistrée par Bonnie Tyler, l''année précédente.' where id = 'Q1273';
update questions set explication = '1989. Le tube de l''été était l''adaptation non créditée d''une chanson bolivienne : l''affaire a fini au tribunal.' where id = 'Q1274';
update questions set explication = '1982. Le titre a lancé sa carrière solo après des débuts discrets en groupe.' where id = 'Q1275';
update questions set explication = '1982. Le personnage est inspiré de Bob Morane, héros de romans d''aventures.' where id = 'Q1276';
update questions set explication = '1984, sur l''album du même nom : le dernier grand succès du groupe avant sa séparation.' where id = 'Q1277';
update questions set explication = '1984, l''un des titres emblématiques de la variété française des années 80.' where id = 'Q1278';
update questions set explication = '1984, sur l''album « La Notte, la Notte ».' where id = 'Q1279';
update questions set explication = '1985, chanson contre le racisme dédiée à sa femme. Le chanteur est mort quelques mois plus tard dans un accident d''hélicoptère.' where id = 'Q1280';
update questions set explication = '1985. Le titre évoque un bonbon disparu ; la chanson arrive régulièrement en tête des préférées des Français.' where id = 'Q1281';
update questions set explication = '1985, le grand succès du groupe toulousain.' where id = 'Q1282';
update questions set explication = '1986. Le clip, tourné comme un film en costumes, a marqué le début d''une longue collaboration avec Laurent Boutonnat.' where id = 'Q1283';
update questions set explication = '1986. Chantée en français, elle a été numéro un dans une dizaine de pays, dont l''Allemagne.' where id = 'Q1284';
update questions set explication = '1986, le tube de l''été devenu un incontournable des soirées dansantes.' where id = 'Q1285';
update questions set explication = '1988 : plus d''un million d''exemplaires vendus.' where id = 'Q1286';
update questions set explication = '1989. La chanson a fait du chanteur un phénomène de société : on a parlé de « bruelmania ».' where id = 'Q1287';
update questions set explication = '1991. L''expression signifie « perdre patience » dans le sud des États-Unis, et non perdre la foi.' where id = 'Q1288';
update questions set explication = '1993, indissociable depuis du sketch des « Roxbury Guys » du Saturday Night Live.' where id = 'Q1289';
update questions set explication = '1994. Dolores O''Riordan l''a écrite après un attentat en Angleterre, pendant le conflit nord-irlandais.' where id = 'Q1290';
update questions set explication = '1995, bâtie sur un morceau de Stevie Wonder et utilisée dans le film « Esprits rebelles ».' where id = 'Q1291';
update questions set explication = '1996. Le clip a été tourné en une seule prise, dans un hôtel londonien.' where id = 'Q1292';
update questions set explication = '1996. Gwen Stefani l''a écrite sur sa rupture avec le bassiste du groupe, resté à ses côtés.' where id = 'Q1293';
update questions set explication = '1997. Mattel a attaqué le groupe en justice ; la chanson a été jugée parodie et protégée à ce titre.' where id = 'Q1294';
update questions set explication = '1998. Le groupe italien a placé ce titre en tête des ventes dans une vingtaine de pays.' where id = 'Q1295';
update questions set explication = '1999. Les paroles ne veulent pas dire grand-chose : le groupe a gardé la version qui sonnait le mieux.' where id = 'Q1296';
update questions set explication = '1999. Le titre a ouvert la voie à la vague pop latine aux États-Unis.' where id = 'Q1297';
update questions set explication = '1999. Le morceau reprend un mambo cubain de Pérez Prado enregistré en 1949.' where id = 'Q1298';
update questions set explication = '1990, l''un des tout premiers grands succès du rap français.' where id = 'Q1299';
update questions set explication = '1991. Le clip de huit minutes a été tourné en Hongrie, avec des centaines de figurants.' where id = 'Q1300';
update questions set explication = '1993, premier grand succès de la chanteuse belge.' where id = 'Q1301';
update questions set explication = '1994. Le titre se moque des soirées marseillaises des années 80 ; il a été numéro un des ventes.' where id = 'Q1302';
update questions set explication = '1995, l''un des titres phares du rap funk français.' where id = 'Q1303';
update questions set explication = '1996, extrait de l''album « Superflu ».' where id = 'Q1304';
update questions set explication = '1996, écrite par Jean-Jacques Goldman ; le roi du raï l''a aussi enregistrée en arabe.' where id = 'Q1305';
update questions set explication = '1998. Le groupe toulousain a reçu la Victoire de la chanson de l''année, en pleine Coupe du monde.' where id = 'Q1306';
update questions set explication = '1998. Le refrain emprunte à un air traditionnel breton popularisé par Alan Stivell.' where id = 'Q1307';
update questions set explication = '2001. Le fameux « la la la » a été numéro un dans plus de quarante pays.' where id = 'Q1309';
update questions set explication = '2002. Le motif de piano a été écrit de nuit, à la toute fin de l''enregistrement de l''album.' where id = 'Q1310';
update questions set explication = '2003, premier single solo de la chanteuse après les Destiny''s Child, avec Jay-Z.' where id = 'Q1311';
update questions set explication = '2003. Le duo d''Atlanta y mêle funk, rock et rap ; le morceau a décroché un Grammy.' where id = 'Q1312';
update questions set explication = '2005. Le chanteur a lui-même reconnu que le succès du titre l''avait rendu « agaçant ».' where id = 'Q1314';
update questions set explication = '2006, avec Wyclef Jean : premier numéro un américain de la Colombienne.' where id = 'Q1315';
update questions set explication = '2006. C''est le premier titre arrivé en tête au Royaume-Uni grâce aux seuls téléchargements.' where id = 'Q1316';
update questions set explication = '2006, extrait de « Life in Cartoon Motion », premier album du chanteur.' where id = 'Q1317';
update questions set explication = '2008, son tout premier succès, écrit en dix minutes selon la chanteuse.' where id = 'Q1318';
update questions set explication = '2009 : quatorze semaines en tête des ventes aux États-Unis.' where id = 'Q1319';
update questions set explication = '2003. Le chanteur, rescapé du génocide rwandais, y raconte son parcours.' where id = 'Q1320';
update questions set explication = '2003, l''un des plus gros succès de vente de l''année en France.' where id = 'Q1321';
update questions set explication = '2003, en duo avec Sita : l''album du même nom s''est vendu à plus d''un million d''exemplaires.' where id = 'Q1322';
update questions set explication = '2004, devenue une chanson de fin d''année scolaire dans beaucoup d''écoles.' where id = 'Q1323';
update questions set explication = '2004. La chanteuse s''était fait connaître dans l''émission Nouvelle Star.' where id = 'Q1324';
update questions set explication = '2005, sur l''album « La Femme chocolat ».' where id = 'Q1325';
update questions set explication = '2005. La chanson égrène les prétextes trouvés pour éviter une soirée entre amis.' where id = 'Q1326';
update questions set explication = '2006, extrait de « Dans ma bulle », album le plus vendu de l''année en France.' where id = 'Q1327';
update questions set explication = '2006, le titre qui a fait connaître le groupe mené par Jennifer Ayache.' where id = 'Q1328';
update questions set explication = '2007, premier grand succès du chanteur.' where id = 'Q1329';
update questions set explication = '2008. L''album a été financé par les internautes, une première en France.' where id = 'Q1330';
update questions set explication = '2010, premier numéro un américain du chanteur hawaïen.' where id = 'Q1331';
update questions set explication = '2011, en duo avec Christina Aguilera, en pleine émission The Voice.' where id = 'Q1332';
update questions set explication = '2011. Le duo réunit un fils et un petit-fils du fondateur du label Motown.' where id = 'Q1333';
update questions set explication = '2011. Enregistrée avec un simple piano, la chanson a fait pleurer les plateaux de télévision du monde entier.' where id = 'Q1334';
update questions set explication = '2012. Le duo de Seattle s''est fait connaître sans maison de disques.' where id = 'Q1335';
update questions set explication = '2014. Le clip, dansé par Maddie Ziegler, 11 ans, a dépassé le milliard de vues.' where id = 'Q1336';
update questions set explication = '2014, avec Jess Glynne : le groupe britannique mêle musique classique et électro.' where id = 'Q1337';
update questions set explication = '2014. C''est le remix du DJ allemand Felix Jaehn qui a transformé ce titre jamaïcain en tube mondial.' where id = 'Q1338';
update questions set explication = '2015, avec MØ. Le clip a été tourné en Inde.' where id = 'Q1339';
update questions set explication = '2016, écrite pour le film d''animation « Les Trolls ».' where id = 'Q1340';
update questions set explication = '2013. Le titre est resté plus d''un an dans les classements français.' where id = 'Q1341';
update questions set explication = '2014, premier album solo après le groupe Sexion d''Assaut.' where id = 'Q1342';
update questions set explication = '2014, extrait de l''album « Cosmopolitanie ».' where id = 'Q1343';
update questions set explication = '2015, le titre qui l''a révélé, accompagné d''une simple guitare.' where id = 'Q1344';
update questions set explication = '2016. Le rappeur marseillais produit lui-même ses morceaux, à un rythme record.' where id = 'Q1345';
update questions set explication = '2017. La chanson raconte quatre destins gâchés par le manque d''audace.' where id = 'Q1346';
update questions set explication = '2018, premier grand succès de la chanteuse, sur l''album « Sainte-Victoire ».' where id = 'Q1347';
update questions set explication = '2018. Le frère et la sœur, tous deux belges, y chantent ensemble.' where id = 'Q1348';
update questions set explication = '2019. La chanteuse est l''artiste française la plus écoutée dans le monde.' where id = 'Q1349';
update questions set explication = '2019, hommage aux femmes et l''un de ses plus gros succès.' where id = 'Q1350';
update questions set explication = '2020. Sortie pendant la pandémie, la chanson a mis plus d''un an à atteindre la première place américaine.' where id = 'Q1351';
update questions set explication = '2021. Écrite à 17 ans, elle a battu le record d''écoutes en une semaine sur Spotify.' where id = 'Q1352';
update questions set explication = '2022, le titre le plus écouté de l''année dans le monde.' where id = 'Q1353';
update questions set explication = '2023. La chanson répond à « When I Was Your Man » de Bruno Mars, en inversant les paroles.' where id = 'Q1354';
update questions set explication = '2021, son retour après huit ans d''absence : la chanson salue ceux qui travaillent pendant les fêtes.' where id = 'Q1355';
update questions set explication = '2021, déclaration d''amour de la chanteuse à sa ville natale.' where id = 'Q1356';
update questions set explication = '2023. La chanteuse nazairienne a raflé quatre Victoires de la musique l''année suivante.' where id = 'Q1358';
update questions set explication = '2024, premier succès solo de la chanteuse, ancienne voix du groupe Hyphen Hyphen.' where id = 'Q1359';
update questions set explication = '2024. Le chanteur venait de remporter la Star Academy.' where id = 'Q1360';
update questions set explication = '« Ce rêve bleu » (1992) a remporté l''Oscar de la meilleure chanson pour Alan Menken et Tim Rice.' where id = 'Q1372';
update questions set explication = 'John Williams, 1993 : le thème majestueux contraste volontairement avec la peur que distille le film.' where id = 'Q1373';
update questions set explication = 'Alan Silvestri, 2012. Le thème revient dans toute la saga, jusqu''à Endgame.' where id = 'Q1376';
update questions set explication = 'Hans Zimmer, 2021. Il a renoncé à un film de Christopher Nolan pour composer celui-ci, adapté d''un roman qu''il aime depuis l''adolescence.' where id = 'Q1381';
update questions set explication = '« Vendez-moi ce stylo » : la scène du film de Martin Scorsese (2013) est devenue un exercice classique en école de commerce.' where id = 'Q1424';
update questions set explication = '1979, sur l''album « Breakfast in America ».' where id = 'Q1440';
update questions set explication = '1971 : plus d''un million de disques vendus.' where id = 'Q1442';
update questions set explication = '1984, premier grand succès du trio de producteurs Stock, Aitken et Waterman.' where id = 'Q1451';
update questions set explication = '1985. Écrite en quelques jours, elle a été ajoutée à l''album au dernier moment.' where id = 'Q1452';
update questions set explication = '1986. Le groupe hésitait à la garder : elle est devenue son plus grand succès.' where id = 'Q1453';
update questions set explication = '1987 : la chanteuse avait 14 ans, et le titre est resté onze semaines en tête.' where id = 'Q1456';
update questions set explication = '1986, le tube du duo rennais, porté par la voix de Muriel Moreno.' where id = 'Q1457';
update questions set explication = '1985, l''un des grands succès de la variété française des années 80.' where id = 'Q1458';
update questions set explication = '1985. Le groupe tire son nom du vocabulaire des petites annonces.' where id = 'Q1460';
update questions set explication = '1983. Aveugle de naissance, le chanteur en a fait un incontournable des soirées dansantes.' where id = 'Q1461';
update questions set explication = '1995. Les situations décrites relèvent plutôt de la malchance que de l''ironie : la chanteuse en plaisante elle-même.' where id = 'Q1462';
update questions set explication = '1992. Le groupe suédois a vendu plus de 20 millions d''exemplaires de son premier album.' where id = 'Q1463';
update questions set explication = '1992, l''un des titres phares de la vague eurodance.' where id = 'Q1464';
update questions set explication = '1997. La chanson a relancé sa carrière après son départ de Take That.' where id = 'Q1466';
update questions set explication = '1999, titre de l''album qui marquait le retour du guitariste John Frusciante.' where id = 'Q1467';
update questions set explication = '1991, enregistrée à Memphis avec des musiciens américains.' where id = 'Q1468';
update questions set explication = '1997, écrite par Lionel Florence et Pascal Obispo.' where id = 'Q1469';
update questions set explication = '1999. La chanteuse venait de triompher dans la comédie musicale Notre-Dame de Paris.' where id = 'Q1471';
update questions set explication = '1988, écrite par Didier Barbelivien.' where id = 'Q1472';
update questions set explication = '2006. Le titre a valu à la chanteuse britannique cinq Grammy Awards en une soirée.' where id = 'Q1473';
update questions set explication = '2001, premier single de la chanteuse, récompensé par trois Grammy.' where id = 'Q1478';
update questions set explication = '2014. Le titre marquait son passage de la country à la pop.' where id = 'Q1486';
update questions set explication = '2014. Héloïse Letissier a inventé ce personnage après un séjour à Londres.' where id = 'Q1488';
update questions set explication = '2013, sur l''album « Løve », disque de platine en France.' where id = 'Q1489';
update questions set explication = '2017. Le clip, tourné dans un hôtel de Miami, a dépassé le milliard de vues.' where id = 'Q1491';
update questions set explication = '2017, avec Young Thug : la chanteuse cubano-américaine y évoque sa ville natale.' where id = 'Q1492';
update questions set explication = '2024, le tube de l''été révélé sur la scène du festival Coachella.' where id = 'Q1495';
update questions set explication = '2021, chanson-titre d''un album entièrement tourné vers le disco.' where id = 'Q1497';
update questions set explication = '2024 : quatrième place à l''Eurovision, le meilleur résultat français depuis 2021.' where id = 'Q1499';
update questions set explication = '« Je te vois » : la formule des Na''vi dans le film de James Cameron (2009) signifie voir l''autre tel qu''il est vraiment.' where id = 'Q1519';

-- 212 questions enrichies
