/**
 * Banque de blind tests (2) — musique de toutes les époques, musiques de films et répliques cultes.
 * Format : comme BanqueBlindTest.gs, plus une 15e valeur : l'année (sert à remplir la colonne « Époque »).
 *
 * Tous les liens ont été vérifiés (vidéo existante et lecture intégrée autorisée) en septembre 2026.
 * La durée de l'extrait suit le temps de réponse de la partie (30 s de chrono = 30 s d'extrait).
 */
function banqueBlindTest2_() {
  const M = 'Blind test musique', C = 'Blind test cinéma';
  const I = 'International', F = 'Chanson française';
  const yt = id => 'https://www.youtube.com/watch?v=' + id;
  const TITRE = '🎵 Quel est ce titre ?';
  const FILM = '🎬 De quel film vient cette musique ?';
  const REPLIQUE = '🎬 De quel film vient cette réplique ?';
  // m = morceau : catégorie, difficulté, id YouTube, début (s), année, bonne réponse, 3 pièges, explication facultative
  const m = (cat, diff, id, start, year, rep, c2, c3, c4, expl) =>
    [M, cat, diff, 'QCM', TITRE, rep, c2, c3, c4, expl || String(year) + '.', '', yt(id), start, 15, year];
  // f = film : catégorie, difficulté, id, début, année, question, bonne réponse, 3 pièges, explication, indices MJ
  const f = (cat, diff, id, start, year, q, rep, c2, c3, c4, expl, ind) =>
    [C, cat, diff, 'QCM', q, rep, c2, c3, c4, expl, ind || '', yt(id), start, 15, year];

  return [
    // ================= MUSIQUE — années 50-60 =================
    m(I, 1, 'PpsUOOfb-vE', 0, 1957, 'Elvis Presley – Jailhouse Rock', 'Elvis Presley – Hound Dog', 'Chuck Berry – Johnny B. Goode', 'Little Richard – Tutti Frutti'),
    m(I, 2, 'Y-9Y4CCIWnM', 0, 1958, 'Chuck Berry – Johnny B. Goode', 'Elvis Presley – Blue Suede Shoes', 'Jerry Lee Lewis – Great Balls of Fire', 'Bill Haley – Rock Around the Clock'),
    m(I, 1, 'hwZNL7QVJjE', 0, 1961, 'Ben E. King – Stand by Me', 'Otis Redding – (Sittin\' On) The Dock of the Bay', 'Sam Cooke – Wonderful World', 'The Drifters – Save the Last Dance for Me'),
    m(I, 2, '2RicaUqd9Hg', 0, 1963, 'The Beatles – Twist and Shout', 'The Beatles – I Want to Hold Your Hand', 'The Kinks – You Really Got Me', 'The Beach Boys – Surfin\' U.S.A.'),
    m(I, 3, 'PqW4GCmQSt4', 0, 1964, 'The Animals – The House of the Rising Sun', 'The Byrds – Mr. Tambourine Man', 'The Doors – Light My Fire', 'Bob Dylan – Like a Rolling Stone'),
    m(I, 2, 'nrIPxlFzDi0', 0, 1965, 'The Rolling Stones – (I Can\'t Get No) Satisfaction', 'The Rolling Stones – Paint It Black', 'The Who – My Generation', 'The Kinks – You Really Got Me'),
    m(I, 2, '9iayJ8u4Qew', 0, 1967, 'Aretha Franklin – Respect', 'Diana Ross & The Supremes – Baby Love', 'Otis Redding – Try a Little Tenderness', 'Tina Turner – River Deep, Mountain High', '1967. La chanson avait d\'abord été écrite et chantée par Otis Redding.'),
    m(I, 1, 'rBrd_3VMC3c', 0, 1967, 'Louis Armstrong – What a Wonderful World', 'Frank Sinatra – Fly Me to the Moon', 'Nat King Cole – L-O-V-E', 'Ray Charles – Georgia on My Mind'),
    m(I, 3, '9C1BCAgu2I8', 0, 1968, 'Simon & Garfunkel – Mrs. Robinson', 'Simon & Garfunkel – The Sound of Silence', 'The Mamas & the Papas – California Dreamin\'', 'Bob Dylan – Blowin\' in the Wind', '1968, pour le film « Le Lauréat ».'),
    m(I, 2, 'qQzdAsjWGPg', 0, 1969, 'Frank Sinatra – My Way', 'Frank Sinatra – New York, New York', 'Elvis Presley – Can\'t Help Falling in Love', 'Dean Martin – That\'s Amore', '1969. Adaptation de « Comme d\'habitude » de Claude François.'),

    m(F, 2, 'F6anG1hPs44', 0, 1962, 'Claude François – Belles ! Belles ! Belles !', 'Claude François – Cette année-là', 'Johnny Hallyday – Souvenirs, souvenirs', 'Richard Anthony – J\'entends siffler le train'),
    m(F, 3, '5cSFjJ4CJKc', 0, 1962, 'Françoise Hardy – Tous les garçons et les filles', 'Françoise Hardy – Comment te dire adieu', 'Sylvie Vartan – Tous mes copains', 'Sheila – L\'École est finie'),
    m(F, 3, 'PT7U_GzRIv0', 0, 1964, 'Georges Brassens – Les Copains d\'abord', 'Georges Brassens – La Mauvaise Réputation', 'Jacques Brel – Le Plat Pays', 'Léo Ferré – Avec le temps'),
    m(F, 3, 'sfiuaOWjEkI', 0, 1964, 'Sylvie Vartan – La plus belle pour aller danser', 'Sylvie Vartan – Comme un garçon', 'France Gall – Laisse tomber les filles', 'Françoise Hardy – Le Temps de l\'amour'),
    m(F, 2, 'fVfnEyLOkrM', 0, 1965, 'Charles Aznavour – La Bohème', 'Charles Aznavour – Emmenez-moi', 'Gilbert Bécaud – Et maintenant', 'Jacques Brel – Amsterdam'),
    m(F, 3, 'rRva0YOVtcI', 0, 1965, 'France Gall – Poupée de cire, poupée de son', 'France Gall – Laisse tomber les filles', 'Sylvie Vartan – La plus belle pour aller danser', 'Sheila – L\'École est finie', '1965. Victoire à l\'Eurovision pour le Luxembourg, écrite par Serge Gainsbourg.'),
    m(F, 3, 'mTj8rizW9Bg', 0, 1966, 'Jacques Dutronc – Et moi, et moi, et moi', 'Jacques Dutronc – Il est cinq heures, Paris s\'éveille', 'Serge Gainsbourg – Le Poinçonneur des Lilas', 'Antoine – Les Élucubrations d\'Antoine'),
    m(F, 1, 'tDWeLlvYyYU', 0, 1969, 'Joe Dassin – Les Champs-Élysées', 'Joe Dassin – L\'Été indien', 'Claude François – Comme d\'habitude', 'Michel Delpech – Pour un flirt'),

    // ================= MUSIQUE — années 70 =================
    m(I, 2, 'DtVBCG6ThDk', 0, 1972, 'Elton John – Rocket Man', 'Elton John – Your Song', 'David Bowie – Space Oddity', 'Billy Joel – Piano Man'),
    m(I, 2, 'ftdZ363R9kQ', 0, 1972, 'Stevie Wonder – Superstition', 'Stevie Wonder – Sir Duke', 'James Brown – Sex Machine', 'Marvin Gaye – Let\'s Get It On'),
    m(I, 2, 'dLl4PZtxia8', 0, 1976, 'Eagles – Hotel California', 'Fleetwood Mac – Go Your Own Way', 'Lynyrd Skynyrd – Sweet Home Alabama', 'Led Zeppelin – Stairway to Heaven'),
    m(I, 3, 'yEbaeLv-aOo', 0, 1977, 'Donna Summer – I Feel Love', 'Donna Summer – Hot Stuff', 'Gloria Gaynor – I Will Survive', 'Giorgio Moroder – Chase'),
    m(I, 1, 'HgzGwKwLmgM', 0, 1978, 'Queen – Don\'t Stop Me Now', 'Queen – We Are the Champions', 'Elton John – I\'m Still Standing', 'David Bowie – Starman'),
    m(I, 1, 'Gs069dndIYk', 0, 1978, 'Earth, Wind & Fire – September', 'Earth, Wind & Fire – Boogie Wonderland', 'Kool & The Gang – Celebration', 'Chic – Le Freak'),
    m(I, 2, 'Nl_Eo2QzqU4', 0, 1978, 'Boney M. – Rasputin', 'Boney M. – Daddy Cool', 'ABBA – Gimme! Gimme! Gimme!', 'Village People – In the Navy'),
    m(I, 3, '9UaJAnnipkY', 0, 1978, 'Patrick Hernandez – Born to Be Alive', 'Village People – Go West', 'Boney M. – Sunny', 'Cerrone – Supernature', '1978. Un chanteur français, numéro 1 dans le monde entier.'),
    m(I, 2, 'WGU_4-5RaxU', 0, 1979, 'Blondie – Heart of Glass', 'Blondie – Call Me', 'Donna Summer – Hot Stuff', 'The Police – Roxanne'),
    m(I, 2, 'HrxX9TBj2zY', 0, 1979, 'Pink Floyd – Another Brick in the Wall', 'Pink Floyd – Money', 'Supertramp – The Logical Song', 'The Police – Message in a Bottle'),

    m(F, 2, 'hHiD6ShYCCA', 0, 1972, 'Michel Fugain – Une belle histoire', 'Michel Fugain – Fais comme l\'oiseau', 'Gérard Lenorman – La Ballade des gens heureux', 'Joe Dassin – Salut les amoureux'),
    m(F, 2, 'e1Fm-7FLu4Q', 0, 1972, 'Claude François – Le Lundi au soleil', 'Claude François – Alexandrie Alexandra', 'Mike Brant – Qui saura', 'C. Jérôme – Kiss Me'),
    m(F, 2, '6YJ_V5V9Zek', 0, 1973, 'Michel Sardou – La Maladie d\'amour', 'Michel Sardou – En chantant', 'Julien Clerc – Ma préférence', 'Serge Lama – Je suis malade'),
    m(F, 3, 'CHOcuP0gUR0', 0, 1973, 'Serge Lama – Je suis malade', 'Serge Lama – Les Petites Femmes de Pigalle', 'Jacques Brel – Ne me quitte pas', 'Michel Sardou – Je vais t\'aimer'),
    m(F, 1, 'tQb4eWCAq8c', 0, 1975, 'Joe Dassin – L\'Été indien', 'Joe Dassin – Et si tu n\'existais pas', 'Mike Brant – Laisse-moi t\'aimer', 'Michel Sardou – Les Vieux Mariés'),
    m(F, 3, 'he4jmetnkQY', 5, 1975, 'Gérard Lenorman – La Ballade des gens heureux', 'Gérard Lenorman – Si j\'étais président', 'Michel Fugain – Une belle histoire', 'Hervé Vilard – Nous'),
    m(F, 2, '8soQkubMk1g', 0, 1977, 'Plastic Bertrand – Ça plane pour moi', 'Téléphone – Hygiaphone', 'Jacques Dutronc – L\'Opportuniste', 'Les Charlots – Merci patron'),
    m(F, 3, 'AgdUnj9iyvc', 0, 1977, 'Alain Souchon – Allô maman bobo', 'Alain Souchon – J\'ai dix ans', 'Laurent Voulzy – Rockollection', 'Renaud – Laisse béton'),
    m(F, 3, 'w3syLw_FZaY', 0, 1977, 'Téléphone – Hygiaphone', 'Téléphone – Un autre monde', 'Trust – Antisocial', 'Plastic Bertrand – Ça plane pour moi'),
    m(F, 2, 'WRHZoMq3TXc', 0, 1979, 'Francis Cabrel – Je l\'aime à mourir', 'Francis Cabrel – Petite Marie', 'Alain Souchon – Foule sentimentale', 'Maxime Le Forestier – San Francisco'),
    m(F, 2, 'xeRfywfkd8o', 0, 1979, 'Sheila – Spacer', 'Sheila – L\'École est finie', 'Dalida – Laissez-moi danser', 'Amanda Lear – Follow Me'),

    // ================= MUSIQUE — années 80 =================
    m(I, 3, '1ti2YCFgCoI', 0, 1980, 'Bob Marley & The Wailers – Could You Be Loved', 'Bob Marley – No Woman, No Cry', 'UB40 – Red Red Wine', 'Jimmy Cliff – Reggae Night'),
    m(I, 3, 'VIN0q8vDQJc', 0, 1981, 'Kim Wilde – Cambodia', 'Kim Wilde – Kids in America', 'Blondie – Call Me', 'Eurythmics – Sweet Dreams'),
    m(I, 1, 'jRr5EasAq84', 0, 1983, 'Cyndi Lauper – Girls Just Want to Have Fun', 'Madonna – Holiday', 'Bananarama – Venus', 'The Bangles – Walk Like an Egyptian'),
    m(I, 1, 'kOn-HdEg6AQ', 0, 1983, 'Michael Jackson – Beat It', 'Michael Jackson – Thriller', 'Prince – When Doves Cry', 'Lionel Richie – Hello'),
    m(I, 2, 'lcOxhH8N3Bo', 10, 1983, 'Bonnie Tyler – Total Eclipse of the Heart', 'Bonnie Tyler – It\'s a Heartache', 'Tina Turner – The Best', 'Céline Dion – It\'s All Coming Back to Me Now'),
    m(I, 1, 'T0T9GyM28tg', 0, 1984, 'Wham! – Last Christmas', 'Wham! – Wake Me Up Before You Go-Go', 'Mariah Carey – All I Want for Christmas Is You', 'Band Aid – Do They Know It\'s Christmas?'),
    m(I, 2, 'WUOtCLOXgm8', 0, 1984, 'Queen – I Want to Break Free', 'Queen – Radio Ga Ga', 'David Bowie – Let\'s Dance', 'Duran Duran – The Reflex'),
    m(I, 2, 'ujNeHIo7oTE', 0, 1987, 'U2 – With or Without You', 'U2 – One', 'Simple Minds – Don\'t You (Forget About Me)', 'The Police – Every Breath You Take'),
    m(I, 1, 'eH3giaIzONA', 10, 1987, 'Whitney Houston – I Wanna Dance with Somebody', 'Whitney Houston – How Will I Know', 'Madonna – Material Girl', 'Tina Turner – What\'s Love Got to Do with It'),
    m(I, 1, '79fzeNUqQbQ', 0, 1989, 'Madonna – Like a Prayer', 'Madonna – Like a Virgin', 'Cyndi Lauper – Time After Time', 'Whitney Houston – So Emotional'),
    m(I, 2, '8Afffdv5Tfg', 30, 1989, 'Tina Turner – The Best', 'Tina Turner – Private Dancer', 'Bonnie Tyler – Holding Out for a Hero', 'Pat Benatar – Love Is a Battlefield'),
    m(I, 2, 'WMT5XzXFhUs', 0, 1989, 'Kaoma – Lambada', 'Gipsy Kings – Bamboléo', 'Los del Río – Macarena', 'Carlos – Big Bisou'),

    m(F, 1, '-boDeijWuOY', 0, 1982, 'Jean-Jacques Goldman – Quand la musique est bonne', 'Jean-Jacques Goldman – Envole-moi', 'Daniel Balavoine – Le Chanteur', 'Michel Berger – Quelques mots d\'amour'),
    m(F, 2, 'M7X6oYg6iro', 0, 1982, 'Indochine – L\'Aventurier', 'Indochine – 3e Sexe', 'Téléphone – Cendrillon', 'Taxi Girl – Cherchez le garçon'),
    m(F, 2, 'NrQnuMnL2ac', 0, 1984, 'Téléphone – Un autre monde', 'Téléphone – Ça (c\'est vraiment toi)', 'Noir Désir – Aux sombres héros de l\'amer', 'Indochine – Canary Bay'),
    m(F, 2, 'J0_Pqo1U90U', 0, 1984, 'Jeanne Mas – Toute première fois', 'Jeanne Mas – En rouge et noir', 'Desireless – Voyage, voyage', 'Elsa – T\'en va pas'),
    m(F, 3, 'Ft2U58G5Szw', 0, 1984, 'Étienne Daho – Week-end à Rome', 'Étienne Daho – Le Grand Sommeil', 'Indochine – Canary Bay', 'Alain Chamfort – Manureva'),
    m(F, 2, 'O4ACXQxCgc8', 10, 1985, 'Daniel Balavoine – L\'Aziza', 'Daniel Balavoine – SOS d\'un terrien en détresse', 'Jean-Jacques Goldman – Je marche seul', 'France Gall – Ella, elle l\'a'),
    m(F, 2, 'Tuoh3o0CM3Y', 0, 1985, 'Renaud – Mistral gagnant', 'Renaud – Morgane de toi', 'Francis Cabrel – Petite Marie', 'Alain Souchon – Foule sentimentale'),
    m(F, 2, '4sZ7eR451Vc', 10, 1985, 'Gold – Capitaine abandonné', 'Gold – Plus près des étoiles', 'Images – Maîtresse', 'Cock Robin – When Your Heart Is Weak'),
    m(F, 3, 'BsI8scmA3lk', 0, 1986, 'Mylène Farmer – Libertine', 'Mylène Farmer – Sans contrefaçon', 'Jeanne Mas – Johnny, Johnny', 'Elsa – T\'en va pas'),
    m(F, 1, 'T7YJoGXs2i8', 0, 1986, 'Desireless – Voyage, voyage', 'Jeanne Mas – Toute première fois', 'Images – Les Démons de minuit', 'Gold – Capitaine abandonné'),
    m(F, 1, 'j1ZeCpUPLtA', 0, 1986, 'Images – Les Démons de minuit', 'Début de Soirée – Nuit de folie', 'Gold – Plus près des étoiles', 'Partenaire Particulier – Partenaire particulier'),
    m(F, 1, 'yTzyJ7kDLL4', 0, 1988, 'Début de Soirée – Nuit de folie', 'Images – Les Démons de minuit', 'Patrick Sébastien – Les Sardines', 'Émile et Images – Jusqu\'au bout de la nuit'),
    m(F, 3, 'r-951A8fuoU', 0, 1989, 'Patrick Bruel – Casser la voix', 'Patrick Bruel – Place des grands hommes', 'Jean-Jacques Goldman – Là-bas', 'Pascal Obispo – Lucie'),

    // ================= MUSIQUE — années 90 =================
    m(I, 2, 'xwtdhWltSIg', 0, 1991, 'R.E.M. – Losing My Religion', 'R.E.M. – Everybody Hurts', 'The Cranberries – Linger', 'Radiohead – Creep'),
    m(I, 1, 'HEXWRTEbj1I', 0, 1993, 'Haddaway – What Is Love', 'Dr. Alban – It\'s My Life', '2 Unlimited – No Limit', 'Corona – The Rhythm of the Night'),
    m(I, 2, '6Ejga4kJUts', 0, 1994, 'The Cranberries – Zombie', 'The Cranberries – Linger', 'Alanis Morissette – Ironic', 'No Doubt – Don\'t Speak'),
    m(I, 2, '7DXlY8LhWnI', 0, 1995, 'Coolio – Gangsta\'s Paradise', '2Pac – California Love', 'Dr. Dre – Still D.R.E.', 'The Notorious B.I.G. – Juicy'),
    m(I, 1, 'gJLIiF15wjQ', 0, 1996, 'Spice Girls – Wannabe', 'Spice Girls – Spice Up Your Life', 'All Saints – Never Ever', 'Backstreet Boys – Everybody'),
    m(I, 3, 'TR3Vdo5etCQ', 0, 1996, 'No Doubt – Don\'t Speak', 'Alanis Morissette – Ironic', 'The Cardigans – Lovefool', 'Natalie Imbruglia – Torn'),
    m(I, 1, 'ZyhrYis509A', 0, 1997, 'Aqua – Barbie Girl', 'Aqua – Doctor Jones', 'Vengaboys – Boom, Boom, Boom, Boom!!', 'Eiffel 65 – Blue (Da Ba Dee)'),
    m(I, 1, 'kyzIQKuSqBs', 0, 1998, 'Eiffel 65 – Blue (Da Ba Dee)', 'Aqua – Barbie Girl', 'Vengaboys – We Like to Party!', 'Alice Deejay – Better Off Alone'),
    m(I, 1, '4fndeDfaWCg', 0, 1999, 'Backstreet Boys – I Want It That Way', 'NSYNC – Bye Bye Bye', 'Westlife – Swear It Again', 'Boyzone – No Matter What'),
    m(I, 1, 'CN5hQOI__10', 0, 1999, 'Ricky Martin – Livin\' la Vida Loca', 'Ricky Martin – María', 'Enrique Iglesias – Bailamos', 'Lou Bega – Mambo No. 5'),
    m(I, 2, 'EK_LN3XEcnw', 0, 1999, 'Lou Bega – Mambo No. 5', 'Ricky Martin – Livin\' la Vida Loca', 'Las Ketchup – Aserejé', 'Los del Río – Macarena'),

    m(F, 2, 'MNYsmMDZfiA', 0, 1990, 'MC Solaar – Bouge de là', 'MC Solaar – Caroline', 'IAM – Je danse le Mia', 'Alliance Ethnik – Respect'),
    m(F, 2, 'lzGmpqN9zZc', 0, 1991, 'Mylène Farmer – Désenchantée', 'Mylène Farmer – Libertine', 'Axelle Red – Sensualité', 'Vanessa Paradis – Joe le taxi'),
    m(F, 3, 'iXKkxZ7U-lo', 0, 1993, 'Axelle Red – Sensualité', 'Axelle Red – Parce que c\'est toi', 'Patricia Kaas – Il me dit que je suis belle', 'Liane Foly – Au fur et à mesure'),
    m(F, 2, '7ceNf9qJjgc', 10, 1994, 'IAM – Je danse le Mia', 'IAM – Petit Frère', 'MC Solaar – Caroline', 'Suprême NTM – Ma Benz'),
    m(F, 3, 'eg8T1SrFQDQ', 0, 1995, 'Alliance Ethnik – Simple et funky', 'MC Solaar – Nouveau Western', 'IAM – Petit Frère', 'Manau – Mais qui est la belette ?'),
    m(F, 2, 'ncoZqdk2uO8', 0, 1996, 'Pascal Obispo – Lucie', 'Pascal Obispo – Fan', 'Patrick Bruel – Qui a le droit', 'Florent Pagny – Savoir aimer'),
    m(F, 1, 'gzlHucbD76U', 0, 1996, 'Khaled – Aïcha', 'Khaled – Didi', 'Faudel – Tellement je t\'aime', 'Rachid Taha – Ya Rayah'),
    m(F, 1, '4y4D-evzDTo', 10, 1998, 'Zebda – Tomber la chemise', 'Manau – La Tribu de Dana', 'Tryo – L\'Hymne de nos campagnes', 'Louise Attaque – J\'t\'emmène au vent'),
    m(F, 1, '80hMEKlLVgQ', 0, 1998, 'Manau – La Tribu de Dana', 'Zebda – Tomber la chemise', 'Alliance Ethnik – Simple et funky', 'Ophélie Winter – Dieu m\'a donné la foi'),
    m(F, 3, 't82VZncQ8e8', 0, 1998, 'Lââm – Chanter pour ceux qui sont loin de chez eux', 'Hélène Ségara – Il y a trop de gens qui t\'aiment', 'Larusso – Tu m\'oublieras', 'Native – Si tu pars', '1998. Reprise d\'une chanson de Michel Berger (1985).'),

    // ================= MUSIQUE — années 2000 =================
    m(I, 2, 'c18441Eh_WE', 0, 2001, 'Kylie Minogue – Can\'t Get You Out of My Head', 'Kylie Minogue – Spinning Around', 'Sophie Ellis-Bextor – Murder on the Dancefloor', 'Britney Spears – Toxic'),
    m(I, 3, 'PFW2uSCZ0uE', 0, 2002, 'Coldplay – Clocks', 'Coldplay – The Scientist', 'Keane – Somewhere Only We Know', 'Muse – Time Is Running Out'),
    m(I, 1, 'ViwtNLUqkMY', 0, 2003, 'Beyoncé – Crazy in Love', 'Beyoncé – Baby Boy', 'Destiny\'s Child – Say My Name', 'Rihanna – Pon de Replay'),
    m(I, 2, 'PWgvGjAhvIw', 45, 2003, 'OutKast – Hey Ya!', 'Gnarls Barkley – Crazy', 'The Black Eyed Peas – Shut Up', 'Nelly – Hot in Herre'),
    m(I, 1, '0J2QdDbelmY', 0, 2003, 'The White Stripes – Seven Nation Army', 'The Killers – Mr. Brightside', 'Franz Ferdinand – Take Me Out', 'Arctic Monkeys – I Bet You Look Good on the Dancefloor', '2003. Son riff est chanté dans tous les stades.'),
    m(I, 2, 'oofSnsGkops', 0, 2005, 'James Blunt – You\'re Beautiful', 'James Morrison – You Give Me Something', 'Daniel Powter – Bad Day', 'Mika – Grace Kelly'),
    m(I, 1, 'DUT5rEU6pqM', 0, 2006, 'Shakira – Hips Don\'t Lie', 'Shakira – Whenever, Wherever', 'Jennifer Lopez – On the Floor', 'Nelly Furtado – Maneater'),
    m(I, 2, '-N4jf6rtyuw', 0, 2006, 'Gnarls Barkley – Crazy', 'OutKast – Hey Ya!', 'Amy Winehouse – Rehab', 'Mika – Grace Kelly'),
    m(I, 2, 'RVmG_d3HKBA', 0, 2006, 'Mika – Relax, Take It Easy', 'Mika – Grace Kelly', 'James Blunt – 1973', 'Scissor Sisters – I Don\'t Feel Like Dancin\''),
    m(I, 2, '2Abk1jAONjw', 0, 2008, 'Lady Gaga – Just Dance', 'Lady Gaga – Poker Face', 'Katy Perry – Hot n Cold', 'Kesha – Tik Tok'),
    m(I, 1, 'uSD4vsh1zDA', 10, 2009, 'The Black Eyed Peas – I Gotta Feeling', 'The Black Eyed Peas – Where Is the Love?', 'Flo Rida – Right Round', 'Taio Cruz – Dynamite'),

    m(F, 2, 'Yg4yWdeW8C4', 0, 2003, 'Corneille – Parce qu\'on vient de loin', 'Corneille – Seul au monde', 'Tété – À la faveur de l\'automne', 'Calogero – En apesanteur'),
    m(F, 1, 'QyAUONxHmkE', 0, 2003, 'Tragédie – Hey Oh', 'Tragédie – Sexy pour moi', 'Magic System – Premier Gaou', 'K-Maro – Femme like U'),
    m(F, 2, 'CLuOd8xMRRo', 0, 2003, 'Kyo – Le Chemin', 'Kyo – Dernière danse', 'Superbus – Butterfly', 'Indochine – J\'ai demandé à la lune'),
    m(F, 2, 'dGBQUcQZmYQ', 0, 2004, 'Sinsemilia – Tout le bonheur du monde', 'Tryo – L\'Hymne de nos campagnes', 'Yannick Noah – Simon Papa Tara', 'Pierpoljak – Je sais pas jouer'),
    m(F, 2, 'D38EUIll1pM', 0, 2004, 'Amel Bent – Ma philosophie', 'Amel Bent – Nouveau Français', 'Jenifer – Au soleil', 'Chimène Badi – Entre nous'),
    m(F, 3, 'uduL7z8BkOs', 0, 2005, 'Olivia Ruiz – J\'traîne des pieds', 'Olivia Ruiz – La Femme chocolat', 'Zazie – Rue de la paix', 'Bénabar – L\'Effet papillon'),
    m(F, 3, '3X-KbPmOx8s', 0, 2005, 'Bénabar – Le Dîner', 'Bénabar – L\'Effet papillon', 'Vincent Delerm – Fanny Ardant et moi', 'Renan Luce – Les Voleurs de swing'),
    m(F, 2, 'OC2R5fvJsxo', 10, 2006, 'Diam\'s – La Boulette', 'Diam\'s – Jeune demoiselle', 'Sinik – Je réalise', 'Kery James – Banlieusards'),
    m(F, 2, 'CQPNj38WscM', 0, 2006, 'Superbus – Butterfly', 'Superbus – Lola', 'Kyo – Le Chemin', 'Luke – La Tête en arrière'),
    m(F, 1, 'NeRLnsPNSg0', 0, 2007, 'Christophe Maé – On s\'attache', 'Christophe Maé – Belle demoiselle', 'Grégoire – Toi + Moi', 'Yannick Noah – Aux arbres citoyens'),
    m(F, 1, '1B083_AiXTU', 0, 2008, 'Grégoire – Toi + Moi', 'Christophe Maé – Belle demoiselle', 'Emmanuel Moire – Le Sourire', 'Yannick Noah – Métisse'),

    // ================= MUSIQUE — années 2010 =================
    m(I, 1, 'LjhCEhWiKXk', 0, 2010, 'Bruno Mars – Just the Way You Are', 'Bruno Mars – Grenade', 'Jason Derulo – Whatcha Say', 'Ne-Yo – So Sick'),
    m(I, 1, 'suRsxpoAc5w', 0, 2011, 'Maroon 5 – Moves Like Jagger', 'Maroon 5 – Payphone', 'Bruno Mars – Locked Out of Heaven', 'One Direction – What Makes You Beautiful'),
    m(I, 1, 'zIh5AHxh-Ok', 0, 2011, 'LMFAO – Party Rock Anthem', 'LMFAO – Sexy and I Know It', 'Pitbull – Give Me Everything', 'Far East Movement – Like a G6'),
    m(I, 1, 'hLQl3WQQoQ0', 0, 2011, 'Adele – Someone Like You', 'Adele – Set Fire to the Rain', 'Birdy – Skinny Love', 'Lana Del Rey – Video Games'),
    m(I, 2, 'VG3JsmOmDqw', 0, 2012, 'Macklemore & Ryan Lewis – Can\'t Hold Us', 'Macklemore & Ryan Lewis – Thrift Shop', 'Imagine Dragons – Radioactive', 'Fun. – We Are Young'),
    m(I, 2, '2vjPBrBU-TM', 0, 2014, 'Sia – Chandelier', 'Sia – Cheap Thrills', 'Rihanna – Diamonds', 'Lorde – Royals'),
    m(I, 2, 'm-M1AtrxztU', 0, 2014, 'Clean Bandit – Rather Be', 'Clean Bandit – Rockabye', 'Disclosure – Latch', 'Jess Glynne – Hold My Hand'),
    m(I, 2, 'jGflUbPQfW8', 0, 2014, 'OMI – Cheerleader', 'Kygo – Firestone', 'Lost Frequencies – Are You With Me', 'Robin Schulz – Prayer in C'),
    m(I, 2, 'YqeW9_5kURI', 0, 2015, 'Major Lazer & DJ Snake – Lean On', 'DJ Snake – Turn Down for What', 'Kygo – Stole the Show', 'Calvin Harris – This Is What You Came For'),
    m(I, 1, 'ru0K8uYEZWw', 0, 2016, 'Justin Timberlake – Can\'t Stop the Feeling!', 'Justin Timberlake – SexyBack', 'Pharrell Williams – Freedom', 'Bruno Mars – That\'s What I Like'),

    m(F, 1, 'rMltoD1jCGI', 20, 2013, 'Maître Gims – Bella', 'Maître Gims – J\'me tire', 'Sexion d\'Assaut – Désolé', 'Black M – Sur ma route'),
    m(F, 1, 'U-Z_bZS8t3M', 10, 2014, 'Black M – Sur ma route', 'Black M – Je garde le sourire', 'Soprano – Cosmo', 'Maître Gims – Bella'),
    m(F, 2, 'WDfxsnyOkeg', 0, 2014, 'Soprano – Cosmo', 'Soprano – Clown', 'Black M – Sur ma route', 'Kendji Girac – Color Gitano'),
    m(F, 2, 'nBI0bDH8W28', 0, 2015, 'Vianney – Pas là', 'Vianney – Je m\'en vais', 'Kendji Girac – Andalouse', 'Louane – Avenir'),
    m(F, 2, 'qWpBduQKTMY', 0, 2016, 'Jul – On m\'appelle l\'ovni', 'Jul – Tchikita', 'Naps – La kiffance', 'SCH – Champs-Élysées'),
    m(F, 2, '8AF-Sm8d8yk', 0, 2017, 'Bigflo & Oli – Dommage', 'Bigflo & Oli – Plus tard', 'Orelsan – Basique', 'Vianney – Je m\'en vais'),
    m(F, 2, '85m-Qgo9_nE', 0, 2018, 'Clara Luciani – La Grenade', 'Clara Luciani – Les Fleurs', 'Angèle – Balance ton quoi', 'Juliette Armanet – L\'Amour en solitaire'),
    m(F, 2, 'Fy1xQSiLx8U', 0, 2018, 'Angèle & Roméo Elvis – Tout oublier', 'Angèle – La Loi de Murphy', 'Clara Luciani – La Grenade', 'Eddy de Pretto – Kid'),
    m(F, 1, '_bPa-VG0AWo', 0, 2019, 'Aya Nakamura – Pookie', 'Aya Nakamura – Copines', 'Dadju – Reine', 'Wejdene – Anissa'),
    m(F, 2, 'tVKaN_H35xs', 0, 2019, 'Dadju – Reine', 'Dadju – Jaloux', 'Tayc – N\'y pense plus', 'Aya Nakamura – Pookie'),

    // ================= MUSIQUE — années 2020 =================
    m(I, 2, 'mRD0-GxqHVo', 0, 2020, 'Glass Animals – Heat Waves', 'The Kid LAROI & Justin Bieber – Stay', 'Harry Styles – As It Was', 'Tame Impala – The Less I Know the Better'),
    m(I, 2, 'ZmDBbnmKpqQ', 0, 2021, 'Olivia Rodrigo – drivers license', 'Olivia Rodrigo – good 4 u', 'Billie Eilish – Happier Than Ever', 'Taylor Swift – cardigan'),
    m(I, 1, 'H5v3kku4y6Q', 0, 2022, 'Harry Styles – As It Was', 'Harry Styles – Watermelon Sugar', 'The Weeknd – Blinding Lights', 'Glass Animals – Heat Waves'),
    m(I, 1, 'G7KNmW9a75Y', 0, 2023, 'Miley Cyrus – Flowers', 'Miley Cyrus – Wrecking Ball', 'Dua Lipa – Houdini', 'Taylor Swift – Anti-Hero'),

    m(F, 2, 'P3QS83ubhHE', 0, 2021, 'Stromae – Santé', 'Stromae – L\'Enfer', 'Orelsan – La Quête', 'Pomme – Very Bad'),
    m(F, 2, 'a79iLjV-HKw', 0, 2021, 'Angèle – Bruxelles je t\'aime', 'Angèle – Balance ton quoi', 'Clara Luciani – Le Reste', 'Pomme – Anxiété'),
    m(F, 3, 'kTaOHpWz3og', 0, 2021, 'Barbara Pravi – Voilà', 'Amir – J\'ai cherché', 'Slimane – Mon amour', 'Pomme – Les Oiseaux', '2021 : 2e place à l\'Eurovision pour la France.'),
    m(F, 3, 'pqo59FkF_5g', 0, 2023, 'Zaho de Sagazan – La Symphonie des éclairs', 'Zaho de Sagazan – Aspiration', 'Clara Luciani – Respire encore', 'Pierre de Maere – Un jour je marierai un ange'),
    m(F, 2, '5RM8GCD6xQM', 0, 2024, 'Santa – Popcorn salé', 'Santa – Recommence-moi', 'Pierre Garnier – Ceux qu\'on était', 'Zaho de Sagazan – La Symphonie des éclairs'),
    m(F, 2, 'xhG45EjK14I', 0, 2024, 'Pierre Garnier – Ceux qu\'on était', 'Pierre Garnier – Nous on sait', 'Santa – Popcorn salé', 'Slimane – Mon amour'),

    // ================= CINÉMA — musiques de films =================
    f('Musiques de films', 4, 'LKwX0Z2EUow', 0, 1964, FILM, 'Les Parapluies de Cherbourg', 'Les Demoiselles de Rochefort', 'Peau d\'âne', 'Un homme et une femme', 'Michel Legrand (1964). Palme d\'or à Cannes.', 'Les Demoiselles de Rochefort sont aussi de Legrand : piège.'),
    f('Musiques de films', 1, 'xJbtQUvJb3k', 0, 1964, FILM, 'Mary Poppins', 'Le Livre de la jungle', 'Les Aristochats', 'Chitty Chitty Bang Bang', '« Supercalifragilisticexpidélilicieux » (1964).'),
    f('Musiques de films', 4, 'M4yo58nTvhU', 0, 1966, FILM, 'Un homme et une femme', 'Les Parapluies de Cherbourg', 'Jules et Jim', 'Love Story', 'Francis Lai (1966) : le célèbre « chabadabada ».'),
    f('Musiques de films', 1, 'peR2EDHpd4w', 20, 1967, FILM, 'Le Livre de la jungle', 'Le Roi lion', 'Robin des Bois', 'Les Aristochats', '« Il en faut peu pour être heureux » (1967).'),
    f('Musiques de films', 3, 'wWtqkz6SH1Y', 0, 1968, FILM, 'Il était une fois dans l\'Ouest', 'Le Bon, la Brute et le Truand', 'Pour une poignée de dollars', 'Mon nom est Personne', 'L\'homme à l\'harmonica, Ennio Morricone (1968).'),
    f('Musiques de films', 4, '53Nh3XxBiWg', 0, 1970, FILM, 'Love Story', 'Un homme et une femme', 'Autant en emporte le vent', 'Sur la route de Madison', 'Francis Lai (1970), Oscar de la meilleure musique.'),
    f('Musiques de films', 4, 'IMizGzihm6U', 0, 1972, FILM, 'Le Grand Blond avec une chaussure noire', 'Les Aventures de Rabbi Jacob', 'La Boum', 'Le Dîner de cons', 'Vladimir Cosma, avec la flûte de pan de Gheorghe Zamfir (1972).'),
    f('Musiques de films', 2, '5zq0_x77aAE', 0, 1980, FILM, 'La Boum', 'La Boum 2', 'L\'Étudiante', 'Diabolo menthe', '« Reality », chanté par Richard Sanderson (1980).'),
    f('Musiques de films', 3, '8a-HfNE3EIo', 0, 1981, FILM, 'Les Chariots de feu', 'Rocky', 'Blade Runner', 'Gandhi', 'Vangelis (1981). Blade Runner est aussi de Vangelis !'),
    f('Musiques de films', 2, '3KFvoDDs0XM', 0, 1990, FILM, 'Pretty Woman', 'Coup de foudre à Notting Hill', 'Dirty Dancing', 'Ghost', '« Oh, Pretty Woman » de Roy Orbison, reprise dans le film de 1990.'),
    f('Musiques de films', 2, 'Zv8czIoAw5w', 0, 1990, FILM, 'Ghost', 'Pretty Woman', 'Titanic', 'Bodyguard', '« Unchained Melody » des Righteous Brothers (film de 1990).'),
    f('Musiques de films', 1, 'g6GnyHc9qNs', 0, 1992, FILM, 'Aladdin', 'La Belle et la Bête', 'Pocahontas', 'Hercule', '« Ce rêve bleu » (1992).'),
    f('Musiques de films', 2, 'lDlU08RU7Tk', 0, 1993, FILM, 'Jurassic Park', 'King Kong', 'Godzilla', 'Indiana Jones', 'John Williams (1993).'),
    f('Musiques de films', 3, 'JlDBqvc7Mw0', 0, 1999, FILM, 'Matrix', 'Blade', 'Fight Club', 'Mission : Impossible', '« Clubbed to Death » de Rob Dougan (1999).'),
    f('Musiques de films', 3, '3CamXKi002Q', 0, 2003, FILM, 'Kill Bill', 'Pulp Fiction', 'Django Unchained', 'Sin City', '« Twisted Nerve », sifflée par Elle Driver (2003).'),
    f('Musiques de films', 3, 'XNCQZ0wxphY', 0, 2012, FILM, 'Avengers', 'Iron Man', 'Captain America', 'Les Gardiens de la Galaxie', 'Alan Silvestri (2012).'),
    f('Musiques de films', 4, 'Wk7RrtEGDyo', 0, 2016, FILM, 'La La Land', 'Whiplash', 'The Greatest Showman', 'Chantons sous la pluie', '« Mia & Sebastian\'s Theme », Justin Hurwitz (2016).'),
    f('Musiques de films', 2, '7G93QfoOAkk', 0, 2017, FILM, 'Coco', 'Encanto', 'Vaiana', 'Soul', '« Ne m\'oublie pas » (2017).'),
    f('Musiques de films', 3, 'ApXoWvfEYVU', 0, 2018, FILM, 'Spider-Man : New Generation', 'Black Panther', 'Venom', 'Les Indestructibles 2', '« Sunflower » de Post Malone et Swae Lee (2018).'),
    f('Musiques de films', 2, 'gIOyB9ZXn8s', 0, 2019, FILM, 'La Reine des neiges 2', 'Vaiana', 'Raiponce', 'Encanto', '« Into the Unknown » (« Dans un autre monde »), 2019.'),
    f('Musiques de films', 5, 'BdtiYwSP9ko', 0, 2021, FILM, 'Dune', 'Interstellar', 'Blade Runner 2049', 'Oppenheimer', 'Hans Zimmer (2021).'),
    f('Musiques de films', 3, 'O2CIAKVTOrc', 10, 2022, FILM, 'Top Gun : Maverick', 'A Star Is Born', 'Mission : Impossible', 'Mourir peut attendre', '« Hold My Hand » de Lady Gaga (2022).'),
    f('Musiques de films', 2, 'hCLkVrp_4CE', 0, 2023, FILM, 'Barbie', 'Wonka', 'Mean Girls', 'Wicked', '« Dance the Night » de Dua Lipa (2023).'),
    f('Musiques de films', 5, '4JZ-o3iAJv4', 0, 2023, FILM, 'Oppenheimer', 'Interstellar', 'Dune', 'Tenet', 'Ludwig Göransson, Oscar de la meilleure musique (2024).'),

    // ================= CINÉMA — répliques cultes (VF) =================
    f('Répliques', 2, 'HmI6co3ensE', 0, 1963, REPLIQUE, 'Les Tontons flingueurs', 'Le cave se rebiffe', 'Un singe en hiver', 'Mélodie en sous-sol', '« Les cons, ça ose tout… » (dialogues de Michel Audiard).'),
    f('Répliques', 4, 'ncf--ybwDbo', 0, 1965, REPLIQUE, 'Le Corniaud', 'La Grande Vadrouille', 'Le Gendarme de Saint-Tropez', 'Fantômas', '« Elle va marcher beaucoup moins bien, forcément ! » (Bourvil).'),
    f('Répliques', 3, '3zUrpCZ261Q', 0, 1966, REPLIQUE, 'La Grande Vadrouille', 'Le Corniaud', 'Les Aventures de Rabbi Jacob', 'La Folie des grandeurs', '« Il n\'y a pas d\'hélice, hélas ! »'),
    f('Répliques', 3, '2nnyYMqMai0', 0, 1972, REPLIQUE, 'Le Parrain', 'Les Affranchis', 'Scarface', 'Il était une fois en Amérique', '« Je vais lui faire une offre qu\'il ne pourra pas refuser. »', 'Extrait d\'1 min 30 : ajuster le début si la réplique tombe après.'),
    f('Répliques', 2, 'm1vL8iTNJmg', 0, 1973, REPLIQUE, 'Les Aventures de Rabbi Jacob', 'La Grande Vadrouille', 'Le Corniaud', 'L\'Aile ou la Cuisse', '« Salomon, vous êtes juif ? » (Louis de Funès).', 'Ajuster le début si besoin.'),
    f('Répliques', 4, 'r6Y7HXfvRa0', 0, 1975, REPLIQUE, 'Les Dents de la mer', 'Orca', 'Abyss', 'Moby Dick', '« Il nous faudrait un plus gros bateau. »'),
    f('Répliques', 3, '6KZo-xKxuLY', 0, 1979, REPLIQUE, 'Les Bronzés font du ski', 'Les Bronzés', 'Le Père Noël est une ordure', 'Viens chez moi, j\'habite chez une copine', '« Sur un malentendu, ça peut marcher. » (Jean-Claude Dusse).', 'Piège : « Les Bronzés » tout court est le premier film (1978).'),
    f('Répliques', 2, 'BX6zSOLm9-Q', 0, 1982, REPLIQUE, 'Le Père Noël est une ordure', 'Les Bronzés', 'Papy fait de la résistance', 'Le Dîner de cons', '« C\'est cela, oui… » (Thérèse).'),
    f('Répliques', 2, 'I-9dthiJw-Q', 0, 1984, REPLIQUE, 'Terminator', 'RoboCop', 'Predator', 'Total Recall', '« I\'ll be back. » (Arnold Schwarzenegger).'),
    f('Répliques', 1, 'L48rDuvgYKk', 0, 1993, REPLIQUE, 'Les Visiteurs', 'La Vérité si je mens !', 'Le Père Noël est une ordure', 'Les Bronzés', '« Okayyy ! » (Jacquouille la Fripouille).'),
    f('Répliques', 1, 'SmxQ_HjeyP8', 0, 1994, REPLIQUE, 'Forrest Gump', 'Rain Man', 'Big Fish', 'Le Terminal', '« La vie, c\'est comme une boîte de chocolats… »'),
    f('Répliques', 3, 'AyKookhlYeA', 0, 1995, REPLIQUE, 'La Haine', 'Taxi', 'Les Misérables', 'Banlieue 13', '« Jusqu\'ici tout va bien… » (Mathieu Kassovitz, 1995).'),
    f('Répliques', 1, 'hUxRkuL_LMU', 0, 1995, REPLIQUE, 'Toy Story', 'Le Monde de Nemo', 'Monstres & Cie', 'Cars', '« Vers l\'infini et au-delà ! » (Buzz l\'Éclair).'),
    f('Répliques', 1, 'LEoGqNrR7-E', 0, 1998, REPLIQUE, 'Le Dîner de cons', 'Les Visiteurs', 'La Chèvre', 'Le Placard', '« Il s\'appelle Juste Leblanc. »'),
    f('Répliques', 2, 'LtJ51d1rTbA', 0, 2001, REPLIQUE, 'Le Seigneur des anneaux : La Communauté de l\'anneau', 'Harry Potter à l\'école des sorciers', 'Le Hobbit', 'Le Monde de Narnia', '« Vous ne passerez pas ! » (Gandalf).'),
    f('Répliques', 1, 'TEVzxycBBUU', 0, 2002, REPLIQUE, 'Astérix et Obélix : Mission Cléopâtre', 'Astérix aux Jeux olympiques', 'Kaamelott : Premier Volet', 'OSS 117 : Le Caire, nid d\'espions', 'Le monologue d\'Otis, le scribe (Édouard Baer).'),
    f('Répliques', 1, 'j6jsoQ1i3Vs', 0, 2006, REPLIQUE, 'OSS 117 : Le Caire, nid d\'espions', 'Brice de Nice', 'Les Visiteurs', 'Astérix et Obélix : Mission Cléopâtre', '« Comment est votre blanquette ? » (Jean Dujardin).'),
    f('Répliques', 1, 'fnhDgAvy-M8', 0, 2008, REPLIQUE, 'Bienvenue chez les Ch\'tis', 'Rien à déclarer', 'Les Tuche', 'Camping', 'Dany Boon et Kad Merad (2008).'),
    f('Répliques', 2, '_w2IDfX9RVc', 0, 1980, REPLIQUE, 'Star Wars : L\'Empire contre-attaque', 'Star Wars : Un nouvel espoir', 'Star Trek', 'Dune', '« Non, je suis ton père. » (Dark Vador).', 'Extrait d\'1 min 45 : ajuster le début si besoin.'),
    f('Répliques', 1, 'SPwathgH5JY', 0, 1997, REPLIQUE, 'Titanic', 'Pearl Harbor', 'Le Loup de Wall Street', 'Arrête-moi si tu peux', '« Je suis le roi du monde ! » (Leonardo DiCaprio).'),
    f('Répliques', 1, 'ByzB0rWuLTQ', 0, 1985, REPLIQUE, 'Retour vers le futur', 'Les Goonies', 'Gremlins', 'Chérie, j\'ai rétréci les gosses', '« Nom de Zeus ! » (Doc Brown).'),
    f('Répliques', 3, 'PghW3eAFWP8', 0, 1983, REPLIQUE, 'Scarface', 'Le Parrain', 'Les Affranchis', 'Heat', '« Dites bonne nuit au mauvais garçon ! » (Tony Montana).'),
    f('Répliques', 3, 'snBWxmZn3iA', 0, 1993, REPLIQUE, 'Jurassic Park', 'Twister', 'King Kong', 'Godzilla', '« La vie trouve toujours un chemin. » (Ian Malcolm).'),
    f('Répliques', 1, '2YUfQ3c0P1g', 0, 2002, REPLIQUE, 'Le Seigneur des anneaux', 'Harry Potter', 'Le Monde de Narnia', 'Willow', '« Mon précieux ! » (Gollum).'),
    f('Répliques', 1, '_evDnoeJgMY', 0, 2011, REPLIQUE, 'Intouchables', 'Bienvenue chez les Ch\'tis', 'Qu\'est-ce qu\'on a fait au Bon Dieu ?', 'Le Sens de la fête', '« Pas de bras, pas de chocolat ! » (Omar Sy).', 'Extrait de 2 min : ajuster le début si besoin.'),
    f('Répliques', 2, '5onIvUtAbnc', 0, 2005, REPLIQUE, 'Brice de Nice', 'OSS 117 : Le Caire, nid d\'espions', 'Les Visiteurs', 'Taxi', '« Cassé ! » (Jean Dujardin).'),
    f('Répliques', 2, 'mbruLMSeq_A', 0, 1994, REPLIQUE, 'La Cité de la peur', 'Le Dîner de cons', 'La Classe américaine', 'Les Visiteurs', 'La scène d\'Odile Deray (Les Nuls, 1994).'),
    f('Répliques', 3, 'Cbr5EHTfz9E', 0, 1981, REPLIQUE, 'La Chèvre', 'Les Compères', 'Les Fugitifs', 'Le Grand Blond avec une chaussure noire', 'Pierre Richard et Gérard Depardieu (1981).', 'Les Compères et Les Fugitifs réunissent le même duo : piège.'),
    f('Répliques', 2, 'O_27-LhybxI', 0, 2010, REPLIQUE, 'Camping 2', 'Les Tuche', 'Les Bronzés', 'Bienvenue chez les Ch\'tis', '« Alors, on attend pas Patrick ? » (Franck Dubosc).'),
    f('Répliques', 2, 'DDJdkJ6-RQg', 0, 2006, REPLIQUE, 'OSS 117 : Le Caire, nid d\'espions', 'Brice de Nice', 'The Artist', 'Le Grand Blond avec une chaussure noire', '« J\'aime me beurrer la biscotte. »'),
    f('Répliques', 2, 'nXfyqljyy4s', 0, 1993, REPLIQUE, 'Les Visiteurs', 'La Vérité si je mens !', 'Le Dîner de cons', 'Les Bronzés', '« Mais qu\'est-ce que c\'est que ce binz ? » (Jacquouille).'),
    f('Répliques', 2, 'bU2a0vmRuWI', 0, 1998, REPLIQUE, 'Le Dîner de cons', 'La Chèvre', 'Le Placard', 'Les Visiteurs', '« Il a une belle tête de vainqueur ! »'),
    f('Répliques', 2, '4c3W0yZ3_E0', 0, 1979, REPLIQUE, 'Les Bronzés font du ski', 'Les Bronzés', 'Camping', 'Le Père Noël est une ordure', 'Le « planté du bâton », la leçon de ski de Popeye (Thierry Lhermitte).'),
    f('Répliques', 3, 'T9hDBtX7t8s', 0, 1963, REPLIQUE, 'Les Tontons flingueurs', 'Le cave se rebiffe', 'Le Pacha', 'Un singe en hiver', '« … éparpillé façon puzzle. » (Michel Audiard).', 'Ajuster le début si besoin.'),
    f('Répliques', 2, 'VFprXdE3YFI', 0, 1991, REPLIQUE, 'Terminator 2 : Le Jugement dernier', 'RoboCop', 'Total Recall', 'Predator', '« Hasta la vista, baby ! »'),
    f('Répliques', 2, 'YjBdJqUT1XY', 0, 2002, REPLIQUE, 'Astérix et Obélix : Mission Cléopâtre', 'Astérix et Obélix contre César', 'Astérix aux Jeux olympiques', 'RRRrrrr!!!', '« Et juste là, un petit géranium… » (Numérobis, Jamel Debbouze).'),
    f('Répliques', 3, 'Z9tB81GAdvM', 0, 1994, REPLIQUE, 'Pulp Fiction', 'Reservoir Dogs', 'Jackie Brown', 'Kill Bill', 'Le passage « Ézéchiel 25:17 » récité par Jules (Samuel L. Jackson).'),
    f('Répliques', 1, 'A2oOTUO7FFk', 0, 2001, REPLIQUE, 'Harry Potter à l\'école des sorciers', 'Le Seigneur des anneaux', 'Les Animaux fantastiques', 'Le Monde de Narnia', '« Tu es un sorcier, Harry. » (Hagrid).'),
    f('Répliques', 2, 'a67sRNtR4dQ', 0, 2003, REPLIQUE, 'Pirates des Caraïbes', 'Le Masque de Zorro', 'Hook', 'Master and Commander', 'Le capitaine Jack Sparrow (Johnny Depp).'),
    f('Répliques', 3, 'w2mNrkvxJ0c', 0, 2013, REPLIQUE, 'Le Loup de Wall Street', 'Arrête-moi si tu peux', 'The Big Short', 'Wall Street', '« Vendez-moi ce stylo. »', 'Extrait d\'1 min 30 : ajuster le début si besoin.'),
    f('Répliques', 2, 'SyCssNHT5VM', 0, 1976, REPLIQUE, 'Rocky', 'Raging Bull', 'Karaté Kid', 'Million Dollar Baby', '« Adrienne ! » (Sylvester Stallone).', 'Le cri est vers la fin de l\'extrait : régler le début vers 60 s si besoin.'),
  ];
}
