/**
 * Banque de questions (8) — Histoire, Géographie, Sciences, Nature & Animaux, Cinéma.
 * q(thème, catégorie, difficulté, type, question, réponse, choix2, choix3, choix4, explication, indices MJ, anecdote MJ)
 * L'explication s'affiche pour tout le monde ; l'anecdote (« Pour animer ») est réservée au maître du jeu.
 */
function banque8_() {
  const H = 'Histoire', G = 'Géographie', S = 'Sciences', N = 'Nature & Animaux', C = 'Cinéma';
  const q = (th, cat, diff, type, texte, rep, c2, c3, c4, expl, ind, anec) =>
    [th, cat, diff, type, texte, rep, c2 || '', c3 || '', c4 || '', expl || '', ind || '', '', '', '', '', anec || ''];
  return [
    // ---------------- HISTOIRE ----------------
    q(H, 'France', 1, 'QCM', 'Quel animal est le symbole de la France depuis l\'Antiquité ?', 'Le coq', 'L\'aigle', 'Le lion', 'L\'ours',
      'En latin, « gallus » veut dire à la fois « coq » et « Gaulois ». Le jeu de mots a fait le reste.', '',
      'Napoléon n\'aimait pas le coq : « Le coq n\'a point de force, il ne peut être l\'image d\'un empire comme la France. » Il lui préférait l\'aigle.'),
    q(H, 'France', 1, 'QCM', 'Quelle fête nationale célèbre-t-on en France le 14 juillet ?', 'La prise de la Bastille et la fête de la Fédération', 'L\'armistice de 1918', 'La victoire de 1945', 'Le sacre de Napoléon',
      'La loi de 1880 ne précise pas l\'année : on célèbre à la fois 1789 (Bastille) et 1790 (fête de la Fédération, symbole d\'unité).', '',
      'Le premier défilé militaire sur les Champs-Élysées date de 1919, pour fêter la victoire. Avant, il avait lieu à Longchamp.'),
    q(H, 'Antiquité', 2, 'QCM', 'Quel volcan a détruit Pompéi en l\'an 79 ?', 'Le Vésuve', 'L\'Etna', 'Le Stromboli', 'Le Santorin',
      'Pompéi et Herculanum ont été ensevelies sous les cendres et les coulées pyroclastiques.', 'Il domine la baie de Naples.',
      'Pline le Jeune a décrit l\'éruption dans deux lettres : c\'est le premier récit détaillé d\'une éruption. Son oncle, Pline l\'Ancien, est mort en voulant secourir les habitants.'),
    q(H, 'Antiquité', 2, 'VF', 'Jules César a été le premier empereur romain.', 'Faux', '', '', '',
      'Faux : il a été dictateur. Le premier empereur est son fils adoptif Octave, devenu Auguste en 27 av. J.-C.', '',
      'Le mot « César » est pourtant devenu synonyme d\'empereur : il a donné « Kaiser » en allemand et « tsar » en russe.'),
    q(H, 'Moyen Âge', 2, 'QCM', 'Quelle épidémie a tué environ un tiers des Européens au milieu du XIVe siècle ?', 'La peste noire', 'Le choléra', 'La variole', 'La grippe espagnole',
      'Arrivée en 1347, elle a fait environ 25 millions de morts en Europe en quelques années.', '',
      'Elle serait arrivée par les ports de la Méditerranée avec les puces des rats. Le mot « quarantaine » vient des 40 jours d\'isolement imposés aux navires à Venise.'),
    q(H, 'XXe siècle', 2, 'QCM', 'Quel appel lance le général de Gaulle depuis Londres en 1940 ?', 'L\'appel du 18 Juin', 'L\'appel du 11 Novembre', 'L\'appel du 6 Juin', 'L\'appel du 8 Mai',
      'Diffusé par la BBC le 18 juin 1940, il appelle à poursuivre le combat.', '',
      'Le discours n\'a pas été enregistré : l\'enregistrement célèbre date du 22 juin. Très peu de Français l\'ont entendu en direct.'),
    q(H, 'XXe siècle', 3, 'ESTIMATION', 'En quelle année le mur de Berlin a-t-il été construit ?', '1961', '', '2', '',
      'Érigé dans la nuit du 12 au 13 août 1961 par la RDA, il est tombé le 9 novembre 1989.', 'Au début des années 60.',
      'Il mesurait 155 km autour de Berlin-Ouest. Environ 140 personnes sont mortes en essayant de le franchir.'),
    q(H, 'Renaissance', 3, 'QCM', 'Quel roi de France a fait venir Léonard de Vinci à Amboise ?', 'François Ier', 'Louis XII', 'Henri II', 'Charles VIII',
      'Léonard a passé ses trois dernières années au Clos Lucé, près du château d\'Amboise, où il est mort en 1519.', 'Le vainqueur de Marignan.',
      'Il est arrivé avec trois tableaux dans ses bagages, dont la Joconde. C\'est ainsi qu\'elle est arrivée dans les collections royales, puis au Louvre.'),
    q(H, 'Monde', 3, 'QCM', 'Quel pays a été le premier à accorder le droit de vote aux femmes, en 1893 ?', 'La Nouvelle-Zélande', 'Le Royaume-Uni', 'La France', 'Les États-Unis',
      'Grâce notamment à la militante Kate Sheppard. La France ne l\'a accordé qu\'en 1944.', 'Un pays d\'Océanie.',
      'Kate Sheppard figure aujourd\'hui sur le billet de 10 dollars néo-zélandais.'),
    q(H, 'Chronologie', 3, 'ORDRE', 'Remettez ces inventions dans l\'ordre chronologique.', 'Imprimerie de Gutenberg | Machine à vapeur de Watt | Téléphone de Bell | Internet (Web)', 'Du plus ancien au plus récent', '', '',
      'Vers 1450, 1769, 1876, 1989.', '',
      'Gutenberg a d\'abord imprimé une Bible : il en reste 49 exemplaires, dont l\'un est à la Bibliothèque nationale de France.'),
    q(H, 'XXe siècle', 4, 'QCM', 'Quelle conférence de février 1945 a réuni Roosevelt, Churchill et Staline ?', 'La conférence de Yalta', 'La conférence de Potsdam', 'La conférence de Munich', 'La conférence de Téhéran',
      'En Crimée, les trois « Grands » y ont préparé l\'après-guerre et le découpage de l\'Europe.', '',
      'De Gaulle n\'avait pas été invité, ce qu\'il n\'a jamais oublié. Roosevelt, déjà très malade, est mort deux mois plus tard.'),
    q(H, 'Napoléon', 4, 'QCM', 'Sur quelle île Napoléon est-il mort en 1821 ?', 'Sainte-Hélène', 'L\'île d\'Elbe', 'La Corse', 'L\'île de Ré',
      'Un îlot britannique perdu dans l\'Atlantique Sud, à près de 2 000 km des côtes africaines.', 'Pas celle de son premier exil.',
      'Ses cendres ont été ramenées en France en 1840 et reposent aux Invalides. La maison où il est mort, à Longwood, appartient à la France.'),
    q(H, 'Monde', 4, 'VF', 'La guerre de Cent Ans opposait la France à l\'Espagne.', 'Faux', '', '', '',
      'Faux : elle opposait les rois de France et d\'Angleterre (1337-1453).', '',
      'Le nom « guerre de Cent Ans » a été inventé par les historiens au XIXe siècle. Les contemporains ne savaient pas qu\'ils vivaient une seule et même guerre.'),
    q(H, 'Antiquité', 5, 'QCM', 'Quelle merveille du monde antique se trouvait à Alexandrie ?', 'Le phare', 'Les jardins suspendus', 'Le colosse', 'Le mausolée',
      'Haut d\'une centaine de mètres, il a guidé les navires pendant plus de 1 500 ans avant d\'être détruit par des séismes.', '',
      'Il était bâti sur l\'île de Pharos, qui a donné le mot « phare » en français. Des archéologues plongeurs en ont retrouvé des blocs dans le port.'),
    q(H, 'France', 5, 'QCM', 'Quel roi de France est mort en 1559 d\'un coup de lance reçu lors d\'un tournoi ?', 'Henri II', 'François Ier', 'Henri III', 'Charles IX',
      'La lance de Montgomery a traversé la visière de son casque. Il est mort après dix jours d\'agonie.', '',
      'Sa femme Catherine de Médicis a porté le deuil jusqu\'à la fin de sa vie et a fait raser le palais des Tournelles où il était mort.'),

    // ---------------- GÉOGRAPHIE ----------------
    q(G, 'Monde', 2, 'QCM', 'Quel est le plus grand désert du monde, en comptant les déserts froids ?', 'L\'Antarctique', 'Le Sahara', 'Le Gobi', 'L\'Arctique',
      'Un désert se définit par le peu de précipitations, pas par la chaleur. L\'Antarctique fait environ 14 millions de km².', 'Il est très froid.',
      'Certaines vallées sèches de l\'Antarctique n\'ont pas reçu de pluie depuis des milliers d\'années.'),
    q(G, 'France', 3, 'QCM', 'Quel est le plus haut sommet des Pyrénées ?', 'L\'Aneto', 'Le Vignemale', 'Le pic du Midi', 'Le Canigou',
      'Il culmine à 3 404 m, côté espagnol.', 'Il est en Espagne.',
      'Le point culminant des Pyrénées françaises est le Vignemale (3 298 m), côté frontière.'),
    q(G, 'Capitales', 2, 'QCM', 'Quelle est la capitale de la Norvège ?', 'Oslo', 'Bergen', 'Stockholm', 'Copenhague',
      'Sur un fjord au sud du pays. Elle s\'est appelée Christiania jusqu\'en 1925.', '',
      'C\'est à Oslo qu\'on remet le prix Nobel de la paix, les autres prix étant remis à Stockholm.'),
    q(G, 'France', 2, 'QCM', 'Quelle île française est surnommée « l\'île de Beauté » ?', 'La Corse', 'La Réunion', 'Belle-Île-en-Mer', 'La Martinique',
      'Son surnom remonte à l\'Antiquité grecque, qui l\'appelait « Kallisté », la plus belle.', '',
      'La Corse est française depuis 1768, un an avant la naissance de Napoléon à Ajaccio.'),
    q(G, 'Monde', 2, 'VF', 'L\'Australie est à la fois un pays et un continent.', 'Vrai', '', '', '',
      'Vrai : on parle souvent de l\'Océanie ou de l\'Australie-continent, dont l\'Australie est la plus grande partie.', '',
      'Elle est aussi grande que les États-Unis continentaux mais compte environ 27 millions d\'habitants, surtout sur les côtes.'),
    q(G, 'Monde', 2, 'QCM', 'Dans quel pays se trouve la ville de Tombouctou ?', 'Le Mali', 'Le Niger', 'Le Maroc', 'La Mauritanie',
      'Aux portes du Sahara, près du fleuve Niger. Ses mosquées et manuscrits sont classés à l\'Unesco.', '',
      '« Aller à Tombouctou » voulait dire aller au bout du monde. Le Français René Caillié a été le premier Européen à en revenir vivant, en 1828.'),
    q(G, 'Monde', 3, 'QCM', 'Quelle mer est si salée qu\'on y flotte sans effort ?', 'La mer Morte', 'La mer Rouge', 'La mer Noire', 'La mer Caspienne',
      'Environ 10 fois plus salée que la mer Méditerranée, entre Israël, la Jordanie et la Cisjordanie.', '',
      'Elle est le point le plus bas des terres émergées : sa surface est à plus de 430 m sous le niveau de la mer, et elle baisse d\'environ 1 m par an.'),
    q(G, 'Capitales', 3, 'QCM', 'Quelle est la capitale de la Turquie ?', 'Ankara', 'Istanbul', 'Izmir', 'Antalya',
      'Choisie par Mustafa Kemal Atatürk en 1923, lors de la fondation de la République.', 'Ce n\'est pas la plus grande ville.',
      'Istanbul a été capitale pendant environ 1 600 ans, sous les Byzantins puis les Ottomans.'),
    q(G, 'Monde', 3, 'ESTIMATION', 'Combien de pays compte le continent africain ?', '54', 'pays', '2', '',
      '54 États reconnus par l\'ONU, dont le plus récent est le Soudan du Sud (2011).', 'Plus de 50.',
      'Le plus grand est l\'Algérie, le plus peuplé le Nigeria, le plus petit les Seychelles.'),
    q(G, 'France', 3, 'QCM', 'Quel fleuve se jette dans la Méditerranée en formant la Camargue ?', 'Le Rhône', 'La Garonne', 'La Durance', 'L\'Hérault',
      'Il se divise en Grand et Petit Rhône, qui enserrent la Camargue.', '',
      'La Camargue est l\'un des rares endroits d\'Europe où les flamants roses nichent. Ses chevaux blancs naissent… bruns ou noirs.'),
    q(G, 'Europe', 3, 'QCM', 'Quel pays européen est entièrement entouré par l\'Italie, avec le Vatican ?', 'Saint-Marin', 'Monaco', 'Andorre', 'Malte',
      'Une des plus anciennes républiques du monde, fondée selon la tradition en 301.', '',
      'Saint-Marin compte environ 34 000 habitants. Il a été invité par Napoléon à s\'agrandir… et a poliment refusé.'),
    q(G, 'Monde', 4, 'QCM', 'Quel pays a la plus longue côte du monde ?', 'Le Canada', 'La Russie', 'L\'Australie', 'L\'Indonésie',
      'Plus de 200 000 km de côtes, grâce à ses milliers d\'îles arctiques.', '',
      'Si on la parcourait à raison de 20 km par jour, il faudrait plus de 27 ans pour en faire le tour.'),
    q(G, 'Monde', 4, 'QCM', 'Quel fleuve traverse Bagdad ?', 'Le Tigre', 'L\'Euphrate', 'Le Jourdain', 'L\'Indus',
      'Le Tigre et l\'Euphrate délimitent la Mésopotamie, « le pays entre les fleuves ».', '',
      'La Mésopotamie est souvent appelée le berceau de la civilisation : l\'écriture y est apparue vers 3300 av. J.-C.'),
    q(G, 'Europe', 5, 'QCM', 'Quelle est la capitale de la Slovénie ?', 'Ljubljana', 'Bratislava', 'Zagreb', 'Skopje',
      'Petite capitale verte, elle est traversée par la rivière Ljubljanica.', 'Son nom évoque « bien-aimée » en slovène.',
      'Son symbole est le dragon : on le retrouve sur le célèbre « pont des Dragons ».'),
    q(G, 'Monde', 5, 'QCM', 'Quel est le seul pays traversé à la fois par l\'équateur et le tropique du Capricorne ?', 'Le Brésil', 'L\'Indonésie', 'Le Kenya', 'L\'Australie',
      'L\'équateur passe près de l\'embouchure de l\'Amazone, le tropique à São Paulo.', 'Un pays d\'Amérique du Sud.',
      'Le Brésil est aussi le seul pays d\'Amérique du Sud dont la langue officielle est le portugais.'),

    // ---------------- SCIENCES ----------------
    q(S, 'Corps humain', 1, 'QCM', 'Combien de sens l\'être humain possède-t-il traditionnellement ?', '5', '3', '4', '7',
      'La vue, l\'ouïe, l\'odorat, le goût et le toucher.', '',
      'Les scientifiques en comptent en réalité bien plus : l\'équilibre, la douleur, la température, la position du corps (proprioception)…'),
    q(S, 'Espace', 1, 'QCM', 'Comment s\'appelle notre galaxie ?', 'La Voie lactée', 'Andromède', 'La Grande Ourse', 'Orion',
      'Une galaxie spirale contenant entre 100 et 400 milliards d\'étoiles.', '',
      'Les Grecs y voyaient du lait renversé par la déesse Héra, d\'où son nom : « galaxie » vient de « gala », le lait.'),
    q(S, 'Physique', 2, 'VF', 'Un objet lourd tombe plus vite qu\'un objet léger dans le vide.', 'Faux', '', '', '',
      'Faux : dans le vide, tous les objets tombent à la même vitesse. C\'est l\'air qui ralentit la plume.', '',
      'En 1971, sur la Lune, l\'astronaute David Scott a lâché un marteau et une plume en même temps : ils ont touché le sol ensemble.'),
    q(S, 'Chimie', 2, 'QCM', 'Quel est le symbole chimique du sodium ?', 'Na', 'So', 'Sd', 'S',
      'De son nom latin « natrium ». S est le soufre.', '',
      'Le sel de table, c\'est du chlorure de sodium (NaCl) : un métal qui explose dans l\'eau associé à un gaz toxique… et le résultat est comestible !'),
    q(S, 'Corps humain', 2, 'QCM', 'Quel est l\'os le plus long du corps humain ?', 'Le fémur', 'Le tibia', 'L\'humérus', 'La colonne vertébrale',
      'L\'os de la cuisse représente environ un quart de la taille d\'une personne.', '',
      'Il est aussi l\'un des plus solides : il peut supporter plusieurs tonnes en compression.'),
    q(S, 'Espace', 2, 'QCM', 'Comment s\'appelle le robot de la NASA qui explore Mars depuis 2021 avec un petit hélicoptère ?', 'Perseverance', 'Curiosity', 'Spirit', 'Sojourner',
      'Arrivé dans le cratère Jezero en février 2021, avec l\'hélicoptère Ingenuity.', '',
      'Ingenuity a été le premier engin à voler sur une autre planète. Prévu pour 5 vols, il en a fait 72.'),
    q(S, 'Savants', 3, 'QCM', 'Quel savant grec aurait crié « Eurêka ! » dans son bain ?', 'Archimède', 'Pythagore', 'Euclide', 'Aristote',
      'Il venait de comprendre la poussée qui porte son nom : un corps plongé dans l\'eau déplace un volume d\'eau égal au sien.', '',
      'Selon la légende, il est sorti nu dans les rues de Syracuse tant il était content. Il cherchait à savoir si la couronne du roi était en or pur.'),
    q(S, 'Physique', 3, 'QCM', 'Dans quelle unité mesure-t-on la fréquence d\'un son ?', 'Le hertz', 'Le décibel', 'Le watt', 'Le newton',
      'Un hertz, c\'est une vibration par seconde. L\'oreille humaine entend environ de 20 à 20 000 Hz.', 'Le décibel mesure le volume, pas la hauteur.',
      'Le « la » du diapason vibre à 440 Hz. Les chiens entendent jusqu\'à 45 000 Hz, les chauves-souris plus de 100 000.'),
    q(S, 'Biologie', 3, 'VF', 'Les humains et les bananes partagent une partie de leur ADN.', 'Vrai', '', '', '',
      'Vrai : on estime qu\'environ 60 % de nos gènes ont un équivalent chez la banane.', '',
      'Cela ne veut pas dire qu\'on est « à 60 % banane » : beaucoup de gènes de base, qui font fonctionner les cellules, sont communs à tout le vivant.'),
    q(S, 'Espace', 3, 'QCM', 'Quelle est la plus grosse lune du système solaire ?', 'Ganymède', 'Titan', 'La Lune', 'Europe',
      'Ce satellite de Jupiter est plus grand que la planète Mercure.', 'Elle tourne autour de Jupiter.',
      'Galilée l\'a découverte en 1610, avec Io, Europe et Callisto. Ganymède a même son propre champ magnétique.'),
    q(S, 'Chimie', 4, 'QCM', 'Quel gaz rare donne leur couleur rouge-orangé aux enseignes lumineuses « néon » ?', 'Le néon', 'L\'argon', 'L\'hélium', 'Le krypton',
      'Chaque gaz a sa couleur : le néon est rouge-orangé, l\'argon bleuté, l\'hélium rose.', '',
      'La première enseigne au néon a été présentée par le Français Georges Claude au Salon de l\'automobile de Paris en 1910.'),
    q(S, 'Corps humain', 4, 'QCM', 'Combien de litres d\'air respire environ un adulte au repos par jour ?', 'Environ 10 000', 'Environ 500', 'Environ 1 000', 'Environ 100 000',
      'Environ 12 à 15 respirations par minute d\'un demi-litre chacune.', '',
      'Seulement 21 % de cet air est de l\'oxygène, et nous n\'en utilisons qu\'une partie : l\'air expiré en contient encore environ 16 %.'),
    q(S, 'Savants', 4, 'QCM', 'Quel savant a établi le tableau périodique des éléments en 1869 ?', 'Dmitri Mendeleïev', 'Antoine Lavoisier', 'John Dalton', 'Niels Bohr',
      'Il a même laissé des cases vides pour des éléments pas encore découverts, dont il avait prédit les propriétés.', '',
      'Il aurait vu l\'organisation du tableau en rêve. Un élément porte son nom : le mendélévium (101).'),
    q(S, 'Physique', 5, 'ESTIMATION', 'À combien de km/h se propage le son dans l\'air (à 20 °C) ?', '1235', 'km/h', '60', '',
      'Environ 343 m/s, soit un peu plus de 1 200 km/h. C\'est « Mach 1 ».', 'Environ 340 m/s.',
      'Pour savoir à quelle distance est un orage, on compte les secondes entre l\'éclair et le tonnerre et on divise par 3 : on obtient la distance en km.'),
    q(S, 'Biologie', 5, 'QCM', 'Quelle est la plus grande cellule connue du monde vivant ?', 'L\'œuf d\'autruche (le jaune)', 'Le neurone de la girafe', 'L\'ovule humain', 'Le globule rouge',
      'Le jaune d\'un œuf d\'autruche non fécondé est une seule cellule, d\'une dizaine de centimètres.', '',
      'Le neurone le plus long, lui, appartient au calmar géant ou aux grandes baleines : plusieurs mètres de long, mais très fin.'),

    // ---------------- NATURE & ANIMAUX ----------------
    q(N, 'Mammifères', 1, 'QCM', 'Comment s\'appelle le petit du kangourou ?', 'Le joey', 'Le kangourillon', 'Le marsu', 'Le petit-roo',
      'Il naît minuscule (2 cm, moins d\'un gramme) et rampe jusqu\'à la poche de sa mère.', '',
      'Il reste environ 6 mois dans la poche avant d\'en sortir la tête. Le mot « joey » désigne le petit de tous les marsupiaux.'),
    q(N, 'Oiseaux', 1, 'QCM', 'Quel oiseau est le symbole de la sagesse ?', 'La chouette', 'Le corbeau', 'Le paon', 'L\'aigle',
      'Elle accompagnait Athéna, déesse grecque de la sagesse. On la voit sur la pièce grecque d\'1 euro.', '',
      'La chouette et le hibou se distinguent par les aigrettes : le hibou a des « oreilles » en plumes, la chouette non.'),
    q(N, 'Mammifères', 2, 'VF', 'Le lion est le seul félin qui vit en groupe.', 'Vrai', '', '', '',
      'Vrai : les lions vivent en troupes, composées de femelles apparentées, de leurs petits et de quelques mâles.', '',
      'Ce sont surtout les lionnes qui chassent, en équipe. Le mâle défend le territoire… et mange en premier.'),
    q(N, 'Mer', 2, 'QCM', 'Quel animal marin a la réputation de pouvoir « régénérer » un bras perdu ?', 'L\'étoile de mer', 'La méduse', 'L\'oursin', 'Le crabe',
      'Certaines espèces peuvent même reformer un individu entier à partir d\'un bras avec un morceau du disque central.', '',
      'L\'étoile de mer n\'a pas de cerveau ni de sang : de l\'eau de mer circule dans son corps.'),
    q(N, 'Plantes', 2, 'QCM', 'Quelle plante carnivore referme ses feuilles sur les insectes ?', 'La dionée attrape-mouche', 'Le népenthès', 'Le rossolis', 'La sarracénie',
      'Ses poils sensibles déclenchent la fermeture en une fraction de seconde s\'ils sont touchés deux fois.', '',
      'Le double contact évite de se refermer pour une goutte de pluie. Elle pousse naturellement dans une petite région des Carolines, aux États-Unis.'),
    q(N, 'Oiseaux', 2, 'QCM', 'Quel oiseau ne vole pas mais est le plus rapide à la course ?', 'L\'autruche', 'L\'émeu', 'Le nandou', 'Le kiwi',
      'Elle peut courir à environ 70 km/h et tenir 50 km/h sur de longues distances.', '',
      'Un coup de patte d\'autruche peut tuer un lion. Elle n\'a que deux doigts à chaque pied, dont un énorme muni d\'une griffe.'),
    q(N, 'Mammifères', 3, 'QCM', 'Combien de temps dort un koala par jour ?', 'Jusqu\'à 20 heures', 'Environ 8 heures', 'Environ 12 heures', 'Moins de 4 heures',
      'Son alimentation d\'eucalyptus, peu nourrissante et difficile à digérer, l\'oblige à économiser son énergie.', '',
      'Les feuilles d\'eucalyptus sont toxiques pour la plupart des animaux. Les bébés koalas mangent les excréments de leur mère pour acquérir les bonnes bactéries.'),
    q(N, 'Petites bêtes', 3, 'QCM', 'Combien d\'yeux possède la plupart des araignées ?', '8', '2', '4', '6',
      'Souvent huit, disposés sur le devant de la tête. Certaines espèces en ont moins.', 'Autant que de pattes.',
      'Les araignées sauteuses voient très bien et en couleur. D\'autres, qui vivent dans des grottes, n\'ont plus d\'yeux du tout.'),
    q(N, 'Mer', 3, 'VF', 'Les hippocampes mâles portent les bébés.', 'Vrai', '', '', '',
      'Vrai : la femelle dépose ses œufs dans la poche ventrale du mâle, qui « accouche » de centaines de petits.', '',
      'C\'est l\'un des rares cas dans le règne animal où le mâle porte la « grossesse ». Il peut libérer plus de 1 000 petits d\'un coup.'),
    q(N, 'Records', 3, 'QCM', 'Quel animal a le cri le plus puissant du règne animal ?', 'Le cachalot', 'Le lion', 'L\'éléphant', 'Le singe hurleur',
      'Ses clics d\'écholocation peuvent dépasser 230 décibels sous l\'eau.', 'Il vit dans l\'océan.',
      'Sur terre, le singe hurleur s\'entend à près de 5 km. Le cachalot a aussi le plus gros cerveau de tous les animaux (environ 8 kg).'),
    q(N, 'Plantes', 4, 'QCM', 'Quel arbre vit le plus longtemps, avec des individus de près de 5 000 ans ?', 'Le pin Bristlecone', 'Le chêne', 'Le baobab', 'L\'olivier',
      'Dans les montagnes de Californie, un pin baptisé « Mathusalem » a environ 4 800 ans.', '',
      'Son emplacement exact est tenu secret pour le protéger. Il germait à peu près quand les Égyptiens construisaient les premières pyramides.'),
    q(N, 'Mammifères', 4, 'QCM', 'Quel mammifère ne peut pas vomir ?', 'Le rat', 'Le chien', 'Le chat', 'Le cochon',
      'Son œsophage et les muscles de son estomac ne le permettent pas. C\'est pour ça que la mort-aux-rats fonctionne.', '',
      'Les chevaux, les lapins et les cochons d\'Inde non plus ne peuvent pas vomir.'),
    q(N, 'Oiseaux', 4, 'QCM', 'Quel oiseau migrateur fait le plus long voyage, entre l\'Arctique et l\'Antarctique ?', 'La sterne arctique', 'L\'hirondelle', 'La cigogne', 'L\'oie cendrée',
      'Elle parcourt jusqu\'à 70 000 km par an en zigzaguant entre les deux pôles.', '',
      'Elle vit environ 30 ans : au cours de sa vie, elle parcourt l\'équivalent de trois allers-retours Terre-Lune. Elle voit aussi deux étés par an.'),
    q(N, 'Petites bêtes', 5, 'QCM', 'Combien de temps vit une éphémère adulte (l\'insecte) ?', 'Quelques heures à quelques jours', 'Environ un mois', 'Environ un an', 'Une seule minute',
      'Elle ne se nourrit même pas : sa bouche est atrophiée. Elle ne vit que pour se reproduire.', '',
      'Sa larve, elle, peut vivre un à deux ans dans l\'eau. Son nom scientifique, Ephemeroptera, vient du grec « qui ne dure qu\'un jour ».'),
    q(N, 'Mer', 5, 'QCM', 'Quel animal est le plus venimeux du monde ?', 'La guêpe de mer (méduse-boîte)', 'Le mamba noir', 'Le scorpion jaune', 'Le cobra royal',
      'Cette méduse australienne peut tuer un humain en quelques minutes.', '',
      'Elle est presque transparente et possède 24 yeux. Sur certaines plages australiennes, on se baigne avec des combinaisons intégrales en saison.'),

    // ---------------- CINÉMA ----------------
    q(C, 'Animation', 1, 'QCM', 'Comment s\'appelle la reine des neiges dans le film Disney de 2013 ?', 'Elsa', 'Anna', 'Aurore', 'Raiponce',
      '« La Reine des neiges », inspirée d\'un conte d\'Andersen, et sa chanson « Libérée, délivrée ».', '',
      'Au départ, Elsa devait être la méchante. La chanson « Let It Go » a tellement plu que les scénaristes ont réécrit l\'histoire.'),
    q(C, 'Films', 1, 'QCM', 'Dans quel film un extraterrestre veut-il « téléphoner maison » ?', 'E.T. l\'extra-terrestre', 'Rencontres du troisième type', 'Men in Black', 'Mars Attacks!',
      'Le film de Steven Spielberg sorti en 1982.', '',
      'Les bonbons que mange E.T. sont des Reese\'s Pieces : Mars avait refusé que ses M&M\'s soient utilisés. Les ventes de Reese\'s Pieces ont explosé.'),
    q(C, 'Films', 2, 'QCM', 'Quel acteur incarne Indiana Jones ?', 'Harrison Ford', 'Tom Selleck', 'Kevin Costner', 'Mel Gibson',
      'Cinq films, de « Les Aventuriers de l\'arche perdue » (1981) à « Le Cadran de la destinée » (2023).', 'Il est aussi Han Solo.',
      'Tom Selleck avait été choisi en premier, mais son contrat avec la série « Magnum » l\'a empêché d\'accepter.'),
    q(C, 'Films français', 2, 'QCM', 'Dans « La Grande Vadrouille » (1966), quels acteurs forment le célèbre duo ?', 'Louis de Funès et Bourvil', 'Fernandel et Bourvil', 'Jean Gabin et Louis de Funès', 'Jean Marais et Bourvil',
      'Un chef d\'orchestre et un peintre en bâtiment aident des aviateurs anglais sous l\'Occupation.', '',
      'Avec plus de 17 millions d\'entrées, il est resté le plus grand succès du cinéma français pendant plus de 40 ans, jusqu\'à « Bienvenue chez les Ch\'tis » (2008).'),
    q(C, 'Films', 2, 'VF', 'Dans « Retour vers le futur », la machine à voyager dans le temps est une DeLorean.', 'Vrai', '', '', '',
      'Vrai : il faut atteindre 88 miles à l\'heure (environ 141 km/h) pour voyager dans le temps.', '',
      'Au départ, la machine devait être un réfrigérateur ! Les producteurs ont eu peur que des enfants s\'enferment dans le leur pour imiter le film.'),
    q(C, 'Films', 2, 'QCM', 'Quel requin terrorise la station balnéaire d\'Amity dans le film de Spielberg (1975) ?', 'Un grand requin blanc', 'Un requin-tigre', 'Un requin-marteau', 'Un requin-baleine',
      '« Les Dents de la mer » a inventé le concept de blockbuster de l\'été.', '',
      'Le requin mécanique, surnommé « Bruce », tombait sans cesse en panne. Spielberg a donc dû suggérer sa présence… ce qui a rendu le film encore plus angoissant.'),
    q(C, 'Acteurs', 3, 'QCM', 'Quel acteur français est le « Magnifique » et « l\'As des as » ?', 'Jean-Paul Belmondo', 'Alain Delon', 'Jean Rochefort', 'Pierre Richard',
      'Surnommé « Bébel », il faisait lui-même ses cascades.', '',
      'Dans « Peur sur la ville » (1975), il est suspendu à un hélicoptère au-dessus de Paris sans doublure. Il a reçu un hommage national aux Invalides en 2021.'),
    q(C, 'Films', 3, 'QCM', 'Dans « Matrix », quelle pilule Neo choisit-il ?', 'La rouge', 'La bleue', 'La verte', 'Aucune',
      'La rouge révèle la vérité, la bleue le laisse dans l\'illusion.', '',
      'Les chiffres verts qui défilent sur l\'écran sont des caractères japonais tirés… d\'un livre de recettes de sushis appartenant au designer.'),
    q(C, 'Films français', 3, 'QCM', 'Quel film de 1995 de Mathieu Kassovitz commence par « Jusqu\'ici tout va bien » ?', 'La Haine', 'Les Misérables', 'Taxi', 'Assassin(s)',
      'Tourné en noir et blanc dans une cité de Chanteloup-les-Vignes, avec Vincent Cassel.', '',
      'Il a valu à Kassovitz le prix de la mise en scène à Cannes en 1995. Le film a été projeté aux ministres à la demande du Premier ministre de l\'époque.'),
    q(C, 'Oscars', 3, 'QCM', 'Quel film en noir et blanc et muet a remporté l\'Oscar du meilleur film en 2012 ?', 'The Artist', 'Hugo Cabret', 'La La Land', 'Le Discours d\'un roi',
      'Réalisé par Michel Hazanavicius, avec Jean Dujardin et Bérénice Bejo.', '',
      'Le chien Uggie a volé la vedette : il a reçu le « Palm Dog » à Cannes, un prix pour les chiens acteurs.'),
    q(C, 'Animation', 3, 'QCM', 'Quel est le premier long métrage entièrement réalisé en images de synthèse ?', 'Toy Story', 'Shrek', 'Le Monde de Nemo', 'Fourmiz',
      'Sorti en 1995, produit par Pixar.', '',
      'Il a fallu environ 800 000 heures de calcul machine pour les 81 minutes du film. Aujourd\'hui, un téléphone ferait le travail bien plus vite.'),
    q(C, 'Réalisateurs', 4, 'QCM', 'Quel réalisateur a tourné « 2001, l\'Odyssée de l\'espace » et « Shining » ?', 'Stanley Kubrick', 'Steven Spielberg', 'Ridley Scott', 'David Lynch',
      'Perfectionniste, il pouvait faire tourner la même scène plus de 100 fois.', '',
      'Pour « Shining », la scène de Shelley Duvall dans l\'escalier aurait été tournée 127 fois, un record.'),
    q(C, 'Films', 4, 'ESTIMATION', 'En quelle année est sorti le film « Le Parrain » ?', '1972', '', '2', '',
      'Réalisé par Francis Ford Coppola, avec Marlon Brando et Al Pacino.', 'Au début des années 70.',
      'Brando avait mis du coton dans ses joues pour les essais. Pour le tournage, un dentiste lui a fabriqué un appareil.'),
    q(C, 'Acteurs', 5, 'QCM', 'Quel acteur a remporté le plus d\'Oscars d\'interprétation chez les hommes ?', 'Daniel Day-Lewis', 'Jack Nicholson', 'Tom Hanks', 'Marlon Brando',
      'Trois Oscars du meilleur acteur : « My Left Foot », « There Will Be Blood » et « Lincoln ».', '',
      'Jack Nicholson en a aussi trois, mais dont un pour un second rôle. Chez les femmes, Katharine Hepburn détient le record avec quatre.'),
    q(C, 'Festivals', 5, 'QCM', 'Quel film de Claude Lelouch a remporté la Palme d\'or en 1966 ?', 'Un homme et une femme', 'Les Parapluies de Cherbourg', 'Le Salaire de la peur', 'Orfeu Negro',
      'Avec Anouk Aimée et Jean-Louis Trintignant, et sa musique de Francis Lai (« Chabadabada »).', '',
      'Tourné en trois semaines avec très peu de moyens, alternant couleur et noir et blanc… en partie faute d\'argent pour la pellicule couleur.'),
  ];
}
