/**
 * Banque de questions (2) — Histoire, Géographie, Sciences, Nature & Animaux, Sport
 * Format : voir Banque1.gs
 */
function banque6_() {
  const H = 'Histoire', G = 'Géographie', S = 'Sciences', N = 'Nature & Animaux', SP = 'Sport';
  return [
    // ---------------- HISTOIRE ----------------
    [H, 'Napoléon', 1, 'QCM', 'Qui a été le premier empereur des Français ?', 'Napoléon Ier', 'Louis XVIII', 'Charlemagne', 'Napoléon III', 'Sacré en 1804 à Notre-Dame de Paris.', ''],
    [H, 'Moyen Âge', 1, 'QCM', 'Quel peuple naviguait à bord de drakkars ?', 'Les Vikings', 'Les Romains', 'Les Gaulois', 'Les Mongols', '', ''],
    [H, 'XXe siècle', 1, 'VF', 'La Seconde Guerre mondiale s\'est terminée en 1945.', 'Vrai', '', '', '', 'Le 8 mai en Europe, le 2 septembre en Asie.', ''],
    [H, 'Antiquité', 1, 'QCM', 'Quel chef gaulois a affronté Jules César à Alésia ?', 'Vercingétorix', 'Astérix', 'Ambiorix', 'Brennus', 'En 52 av. J.-C.', ''],
    [H, 'France', 2, 'QCM', 'Quel roi de France a été guillotiné en 1793 ?', 'Louis XVI', 'Louis XV', 'Louis XIV', 'Charles X', 'Exécuté le 21 janvier 1793, place de la Révolution (aujourd\'hui place de la Concorde).', ''],
    [H, 'XXe siècle', 2, 'QCM', 'Quelle ville a été frappée par la première bombe atomique ?', 'Hiroshima', 'Nagasaki', 'Tokyo', 'Osaka', 'Le 6 août 1945. Nagasaki a été touchée trois jours plus tard.', ''],
    [H, 'XXe siècle', 2, 'ESTIMATION', 'En quelle année l\'homme a-t-il marché sur la Lune pour la première fois ?', '1969', '', '1', '', 'Mission Apollo 11.', ''],
    [H, 'Monde', 2, 'QCM', 'Qui était président des États-Unis pendant la guerre de Sécession ?', 'Abraham Lincoln', 'George Washington', 'Thomas Jefferson', 'Ulysses Grant', 'Il a aboli l\'esclavage et a été assassiné en 1865.', ''],
    [H, 'XXe siècle', 3, 'QCM', 'Où a eu lieu le débarquement allié du 6 juin 1944 ?', 'En Normandie', 'En Provence', 'En Sicile', 'À Dunkerque', 'Le « D-Day », opération Overlord.', ''],
    [H, 'XXe siècle', 3, 'QCM', 'Qui a été le premier homme à aller dans l\'espace ?', 'Youri Gagarine', 'Neil Armstrong', 'Alexeï Leonov', 'John Glenn', 'Le 12 avril 1961, à bord de Vostok 1.', ''],
    [H, 'France', 3, 'QCM', 'Quel roi des Francs a été baptisé à Reims ?', 'Clovis', 'Dagobert', 'Childéric', 'Pépin le Bref', 'Vers 496-499, par l\'évêque Remi.', ''],
    [H, 'Chronologie', 3, 'ORDRE', 'Remettez ces événements dans l\'ordre chronologique.', 'Débarquement en Normandie | Fin de la guerre d\'Algérie | Chute du mur de Berlin | Arrivée des pièces et billets en euros', 'Du plus ancien au plus récent', '', '', '1944, 1962, 1989, 2002.', ''],
    [H, 'Explorateurs', 4, 'VF', 'Christophe Colomb était portugais.', 'Faux', '', '', '', 'Il était génois, mais naviguait pour les rois d\'Espagne.', ''],
    [H, 'Antiquité', 4, 'QCM', 'Quelle reine d\'Égypte était l\'alliée et la compagne de Marc Antoine ?', 'Cléopâtre VII', 'Néfertiti', 'Hatchepsout', 'Néfertari', '', ''],
    [H, 'France', 4, 'ESTIMATION', 'En quelle année a été proclamée la Première République française ?', '1792', '', '2', '', 'Le 21 septembre 1792.', ''],
    [H, 'Monde', 4, 'QCM', 'Quel empire était dirigé par Soliman le Magnifique ?', 'L\'Empire ottoman', 'L\'Empire perse', 'L\'Empire moghol', 'L\'Empire byzantin', 'Au XVIe siècle.', ''],
    [H, 'XXe siècle', 4, 'VF', 'La révolution russe a eu lieu en 1917.', 'Vrai', '', '', '', 'Révolutions de février puis d\'octobre 1917.', ''],
    [H, 'Monde', 5, 'QCM', 'Quels traités ont mis fin à la guerre de Trente Ans en 1648 ?', 'Les traités de Westphalie', 'Le traité d\'Utrecht', 'Le traité des Pyrénées', 'La paix d\'Augsbourg', '', ''],
    [H, 'Napoléon', 5, 'QCM', 'Quelle bataille navale de 1805 a vu la victoire de l\'amiral Nelson ?', 'Trafalgar', 'Aboukir', 'Lépante', 'Salamine', 'Nelson y trouva la mort.', ''],
    [H, 'France', 5, 'ESTIMATION', 'Combien d\'années a duré le règne de Louis XIV ?', '72', 'ans', '2', '', 'De 1643 à 1715 : le plus long règne de l\'histoire de France.', ''],

    // ---------------- GÉOGRAPHIE ----------------
    [G, 'Capitales', 1, 'QCM', 'Quelle est la capitale du Royaume-Uni ?', 'Londres', 'Manchester', 'Dublin', 'Édimbourg', '', ''],
    [G, 'Monde', 1, 'QCM', 'Sur quel continent se trouve l\'Égypte ?', 'L\'Afrique', 'L\'Asie', 'L\'Europe', 'L\'Océanie', 'Seule la péninsule du Sinaï est en Asie.', ''],
    [G, 'Montagnes', 1, 'VF', 'Le mont Everest est la plus haute montagne du monde.', 'Vrai', '', '', '', 'Environ 8 849 m, entre le Népal et la Chine.', ''],
    [G, 'Capitales', 1, 'QCM', 'Quelle est la capitale de l\'Allemagne ?', 'Berlin', 'Munich', 'Francfort', 'Hambourg', '', ''],
    [G, 'Capitales', 2, 'QCM', 'De quel pays Lisbonne est-elle la capitale ?', 'Le Portugal', 'L\'Espagne', 'Le Brésil', 'L\'Italie', '', ''],
    [G, 'Monde', 2, 'QCM', 'Quel est le plus grand océan du monde ?', 'L\'océan Pacifique', 'L\'océan Atlantique', 'L\'océan Indien', 'L\'océan Arctique', 'Il couvre près d\'un tiers de la surface de la Terre.', ''],
    [G, 'France', 2, 'QCM', 'Quelle chaîne de montagnes sépare la France de l\'Espagne ?', 'Les Pyrénées', 'Les Alpes', 'Le Jura', 'Les Vosges', '', ''],
    [G, 'Monde', 2, 'QCM', 'Quel est le plus grand pays du monde par sa superficie ?', 'La Russie', 'Le Canada', 'La Chine', 'Les États-Unis', 'Plus de 17 millions de km².', ''],
    [G, 'France', 3, 'ESTIMATION', 'Combien de régions compte la France métropolitaine depuis 2016 ?', '13', 'régions', '0', '', '18 en comptant les régions d\'outre-mer.', ''],
    [G, 'Capitales', 3, 'QCM', 'Quelle est la capitale du Brésil ?', 'Brasília', 'Rio de Janeiro', 'São Paulo', 'Salvador', 'Ville nouvelle inaugurée en 1960.', 'Piège classique !'],
    [G, 'Monuments', 3, 'QCM', 'Dans quel pays se trouve le Machu Picchu ?', 'Le Pérou', 'Le Mexique', 'La Bolivie', 'Le Chili', 'Cité inca perchée dans les Andes.', ''],
    [G, 'Fleuves', 3, 'VF', 'Le Rhône prend sa source en Suisse.', 'Vrai', '', '', '', 'Au glacier du Rhône, dans le Valais. Il traverse le lac Léman.', ''],
    [G, 'Capitales', 3, 'QCM', 'Quelle est la capitale de la Suisse ?', 'Berne', 'Genève', 'Zurich', 'Lausanne', 'Officiellement « ville fédérale ».', ''],
    [G, 'Capitales', 4, 'QCM', 'Quelle est la capitale du Maroc ?', 'Rabat', 'Casablanca', 'Marrakech', 'Fès', '', ''],
    [G, 'Fleuves', 4, 'ESTIMATION', 'Combien de kilomètres mesure la Seine ?', '777', 'km', '30', '', 'Du plateau de Langres jusqu\'à la Manche, au Havre.', ''],
    [G, 'Population', 4, 'QCM', 'Quel est le pays le plus peuplé d\'Afrique ?', 'Le Nigeria', 'L\'Égypte', 'L\'Éthiopie', 'L\'Afrique du Sud', 'Plus de 220 millions d\'habitants.', ''],
    [G, 'Europe', 4, 'VF', 'La Suisse est membre de l\'Union européenne.', 'Faux', '', '', '', 'Elle fait partie de l\'espace Schengen, mais pas de l\'UE.', ''],
    [G, 'Monde', 4, 'ORDRE', 'Classez ces pays selon leur superficie.', 'Russie | Canada | Brésil | France', 'Du plus grand au plus petit', '', '', '', ''],
    [G, 'Capitales', 5, 'QCM', 'Quelle est la capitale de la Mongolie ?', 'Oulan-Bator', 'Astana', 'Bichkek', 'Douchanbé', '', ''],
    [G, 'Monde', 5, 'ESTIMATION', 'Combien de kilomètres mesure environ la circonférence de la Terre à l\'équateur ?', '40075', 'km', '1000', '', 'Environ 40 000 km.', ''],
    [G, 'Monde', 5, 'QCM', 'Quel pays est réputé compter le plus grand nombre d\'îles ?', 'La Suède', 'L\'Indonésie', 'Les Philippines', 'La Grèce', 'Plus de 260 000 îles et îlots recensés.', 'Réponse surprenante.'],
    [G, 'Montagnes', 5, 'QCM', 'Quel est le plus haut sommet d\'Afrique ?', 'Le Kilimandjaro', 'Le mont Kenya', 'Le Toubkal', 'Le Ruwenzori', 'Environ 5 895 m, en Tanzanie.', ''],

    // ---------------- SCIENCES ----------------
    [S, 'Espace', 1, 'QCM', 'Quelle planète est surnommée « la planète rouge » ?', 'Mars', 'Jupiter', 'Vénus', 'Saturne', 'Sa couleur vient de l\'oxyde de fer.', ''],
    [S, 'Physique', 1, 'QCM', 'Sous quelle forme est l\'eau à −10 °C ?', 'Solide (glace)', 'Liquide', 'Gazeuse', 'Plasma', '', ''],
    [S, 'Biologie', 1, 'VF', 'Les plantes ont besoin de lumière pour vivre.', 'Vrai', '', '', '', 'Elles s\'en servent pour la photosynthèse.', ''],
    [S, 'Corps humain', 1, 'QCM', 'Quel organe permet de respirer ?', 'Les poumons', 'Le cœur', 'L\'estomac', 'Le foie', '', ''],
    [S, 'Physique', 1, 'ESTIMATION', 'À quelle température, en °C, l\'eau pure gèle-t-elle ?', '0', '°C', '0', '', '', ''],
    [S, 'Corps humain', 2, 'QCM', 'Combien de dents de lait a un enfant ?', '20', '32', '24', '16', 'Un adulte a 32 dents, dents de sagesse comprises.', ''],
    [S, 'Espace', 2, 'QCM', 'Quelle planète a les anneaux les plus visibles ?', 'Saturne', 'Jupiter', 'Uranus', 'Neptune', 'Les autres géantes ont aussi des anneaux, mais bien plus discrets.', ''],
    [S, 'Espace', 2, 'VF', 'La Lune produit sa propre lumière.', 'Faux', '', '', '', 'Elle réfléchit la lumière du Soleil.', ''],
    [S, 'Espace', 2, 'ESTIMATION', 'Combien d\'heures met la Terre pour faire un tour sur elle-même ?', '24', 'h', '0', '', 'Précisément 23 h 56 min par rapport aux étoiles.', ''],
    [S, 'Corps humain', 3, 'QCM', 'Quel est le plus grand organe du corps humain ?', 'La peau', 'Le foie', 'Le cerveau', 'L\'intestin', 'Environ 2 m² chez un adulte.', ''],
    [S, 'Chimie', 3, 'QCM', 'Quel gaz est le plus abondant dans l\'air ?', 'L\'azote', 'L\'oxygène', 'Le dioxyde de carbone', 'L\'argon', 'Environ 78 %, contre 21 % d\'oxygène.', ''],
    [S, 'Corps humain', 3, 'ESTIMATION', 'Combien de litres de sang contient environ le corps d\'un adulte ?', '5', 'L', '1', '', '', ''],
    [S, 'Physique', 3, 'QCM', 'Quelle unité mesure la puissance électrique ?', 'Le watt', 'Le volt', 'L\'ampère', 'L\'ohm', '', ''],
    [S, 'Espace', 3, 'ORDRE', 'Classez ces planètes selon leur taille.', 'Jupiter | Saturne | Terre | Mercure', 'De la plus grande à la plus petite', '', '', '', ''],
    [S, 'Physique', 3, 'QCM', 'Quelle force maintient les planètes en orbite autour du Soleil ?', 'La gravitation', 'Le magnétisme', 'La force nucléaire', 'La friction', '', ''],
    [S, 'Savants', 4, 'QCM', 'Quel scientifique a proposé la théorie de l\'évolution par la sélection naturelle ?', 'Charles Darwin', 'Jean-Baptiste de Lamarck', 'Gregor Mendel', 'Louis Pasteur', '« De l\'origine des espèces », 1859.', ''],
    [S, 'Savants', 4, 'QCM', 'Qui a mis au point le vaccin contre la rage en 1885 ?', 'Louis Pasteur', 'Robert Koch', 'Edward Jenner', 'Alexander Fleming', '', ''],
    [S, 'Corps humain', 4, 'VF', 'Le cœur humain compte quatre cavités.', 'Vrai', '', '', '', 'Deux oreillettes et deux ventricules.', ''],
    [S, 'Chimie', 4, 'QCM', 'Quel est le symbole chimique du fer ?', 'Fe', 'Fr', 'Ir', 'F', 'Du latin « ferrum ».', ''],
    [S, 'Espace', 4, 'VF', 'L\'année-lumière est une unité de temps.', 'Faux', '', '', '', 'C\'est une distance : environ 9 500 milliards de km.', ''],
    [S, 'Chimie', 5, 'QCM', 'Quel est le numéro atomique de l\'oxygène ?', '8', '6', '16', '12', '8 protons dans son noyau.', ''],
    [S, 'Espace', 5, 'ESTIMATION', 'Quelle est la distance moyenne entre la Terre et la Lune, en km ?', '384400', 'km', '20000', '', 'Environ 384 400 km.', ''],
    [S, 'Espace', 5, 'QCM', 'Quelle est la planète la plus éloignée du Soleil ?', 'Neptune', 'Uranus', 'Saturne', 'Pluton', 'Pluton n\'est plus considérée comme une planète depuis 2006.', 'Piège : Pluton !'],

    // ---------------- NATURE & ANIMAUX ----------------
    [N, 'Petites bêtes', 1, 'QCM', 'Quel insecte fabrique le miel ?', 'L\'abeille', 'La guêpe', 'La coccinelle', 'La fourmi', '', ''],
    [N, 'Petites bêtes', 1, 'QCM', 'Combien de pattes a un insecte ?', '6', '8', '4', '10', '', ''],
    [N, 'Mammifères', 1, 'QCM', 'Quel animal a une trompe ?', 'L\'éléphant', 'Le rhinocéros', 'L\'hippopotame', 'La girafe', '', ''],
    [N, 'Vocabulaire', 1, 'QCM', 'Comment s\'appelle le cri du chat ?', 'Le miaulement', 'L\'aboiement', 'Le rugissement', 'Le hennissement', '', ''],
    [N, 'Ferme', 2, 'QCM', 'Comment s\'appelle le petit du cheval ?', 'Le poulain', 'Le veau', 'Le faon', 'Le chevreau', '', ''],
    [N, 'Mammifères', 2, 'QCM', 'Quel est le plus grand mammifère terrestre ?', 'L\'éléphant d\'Afrique', 'L\'hippopotame', 'Le rhinocéros blanc', 'La girafe', '', ''],
    [N, 'Oiseaux', 2, 'QCM', 'Quel oiseau est le symbole de la paix ?', 'La colombe', 'Le cygne', 'L\'aigle', 'Le moineau', '', ''],
    [N, 'Oiseaux', 2, 'ORDRE', 'Classez ces oiseaux par taille.', 'Autruche | Aigle royal | Pigeon | Colibri', 'Du plus grand au plus petit', '', '', '', ''],
    [N, 'Oiseaux', 3, 'VF', 'Le pingouin et le manchot sont le même animal.', 'Faux', '', '', '', 'Le pingouin vit dans l\'hémisphère Nord et vole. Le manchot, lui, vit dans l\'hémisphère Sud et ne vole pas.', ''],
    [N, 'Mammifères', 3, 'QCM', 'Quel animal peut dormir debout ?', 'Le cheval', 'Le chat', 'Le lapin', 'Le chien', 'Ses pattes se « verrouillent » pendant qu\'il somnole.', ''],
    [N, 'Mammifères', 3, 'ESTIMATION', 'Combien d\'années vit en moyenne un chat domestique ?', '15', 'ans', '3', '', '', ''],
    [N, 'Mammifères', 3, 'QCM', 'Quel grand singe vit sur les îles de Bornéo et de Sumatra ?', 'L\'orang-outan', 'Le gorille', 'Le chimpanzé', 'Le bonobo', 'Son nom signifie « homme de la forêt » en malais.', ''],
    [N, 'Mer', 3, 'QCM', 'Quelle est la plus grande espèce de requin ?', 'Le requin-baleine', 'Le grand requin blanc', 'Le requin-tigre', 'Le requin-marteau', 'Jusqu\'à 18 m. Il se nourrit de plancton.', ''],
    [N, 'Reptiles', 4, 'VF', 'Les serpents ont des paupières.', 'Faux', '', '', '', 'Leurs yeux sont protégés par une écaille transparente.', ''],
    [N, 'Vocabulaire', 4, 'QCM', 'Comment s\'appelle le petit du lièvre ?', 'Le levraut', 'Le lapereau', 'Le marcassin', 'Le faon', 'Le lapereau est le petit du lapin.', ''],
    [N, 'Mammifères', 4, 'ESTIMATION', 'Combien de kilos de nourriture un éléphant mange-t-il par jour ?', '150', 'kg', '50', '', 'Entre 100 et 200 kg de végétaux.', ''],
    [N, 'Plantes', 4, 'QCM', 'Quel conifère perd ses aiguilles en hiver ?', 'Le mélèze', 'Le sapin', 'L\'épicéa', 'Le pin', '', ''],
    [N, 'Oiseaux', 4, 'QCM', 'Quel oiseau est capable de voler en arrière ?', 'Le colibri', 'L\'hirondelle', 'Le martinet', 'Le moineau', '', ''],
    [N, 'Mer', 4, 'QCM', 'Quel mammifère marin est surnommé la « licorne des mers » ?', 'Le narval', 'Le béluga', 'Le dauphin', 'Le lamantin', 'Sa « corne » est en fait une dent qui peut dépasser 2 m.', ''],
    [N, 'Mammifères', 5, 'QCM', 'Quel animal a des empreintes digitales presque identiques à celles de l\'humain ?', 'Le koala', 'Le chimpanzé', 'Le gorille', 'Le panda', 'Au point qu\'elles pourraient semer le doute sur une scène de crime !', ''],
    [N, 'Mammifères', 5, 'VF', 'La girafe a le même nombre de vertèbres cervicales que l\'humain.', 'Vrai', '', '', '', 'Sept, comme presque tous les mammifères. Elles sont juste beaucoup plus longues.', ''],

    // ---------------- SPORT ----------------
    [SP, 'Basket', 1, 'QCM', 'Combien de joueurs par équipe y a-t-il sur un terrain de basket ?', '5', '6', '7', '4', '', ''],
    [SP, 'Rugby', 1, 'QCM', 'Dans quel sport joue-t-on avec un ballon ovale ?', 'Le rugby', 'Le football', 'Le volley-ball', 'Le handball', '', ''],
    [SP, 'Raquettes', 1, 'VF', 'Au tennis, on a le droit de toucher la balle avec la main.', 'Faux', '', '', '', '', ''],
    [SP, 'Rugby', 1, 'QCM', 'Quel sport se joue lors du Tournoi des Six Nations ?', 'Le rugby', 'Le football', 'Le handball', 'Le cricket', '', ''],
    [SP, 'Combat', 2, 'QCM', 'Dans quel pays le judo a-t-il été inventé ?', 'Au Japon', 'En Chine', 'En Corée', 'Au Brésil', 'Par Jigoro Kano, en 1882.', ''],
    [SP, 'Football', 2, 'ESTIMATION', 'Combien de minutes dure un match de football, sans les prolongations ?', '90', 'min', '0', '', 'Deux mi-temps de 45 minutes, plus le temps additionnel.', ''],
    [SP, 'Football', 2, 'QCM', 'Quel pays a remporté la Coupe du monde de football 2022 ?', 'L\'Argentine', 'La France', 'Le Brésil', 'La Croatie', 'Finale contre la France, gagnée aux tirs au but.', ''],
    [SP, 'Basket', 2, 'QCM', 'Quel sport pratique Victor Wembanyama ?', 'Le basket', 'Le volley-ball', 'Le handball', 'Le tennis', 'Avec les San Antonio Spurs en NBA.', ''],
    [SP, 'Raquettes', 2, 'QCM', 'Dans quel pays se joue le tournoi de Wimbledon ?', 'Au Royaume-Uni', 'Aux États-Unis', 'En Australie', 'En France', 'Sur gazon, près de Londres.', ''],
    [SP, 'Rugby', 3, 'QCM', 'Dans quel sport s\'illustre Antoine Dupont ?', 'Le rugby', 'Le football', 'Le handball', 'Le basket', 'Il a aussi été champion olympique de rugby à 7 en 2024.', ''],
    [SP, 'Handball', 3, 'VF', 'Au handball, une équipe compte 7 joueurs sur le terrain.', 'Vrai', '', '', '', 'Six joueurs de champ et un gardien.', ''],
    [SP, 'Natation', 3, 'QCM', 'Quel nageur français a remporté 4 médailles d\'or aux JO de Paris 2024 ?', 'Léon Marchand', 'Florent Manaudou', 'Yannick Agnel', 'Maxime Grousset', '', ''],
    [SP, 'Natation', 3, 'ESTIMATION', 'Combien de mètres mesure un bassin olympique ?', '50', 'm', '0', '', '', ''],
    [SP, 'Divers', 3, 'ORDRE', 'Classez ces balles et ballons par taille.', 'Ballon de basket | Ballon de football | Balle de tennis | Balle de golf', 'Du plus grand au plus petit', '', '', '', ''],
    [SP, 'Athlétisme', 3, 'VF', 'Le marathon tire son nom d\'une ville grecque.', 'Vrai', '', '', '', 'En souvenir du messager qui aurait couru de Marathon à Athènes.', ''],
    [SP, 'Athlétisme', 4, 'QCM', 'Dans quelle discipline Renaud Lavillenie a-t-il été champion olympique en 2012 ?', 'Le saut à la perche', 'Le saut en hauteur', 'Le saut en longueur', 'Le triple saut', '', ''],
    [SP, 'Rugby', 4, 'ESTIMATION', 'Combien de points rapporte un essai transformé au rugby ?', '7', 'points', '0', '', '5 pour l\'essai et 2 pour la transformation.', ''],
    [SP, 'Football', 4, 'QCM', 'Quel club a remporté le plus de Ligues des champions ?', 'Le Real Madrid', 'L\'AC Milan', 'Liverpool', 'Le Bayern Munich', '', ''],
    [SP, 'Raquettes', 4, 'QCM', 'Quel joueur détient le record de titres du Grand Chelem en simple messieurs ?', 'Novak Djokovic', 'Rafael Nadal', 'Roger Federer', 'Pete Sampras', '24 titres.', ''],
    [SP, 'Football', 4, 'ESTIMATION', 'En quelle année a eu lieu la première Coupe du monde de football ?', '1930', '', '2', '', 'En Uruguay, qui l\'a remportée.', ''],
    [SP, 'Golf', 5, 'QCM', 'Au golf, comment appelle-t-on un trou joué en un coup de moins que le par ?', 'Un birdie', 'Un eagle', 'Un bogey', 'Un albatros', 'Eagle = −2, albatros = −3, bogey = +1.', ''],
    [SP, 'Football', 5, 'QCM', 'Dans quel pays s\'est déroulée la première Coupe du monde de football ?', 'L\'Uruguay', 'Le Brésil', 'L\'Italie', 'La France', 'En 1930.', ''],
  ];
}
