/**
 * Banque de questions (9) — Musique, Sport, Arts & Littérature, Gastronomie, Divers.
 * q(thème, catégorie, difficulté, type, question, réponse, choix2, choix3, choix4, explication, indices MJ, anecdote MJ)
 * L'explication s'affiche pour tout le monde ; l'anecdote (« Pour animer ») est réservée au maître du jeu.
 */
function banque9_() {
  const M = 'Musique', SP = 'Sport', A = 'Arts & Littérature', GA = 'Gastronomie', D = 'Divers';
  const q = (th, cat, diff, type, texte, rep, c2, c3, c4, expl, ind, anec) =>
    [th, cat, diff, type, texte, rep, c2 || '', c3 || '', c4 || '', expl || '', ind || '', '', '', '', '', anec || ''];
  return [
    // ---------------- MUSIQUE ----------------
    q(M, 'Chanson française', 1, 'QCM', 'Qui chante « Je te promets » (1986) ?', 'Johnny Hallyday', 'Michel Sardou', 'Eddy Mitchell', 'Florent Pagny',
      'Écrite par Jean-Jacques Goldman, sur l\'album « Gang ».', '',
      'Goldman a écrit tout l\'album « Gang » pour Johnny, qui cherchait un nouveau souffle. L\'album s\'est vendu à plus d\'un million d\'exemplaires.'),
    q(M, 'Pop-rock', 1, 'QCM', 'Quelle chanteuse est surnommée « Queen B » ?', 'Beyoncé', 'Britney Spears', 'Rihanna', 'Billie Eilish',
      'Ex-membre des Destiny\'s Child, elle détient le record de Grammy Awards remportés.', '',
      'Elle a dépassé les 30 Grammys. En 2025, son album country « Cowboy Carter » lui a enfin valu le Grammy de l\'album de l\'année.'),
    q(M, 'Instruments', 1, 'QCM', 'Combien de cordes a une guitare basse standard ?', '4', '5', '6', '12',
      'Accordées comme les quatre cordes les plus graves d\'une guitare, une octave plus bas.', '',
      'La basse électrique a été popularisée par Leo Fender en 1951, avec la Precision Bass : avec des frettes, on jouait enfin « précisément » juste.'),
    q(M, 'Chanson française', 2, 'QCM', 'Quel chanteur a écrit « Les Lacs du Connemara » ?', 'Michel Sardou', 'Julien Clerc', 'Alain Souchon', 'Serge Lama',
      'Sortie en 1981, elle raconte l\'Irlande… que Sardou n\'avait jamais visitée en l\'écrivant.', '',
      'Elle dure plus de 6 minutes et est devenue un hymne des soirées étudiantes, où tout le monde s\'accroupit puis saute au refrain.'),
    q(M, 'Pop-rock', 2, 'QCM', 'Quel groupe irlandais a pour chanteur Bono ?', 'U2', 'The Cranberries', 'The Corrs', 'Thin Lizzy',
      'Formé à Dublin en 1976, avec The Edge, Adam Clayton et Larry Mullen Jr.', '',
      'En 2014, U2 a offert son album à tous les utilisateurs d\'iTunes, soit 500 millions de personnes… qui ne l\'avaient pas toutes demandé.'),
    q(M, 'Classique', 2, 'VF', 'Frédéric Chopin était polonais.', 'Vrai', '', '', '',
      'Vrai : né près de Varsovie en 1810, d\'un père français et d\'une mère polonaise. Il a passé la seconde moitié de sa vie à Paris.', '',
      'Il est enterré au Père-Lachaise, mais son cœur, selon sa volonté, repose dans une église de Varsovie.'),
    q(M, 'Rap', 2, 'QCM', 'Quel rappeur originaire de Caen a sorti l\'album « Civilisation » en 2021 ?', 'Orelsan', 'Nekfeu', 'Vald', 'Lomepal',
      'Porté par les titres « L\'odeur de l\'essence » et « La Quête ».', '',
      'La même année, sa série documentaire « Montre jamais ça à personne », tournée par son frère pendant près de 20 ans, a raconté son parcours depuis ses débuts.'),
    q(M, 'Eurovision', 3, 'QCM', 'Quelle chanteuse a donné la dernière victoire à la France à l\'Eurovision, en 1977 ?', 'Marie Myriam', 'Frida Boccara', 'Isabelle Aubret', 'Patricia Kaas',
      'Avec « L\'oiseau et l\'enfant ».', '',
      'La France a gagné 5 fois (1958, 1960, 1962, 1969, 1977). Depuis, sa meilleure place est la 2e de Barbara Pravi en 2021.'),
    q(M, 'Classique', 3, 'QCM', 'Quel compositeur a écrit « La Truite » et « La Jeune Fille et la Mort » ?', 'Franz Schubert', 'Robert Schumann', 'Johannes Brahms', 'Felix Mendelssohn',
      'Compositeur viennois, mort à 31 ans en 1828, auteur de plus de 600 lieder.', '',
      'Il admirait tellement Beethoven qu\'il a porté une torche à ses funérailles. Il a été enterré, à sa demande, près de lui.'),
    q(M, 'Pop-rock', 3, 'QCM', 'Quel album des Beatles montre les quatre musiciens traversant un passage piéton ?', 'Abbey Road', 'Let It Be', 'Revolver', 'Help!',
      'La photo a été prise en 1969 devant les studios d\'enregistrement d\'Abbey Road, à Londres.', '',
      'Paul est pieds nus sur la photo, ce qui a alimenté la rumeur « Paul est mort ». Le passage piéton est aujourd\'hui classé et filmé en permanence par une webcam.'),
    q(M, 'Instruments', 3, 'QCM', 'Quel instrument joue le « la » pour accorder l\'orchestre ?', 'Le hautbois', 'Le premier violon', 'Le piano', 'La flûte',
      'Son timbre perçant et sa justesse stable en font la référence.', '',
      'C\'est ensuite le premier violon, le « violon solo », qui mène l\'accord des cordes et salue le public à l\'entrée.'),
    q(M, 'Chanson française', 3, 'ESTIMATION', 'En quelle année Édith Piaf est-elle morte ?', '1963', '', '2', '',
      'Le 10 octobre 1963. Son ami Jean Cocteau est mort quelques heures plus tard.', 'Au début des années 60.',
      'Plus de 40 000 personnes ont assisté à ses obsèques au Père-Lachaise. L\'Église avait refusé une messe à cause de sa vie jugée scandaleuse.'),
    q(M, 'Jazz', 4, 'QCM', 'Quel trompettiste a enregistré l\'album « Kind of Blue » (1959) ?', 'Miles Davis', 'Louis Armstrong', 'Chet Baker', 'Dizzy Gillespie',
      'L\'album de jazz le plus vendu de l\'histoire.', '',
      'Il a été enregistré presque sans répétition : les musiciens découvraient les thèmes en studio. La plupart des morceaux ont été gardés dès la première prise.'),
    q(M, 'Chronologie', 4, 'ORDRE', 'Remettez ces supports de musique dans l\'ordre d\'apparition.', 'Disque vinyle 33 tours | Cassette audio | CD | MP3', 'Du plus ancien au plus récent', '', '',
      '1948, 1963, 1982, années 1990.', '',
      'Le vinyle a fait un retour spectaculaire : depuis quelques années, il se vend de nouveau plus de vinyles que de CD dans plusieurs pays.'),
    q(M, 'Classique', 5, 'QCM', 'Quel compositeur a écrit « Le Sacre du printemps », dont la création en 1913 a déclenché une émeute ?', 'Igor Stravinsky', 'Claude Debussy', 'Serge Prokofiev', 'Erik Satie',
      'Créé au théâtre des Champs-Élysées à Paris par les Ballets russes.', '',
      'Le public a sifflé, crié et s\'est battu dans la salle. Les danseurs n\'entendaient plus l\'orchestre ; le chorégraphe Nijinski leur criait les temps depuis les coulisses.'),

    // ---------------- SPORT ----------------
    q(SP, 'Football', 1, 'QCM', 'Quel joueur a marqué deux buts de la tête en finale de la Coupe du monde 1998 ?', 'Zinédine Zidane', 'Emmanuel Petit', 'Thierry Henry', 'Lilian Thuram',
      'France-Brésil 3-0 au Stade de France, le 12 juillet 1998. Emmanuel Petit a marqué le troisième.', '',
      'Thuram, lui, avait marqué ses deux seuls buts en sélection en demi-finale contre la Croatie.'),
    q(SP, 'JO', 1, 'QCM', 'Combien d\'anneaux compte le drapeau olympique ?', '5', '4', '6', '7',
      'Ils représentent l\'union des cinq continents habités.', '',
      'Pierre de Coubertin l\'a dessiné en 1913. Les six couleurs (avec le fond blanc) permettaient de retrouver celles de tous les drapeaux nationaux de l\'époque.'),
    q(SP, 'Tennis', 2, 'QCM', 'Sur quelle surface se joue le tournoi de Wimbledon ?', 'Le gazon', 'La terre battue', 'Le dur', 'La moquette',
      'C\'est le seul tournoi du Grand Chelem encore sur gazon.', '',
      'Le code vestimentaire y impose une tenue presque entièrement blanche. Les fraises à la crème sont la tradition : on en sert plus de 2 tonnes par jour.'),
    q(SP, 'Cyclisme', 2, 'QCM', 'Quel maillot porte le meilleur grimpeur du Tour de France ?', 'Le maillot à pois', 'Le maillot vert', 'Le maillot blanc', 'Le maillot jaune',
      'Blanc à pois rouges, créé en 1975 pour un sponsor de chocolat.', '',
      'Le maillot vert est celui du classement par points, le blanc celui du meilleur jeune. Le jaune viendrait de la couleur du journal « L\'Auto », organisateur du Tour.'),
    q(SP, 'Rugby', 2, 'QCM', 'Comment s\'appelle la mêlée où les joueurs se lient pour pousser au rugby ?', 'La mêlée ordonnée', 'La touche', 'Le maul', 'Le ruck',
      'Huit joueurs de chaque équipe s\'y affrontent pour remettre le ballon en jeu après une faute légère.', '',
      'Un pilier peut subir une pression de plus d\'une tonne au moment de l\'impact. C\'est pour ça que les règles d\'engagement sont très codifiées.'),
    q(SP, 'Athlétisme', 2, 'VF', 'Au saut en hauteur, on peut franchir la barre en sautant sur le dos.', 'Vrai', '', '', '',
      'Vrai : c\'est le « Fosbury flop », popularisé par l\'Américain Dick Fosbury aux JO de 1968.', '',
      'Avant lui, on sautait en ciseaux ou en rouleau ventral. Le flop n\'a été possible qu\'avec l\'arrivée des tapis de réception épais.'),
    q(SP, 'Football', 3, 'QCM', 'Quel club français a remporté la Ligue des champions en 1993 ?', 'L\'Olympique de Marseille', 'Le Paris Saint-Germain', 'Monaco', 'Bordeaux',
      'Victoire 1-0 contre le Milan AC, but de la tête de Basile Boli.', '',
      'L\'OM a été privé de son titre de champion de France 1993 (affaire VA-OM), mais garde sa Ligue des champions. « À jamais les premiers ! »'),
    q(SP, 'JO', 3, 'QCM', 'Quel athlète américain a remporté 4 médailles d\'or aux JO de Berlin en 1936 ?', 'Jesse Owens', 'Carl Lewis', 'Jim Thorpe', 'Mark Spitz',
      '100 m, 200 m, longueur et relais 4 × 100 m, sous les yeux d\'Hitler.', '',
      'Selon la légende, le sauteur allemand Luz Long, son rival en longueur, lui aurait donné un conseil pendant le concours. Ils sont restés amis par lettres.'),
    q(SP, 'Combat', 3, 'QCM', 'Quel boxeur disait : « Je vole comme le papillon, je pique comme l\'abeille » ?', 'Mohamed Ali', 'Mike Tyson', 'George Foreman', 'Joe Frazier',
      'Triple champion du monde des poids lourds, né Cassius Clay.', '',
      'En 1974, à Kinshasa, il a battu George Foreman lors du « Rumble in the Jungle ». Il a allumé la vasque olympique à Atlanta en 1996.'),
    q(SP, 'Basket', 3, 'ESTIMATION', 'Combien mesure Victor Wembanyama (en cm) ?', '224', 'cm', '5', '',
      'Environ 2,24 m, avec une envergure de près de 2,40 m.', 'Plus de 2,20 m.',
      'Premier choix de la draft NBA 2023, il a été élu meilleur débutant (rookie of the year) en 2024 à l\'unanimité.'),
    q(SP, 'Voile', 4, 'QCM', 'Quelle course à la voile en solitaire fait le tour du monde sans escale ni assistance ?', 'Le Vendée Globe', 'La Route du Rhum', 'La Transat Jacques Vabre', 'La Solitaire du Figaro',
      'Départ et arrivée aux Sables-d\'Olonne, tous les quatre ans.', '',
      'On le surnomme « l\'Everest des mers ». Moins de 200 marins l\'ont terminé depuis sa création en 1989.'),
    q(SP, 'Golf', 4, 'QCM', 'Au golf, comment appelle-t-on un trou réussi en deux coups de moins que le par ?', 'Un eagle', 'Un birdie', 'Un albatros', 'Un bogey',
      'Birdie = 1 sous le par, eagle = 2, albatros = 3. Le bogey, lui, est un coup au-dessus.', '',
      'Le « condor », 4 coups sous le par, est rarissime : un trou en un sur un par 5. Il n\'y en a que quelques-uns de recensés.'),
    q(SP, 'Tennis', 4, 'QCM', 'Quelle joueuse française a remporté Wimbledon en 2013 ?', 'Marion Bartoli', 'Amélie Mauresmo', 'Mary Pierce', 'Caroline Garcia',
      'Elle a battu Sabine Lisicki en finale sans perdre un set de tout le tournoi.', '',
      'Elle a annoncé sa retraite à peine six semaines plus tard, à 28 ans. Son père, médecin, l\'avait entraînée avec des méthodes très originales.'),
    q(SP, 'Records', 5, 'QCM', 'Qui a été le premier homme à courir un marathon en moins de 2 heures, en 2019 (hors compétition officielle) ?', 'Eliud Kipchoge', 'Kenenisa Bekele', 'Haile Gebreselassie', 'Kelvin Kiptum',
      'À Vienne, en 1 h 59 min 40 s, avec des lièvres qui se relayaient.', '',
      'Le record n\'est pas homologué à cause des conditions spéciales (lièvres, voiture ouvreuse projetant un laser). Le record officiel, 2 h 00 min 35 s, a été établi par Kelvin Kiptum à Chicago en 2023.'),
    q(SP, 'Rugby', 5, 'QCM', 'En quelle année la France a-t-elle joué sa première finale de Coupe du monde de rugby ?', '1987', '1991', '1999', '2011',
      'Défaite contre la Nouvelle-Zélande en finale de la toute première Coupe du monde.', '',
      'La France a perdu ses trois finales (1987, 1999, 2011). En 2011, elle ne s\'était inclinée que 8 à 7 face aux All Blacks.'),

    // ---------------- ARTS & LITTÉRATURE ----------------
    q(A, 'Littérature', 1, 'QCM', 'Quel écrivain a créé le personnage de Gavroche ?', 'Victor Hugo', 'Émile Zola', 'Alphonse Daudet', 'Honoré de Balzac',
      'Le petit gamin de Paris des « Misérables » (1862), qui meurt sur une barricade.', '',
      '« Je suis tombé par terre, c\'est la faute à Voltaire… » : c\'est la chanson qu\'il chante sous les balles.'),
    q(A, 'Bande dessinée', 1, 'QCM', 'Comment s\'appelle le druide d\'Astérix ?', 'Panoramix', 'Abraracourcix', 'Assurancetourix', 'Idéfix',
      'Il prépare la potion magique qui rend invincible.', '',
      'Obélix est tombé dans la marmite quand il était petit : c\'est pour ça qu\'il n\'a pas le droit d\'en reprendre.'),
    q(A, 'Peinture', 2, 'QCM', 'Quel peintre espagnol est considéré comme le fondateur du cubisme avec Georges Braque ?', 'Pablo Picasso', 'Salvador Dalí', 'Joan Miró', 'Francisco de Goya',
      '« Les Demoiselles d\'Avignon » (1907) est souvent vu comme le point de départ du cubisme.', '',
      'Picasso a été brièvement soupçonné du vol de la Joconde en 1911 : il avait acheté des statuettes volées au Louvre, sans le savoir, dit-il.'),
    q(A, 'Littérature', 2, 'QCM', 'Quel héros de Jules Verne commande le sous-marin Nautilus ?', 'Le capitaine Nemo', 'Phileas Fogg', 'Michel Strogoff', 'Robur le Conquérant',
      'Dans « Vingt Mille Lieues sous les mers » (1870). « Nemo » veut dire « personne » en latin.', '',
      'Le premier sous-marin nucléaire de l\'histoire, lancé par les Américains en 1954, a été baptisé USS Nautilus en hommage.'),
    q(A, 'Architecture', 2, 'VF', 'Le château de Versailles a d\'abord été un pavillon de chasse.', 'Vrai', '', '', '',
      'Vrai : Louis XIII y fait construire un petit relais de chasse en 1623. Louis XIV le transforme en palais.', '',
      'La galerie des Glaces compte 357 miroirs. À l\'époque, le secret de fabrication des grands miroirs appartenait à Venise, et Colbert a débauché des artisans vénitiens.'),
    q(A, 'Littérature', 2, 'QCM', 'Dans quel roman d\'Alexandre Dumas trouve-t-on Edmond Dantès ?', 'Le Comte de Monte-Cristo', 'Les Trois Mousquetaires', 'La Reine Margot', 'Vingt ans après',
      'Emprisonné à tort au château d\'If, il s\'évade et revient se venger, riche et méconnaissable.', '',
      'Dumas s\'est inspiré d\'un fait divers réel : l\'histoire du cordonnier François Picaud, emprisonné sur dénonciation au début du XIXe siècle.'),
    q(A, 'Sculpture', 3, 'QCM', 'Quel sculpteur a réalisé « La Petite Danseuse de quatorze ans », à l\'origine en cire ?', 'Edgar Degas', 'Auguste Rodin', 'Camille Claudel', 'Aristide Maillol',
      'Présentée en 1881 avec un vrai tutu et de vrais cheveux, elle a choqué le public.', '',
      'Degas n\'a exposé qu\'une seule sculpture de son vivant : celle-ci. Les bronzes que l\'on voit aujourd\'hui ont été fondus après sa mort.'),
    q(A, 'Poésie', 3, 'QCM', 'Quel poète a écrit « Demain, dès l\'aube… » en souvenir de sa fille Léopoldine ?', 'Victor Hugo', 'Alfred de Musset', 'Alphonse de Lamartine', 'Paul Verlaine',
      'Léopoldine s\'est noyée dans la Seine à Villequier en 1843. Le poème figure dans « Les Contemplations » (1856).', '',
      'Hugo a appris sa mort par hasard, en lisant un journal dans un café de Rochefort, pendant un voyage.'),
    q(A, 'Musées', 3, 'QCM', 'Quel musée parisien est installé dans une ancienne gare ?', 'Le musée d\'Orsay', 'Le Centre Pompidou', 'Le Petit Palais', 'Le musée Rodin',
      'La gare d\'Orsay a été construite pour l\'Exposition universelle de 1900 ; le musée a ouvert en 1986.', '',
      'Il abrite la plus grande collection de tableaux impressionnistes au monde. La grande horloge de la gare est toujours là.'),
    q(A, 'Littérature', 3, 'QCM', 'Qui a écrit « Les Liaisons dangereuses » (1782) ?', 'Choderlos de Laclos', 'Voltaire', 'Marivaux', 'Beaumarchais',
      'Un roman épistolaire : toute l\'histoire est racontée par des lettres entre les personnages.', '',
      'Laclos était officier d\'artillerie. On lui doit aussi une invention : le boulet creux explosif.'),
    q(A, 'Bande dessinée', 3, 'QCM', 'Dans quel pays est né Lucky Luke, « l\'homme qui tire plus vite que son ombre » ?', 'En Belgique', 'En France', 'Aux États-Unis', 'En Suisse',
      'Créé en 1946 par le dessinateur belge Morris, puis scénarisé par René Goscinny.', '',
      'En 1983, Lucky Luke a arrêté de fumer : sa cigarette a été remplacée par un brin d\'herbe, ce qui lui a valu une récompense de l\'OMS.'),
    q(A, 'Peinture', 4, 'QCM', 'Quel peintre a représenté plus de 250 fois les nymphéas de son jardin de Giverny ?', 'Claude Monet', 'Auguste Renoir', 'Alfred Sisley', 'Berthe Morisot',
      'Il y a vécu plus de 40 ans, jusqu\'à sa mort en 1926. Le jardin se visite toujours.', '',
      'Atteint de cataracte, il voyait les couleurs de plus en plus jaunes et rouges : ses derniers tableaux sont presque abstraits.'),
    q(A, 'Littérature', 4, 'VF', 'Victor Hugo a écrit une grande partie de son œuvre en exil, sur une île anglo-normande.', 'Vrai', '', '', '',
      'Vrai : opposant à Napoléon III, il a vécu à Jersey puis à Guernesey de 1852 à 1870.', '',
      'Il a écrit « Les Misérables » à Guernesey, dans sa maison de Hauteville House, aujourd\'hui propriété de la Ville de Paris.'),
    q(A, 'Architecture', 5, 'QCM', 'Quel architecte suisse a conçu la Cité radieuse de Marseille ?', 'Le Corbusier', 'Jean Nouvel', 'Auguste Perret', 'Renzo Piano',
      'Inaugurée en 1952, elle est classée au patrimoine mondial de l\'Unesco avec d\'autres de ses œuvres.', '',
      'Le bâtiment contient une rue commerçante intérieure, un hôtel et une école sur le toit. Les Marseillais l\'appelaient « la maison du fada ».'),
    q(A, 'Littérature', 5, 'QCM', 'Quelle romancière a écrit « Bonjour tristesse » à 18 ans ?', 'Françoise Sagan', 'Marguerite Duras', 'Simone de Beauvoir', 'Colette',
      'Paru en 1954, ce premier roman a été un succès mondial.', '',
      'Son pseudonyme vient d\'un personnage de Proust, la princesse de Sagan. Son vrai nom était Françoise Quoirez.'),

    // ---------------- GASTRONOMIE ----------------
    q(GA, 'Cuisine', 1, 'QCM', 'Quel est l\'ingrédient principal d\'une omelette ?', 'Les œufs', 'La farine', 'Le lait', 'Le fromage',
      'Battus puis cuits à la poêle, souvent pliés en deux.', '',
      'L\'omelette de la Mère Poulard, au Mont-Saint-Michel, est célèbre depuis la fin du XIXe siècle : les œufs y sont battus longuement au fouet en rythme.'),
    q(GA, 'Desserts', 1, 'QCM', 'Quel dessert est composé de choux, de crème pâtissière et de caramel, monté en pyramide ?', 'La pièce montée (croquembouche)', 'Le paris-brest', 'La religieuse', 'Le saint-honoré',
      'Le dessert traditionnel des mariages et des baptêmes en France.', '',
      'Le pâtissier Antonin Carême, au début du XIXe siècle, en a fait de véritables architectures, inspirées des temples et des ruines antiques.'),
    q(GA, 'Régions', 2, 'QCM', 'De quelle région vient le kouign-amann ?', 'La Bretagne', 'L\'Alsace', 'La Normandie', 'Le Pays basque',
      'Son nom signifie « gâteau au beurre » en breton. Il est né à Douarnenez vers 1860.', '',
      'La légende dit qu\'un boulanger, en manque de farine, aurait improvisé avec beaucoup de beurre et de sucre. Il contient à peu près autant de beurre que de pâte.'),
    q(GA, 'Fromages', 2, 'QCM', 'Quel fromage est traditionnellement utilisé dans la raclette ?', 'La raclette (fromage à raclette)', 'Le comté', 'Le reblochon', 'L\'emmental',
      'Un fromage au lait de vache de Savoie ou du Valais suisse, qui fond bien.', '',
      'Le nom vient du verbe « racler » : on raclait autrefois une demi-meule chauffée au feu de bois directement sur les pommes de terre.'),
    q(GA, 'Monde', 2, 'VF', 'Le croissant est d\'origine autrichienne.', 'Vrai', '', '', '',
      'Vrai : il descend du « kipferl » viennois, introduit à Paris au XIXe siècle par une boulangerie viennoise.', '',
      'La pâte feuilletée levée du croissant moderne est en revanche une invention française du début du XXe siècle.'),
    q(GA, 'Cuisine', 2, 'QCM', 'Quelle sauce est à base de beurre, de jaunes d\'œufs, d\'échalote et d\'estragon ?', 'La béarnaise', 'La hollandaise', 'La béchamel', 'La mayonnaise',
      'Une sauce émulsionnée chaude, idéale avec une pièce de bœuf grillée.', '',
      'Malgré son nom, elle aurait été inventée près de Paris, au pavillon Henri IV de Saint-Germain-en-Laye, en hommage au roi né à Pau.'),
    q(GA, 'Boissons', 3, 'QCM', 'De quel pays est originaire le thé ?', 'La Chine', 'L\'Inde', 'Le Japon', 'Le Royaume-Uni',
      'La légende raconte qu\'un empereur chinois l\'aurait découvert vers 2700 av. J.-C. quand une feuille est tombée dans son eau chaude.', '',
      'Les Britanniques ont développé la culture du thé en Inde au XIXe siècle pour ne plus dépendre de la Chine.'),
    q(GA, 'Fromages', 3, 'ESTIMATION', 'Combien de litres de lait faut-il environ pour fabriquer une meule de comté (environ 40 kg) ?', '450', 'litres', '60', '',
      'Environ 11 litres de lait par kilo de fromage, soit plus de 400 litres par meule.', '',
      'Le lait doit être transformé dans les 24 heures après la traite. Une meule est affinée au minimum 4 mois, parfois plus de 2 ans.'),
    q(GA, 'Desserts', 3, 'QCM', 'Quel gâteau en forme de roue a été créé pour célébrer une course cycliste ?', 'Le paris-brest', 'Le saint-honoré', 'Le mont-blanc', 'Le fraisier',
      'Créé en 1910 pour la course Paris-Brest-Paris, garni de crème pralinée.', '',
      'Il a été inventé par Louis Durand, pâtissier à Maisons-Laffitte, sur une route empruntée par la course. Sa boutique existe toujours.'),
    q(GA, 'Monde', 3, 'QCM', 'Quel plat japonais est composé de nouilles dans un bouillon ?', 'Les ramen', 'Les sushis', 'Les tempuras', 'Les gyozas',
      'Venus de Chine, ils sont devenus un plat national au Japon, décliné dans chaque région.', '',
      'Les nouilles instantanées ont été inventées au Japon en 1958 par Momofuku Andō. Un musée leur est consacré à Yokohama.'),
    q(GA, 'Vins', 4, 'QCM', 'Quel cépage est roi en Bourgogne pour les vins rouges ?', 'Le pinot noir', 'Le cabernet sauvignon', 'Le merlot', 'La syrah',
      'Il donne notamment la Romanée-Conti, l\'un des vins les plus chers du monde.', '',
      'En Bourgogne, le chardonnay règne sur les blancs. Le cabernet et le merlot sont plutôt les cépages du Bordelais.'),
    q(GA, 'Épices', 4, 'QCM', 'De quelle plante vient la cannelle ?', 'De l\'écorce d\'un arbre', 'D\'une graine', 'D\'une racine', 'D\'une fleur séchée',
      'On récolte l\'écorce intérieure du cannelier, qui s\'enroule en séchant.', '',
      'La meilleure cannelle vient du Sri Lanka. Au Moyen Âge, elle valait si cher qu\'on la donnait en cadeau aux rois.'),
    q(GA, 'Traditions', 4, 'VF', 'Le repas gastronomique des Français est inscrit au patrimoine immatériel de l\'Unesco.', 'Vrai', '', '', '',
      'Vrai, depuis 2010 : pour ses rituels (bien choisir les plats, accorder mets et vins, dresser la table…).', '',
      'La baguette de pain l\'a rejoint en 2022 : « savoir-faire artisanal et culture de la baguette de pain ».'),
    q(GA, 'Cuisine', 5, 'QCM', 'Quel chef lyonnais a été sacré « cuisinier du siècle » par le guide Gault et Millau en 1989 ?', 'Paul Bocuse', 'Joël Robuchon', 'Alain Ducasse', 'Bernard Loiseau',
      'Son restaurant de Collonges-au-Mont-d\'Or a gardé trois étoiles Michelin de 1965 à 2020.', '',
      'Joël Robuchon a reçu le même titre l\'année suivante. Bocuse a aussi créé le Bocuse d\'or, un concours mondial de cuisine, en 1987.'),
    q(GA, 'Fromages', 5, 'QCM', 'Quel fromage est affiné dans les caves de Roquefort grâce à un champignon ?', 'Le roquefort, grâce au Penicillium roqueforti', 'Le brie, grâce au Penicillium camemberti', 'Le munster, grâce au lin', 'Le cantal, grâce à la bactérie lactique',
      'Ce champignon naturellement présent dans les caves crée les veines bleues.', '',
      'Les caves s\'appuient sur des failles naturelles, les « fleurines », qui assurent une ventilation et une humidité constantes.'),

    // ---------------- DIVERS ----------------
    q(D, 'Langue française', 1, 'QCM', 'Combien de voyelles compte l\'alphabet français (en comptant le y) ?', '6', '5', '7', '4',
      'A, E, I, O, U et Y.', '',
      'Le français compte en revanche environ 16 sons voyelles différents à l\'oral : an, on, in, eu, ou…'),
    q(D, 'Jeux', 1, 'QCM', 'Combien de points vaut la lettre Z au Scrabble en français ?', '10', '8', '5', '12',
      'Comme le K, le W, le X et le Y.', '',
      'Le Scrabble a été inventé par un architecte américain au chômage, Alfred Butts, pendant la crise des années 1930.'),
    q(D, 'Tech', 2, 'QCM', 'Que signifie le « www » des adresses Internet ?', 'World Wide Web', 'World Web Wide', 'Wide World Web', 'Web World Wide',
      'La « toile d\'araignée mondiale », inventée par Tim Berners-Lee au CERN en 1989.', '',
      'Le tout premier site web, info.cern.ch, est toujours en ligne. Il explique… ce qu\'est le Web.'),
    q(D, 'Calendrier', 2, 'QCM', 'Quel mois de l\'année compte le moins de jours ?', 'Février', 'Avril', 'Juin', 'Novembre',
      '28 jours, 29 les années bissextiles.', '',
      'En 1712, la Suède a eu un 30 février pour rattraper une erreur dans son passage au calendrier grégorien.'),
    q(D, 'Monnaies', 2, 'QCM', 'En quelle année l\'euro a-t-il remplacé le franc dans les porte-monnaie ?', '2002', '1999', '2000', '2004',
      'Les pièces et billets sont arrivés le 1er janvier 2002. L\'euro existait déjà pour les banques depuis 1999.', '',
      '1 euro valait 6,55957 francs. Beaucoup de Français ont longtemps continué à convertir mentalement les prix.'),
    q(D, 'Langue française', 2, 'VF', 'Le mot « amour » est masculin au singulier et peut être féminin au pluriel.', 'Vrai', '', '', '',
      'Vrai, dans la langue littéraire : « de belles amours ». Comme « délice » et « orgue ».', '',
      'On dit « un orgue » mais « les grandes orgues » quand on parle de l\'instrument d\'une église. Le français aime les exceptions.'),
    q(D, 'Tech', 3, 'QCM', 'Quel est le nom du premier ordinateur personnel d\'Apple (1976) ?', 'L\'Apple I', 'Le Macintosh', 'Le Lisa', 'L\'iMac',
      'Assemblé à la main par Steve Wozniak, vendu 666,66 dollars.', '',
      'On raconte que les premiers ont été fabriqués dans le garage des parents de Steve Jobs. Un Apple I en état de marche se vend aujourd\'hui plusieurs centaines de milliers de dollars.'),
    q(D, 'Jeux', 3, 'QCM', 'Dans quel pays le Monopoly a-t-il été commercialisé pour la première fois ?', 'Aux États-Unis', 'Au Royaume-Uni', 'En France', 'En Allemagne',
      'Par Parker Brothers en 1935, avec les rues d\'Atlantic City.', '',
      'Il s\'inspire d\'un jeu inventé en 1903 par Elizabeth Magie, « The Landlord\'s Game », qui voulait… dénoncer les méfaits des monopoles.'),
    q(D, 'Couleurs', 3, 'QCM', 'Quelles sont les trois couleurs primaires de la lumière (écrans) ?', 'Rouge, vert, bleu', 'Rouge, jaune, bleu', 'Cyan, magenta, jaune', 'Rouge, orange, violet',
      'Le « RVB » : en les mélangeant à pleine puissance, on obtient du blanc.', '',
      'Pour la peinture et l\'imprimerie, c\'est l\'inverse : cyan, magenta et jaune, qui mélangés donnent presque du noir.'),
    q(D, 'Maths', 3, 'ESTIMATION', 'Combien vaut le nombre pi arrondi au centième ?', '3.14', '', '0', '',
      '3,14159… Ses décimales ne s\'arrêtent jamais et ne se répètent jamais.', '',
      'Le 14 mars (3/14 en notation américaine) est la journée internationale de pi. C\'est aussi l\'anniversaire d\'Albert Einstein.'),
    q(D, 'Langue française', 4, 'QCM', 'Quel est le pluriel de « un chou » ?', 'Des choux', 'Des chous', 'Des choues', 'Des chouxs',
      'Il fait partie des sept noms en -ou qui prennent un x : bijou, caillou, chou, genou, hibou, joujou, pou.', '',
      'Les autres mots en -ou prennent un s : des clous, des fous, des trous. Moyen mnémotechnique : « Viens mon chou, mon bijou, sur mes genoux… »'),
    q(D, 'Calendrier', 4, 'QCM', 'Quel pape a donné son nom au calendrier utilisé aujourd\'hui ?', 'Grégoire XIII', 'Jules II', 'Jean-Paul II', 'Pie VII',
      'Le calendrier grégorien a été adopté en 1582 pour corriger le décalage du calendrier julien.', '',
      'Pour rattraper le retard, on a supprimé 10 jours : en France, on est passé directement du 9 au 20 décembre 1582.'),
    q(D, 'Tech', 4, 'QCM', 'Que veut dire l\'acronyme « Wi-Fi » ?', 'Rien de précis : c\'est un nom de marque', 'Wireless Fidelity', 'Wide Fiber', 'Wireless Field',
      'Le nom a été inventé par une agence de marketing en 1999, en clin d\'œil au « Hi-Fi ».', '',
      '« Wireless Fidelity » a été ajouté après coup comme slogan, puis abandonné. Question piège pour les connaisseurs !'),
    q(D, 'Maths', 5, 'QCM', 'Combien de faces a un icosaèdre ?', '20', '12', '8', '30',
      'Du grec « eikosi », vingt. C\'est la forme du dé à 20 faces des jeux de rôle.', '',
      'Beaucoup de virus, dont celui de la varicelle, ont une coque en forme d\'icosaèdre : c\'est une forme très économique en matériau.'),
    q(D, 'Jeux', 5, 'QCM', 'Aux échecs, comment appelle-t-on le coup spécial où le roi et la tour bougent en même temps ?', 'Le roque', 'L\'échec et mat', 'La prise en passant', 'Le pat',
      'Le roi se déplace de deux cases vers la tour, qui passe de l\'autre côté du roi.', '',
      'Condition : ni le roi ni la tour ne doivent avoir bougé, et le roi ne doit pas être en échec ni traverser une case attaquée.'),
  ];
}
