/**
 * Banque de questions — thème « Actualité » : faits marquants de 2024 à début 2026 (sport, politique, culture, société).
 * a(année, difficulté, type, question, réponse, choix2, choix3, choix4, explication, anecdote MJ)
 * Rédigée en septembre 2026 à partir d'événements vérifiés jusqu'au printemps 2026 : à rafraîchir de temps en temps
 * (désactive une question en mettant « non » dans la colonne Actif si elle a vieilli).
 */
function banqueActualite_() {
  const T = 'Actualité';
  const a = (annee, diff, type, texte, rep, c2, c3, c4, expl, anec) =>
    [T, String(annee), diff, type, texte, rep, c2 || '', c3 || '', c4 || '', expl || '', 'Actualité ' + annee, '', '', '', annee, anec || ''];
  return [
    // ---------------- 2024 ----------------
    a(2024, 1, 'QCM', 'Où a été allumée la vasque olympique des Jeux de Paris 2024 ?', 'Dans le jardin des Tuileries, sous un ballon', 'Au sommet de la tour Eiffel', 'Au Stade de France', 'Sur le parvis de Notre-Dame',
      'La vasque, accrochée à un ballon inspiré de celui des frères Montgolfier, s\'élevait chaque soir au-dessus des Tuileries.',
      'Elle a été allumée par Marie-José Pérec et Teddy Riner. La « flamme » était en fait de la lumière et de la vapeur d\'eau : une première sans combustion. Des foules immenses sont venues la voir s\'élever chaque soir.'),
    a(2024, 1, 'QCM', 'Quel nageur français a remporté 4 médailles d\'or aux JO de Paris 2024 ?', 'Léon Marchand', 'Florent Manaudou', 'Maxime Grousset', 'Yannick Agnel',
      '200 m papillon, 200 m brasse, 200 m 4 nages et 400 m 4 nages, plus un bronze en relais.',
      'Il a gagné le 200 m papillon et le 200 m brasse le même soir, à deux heures d\'intervalle. La foule de La Défense Arena chantait la Marseillaise a cappella à chaque podium.'),
    a(2024, 1, 'QCM', 'Quelle chanteuse a clôturé la cérémonie d\'ouverture des JO de Paris 2024 depuis la tour Eiffel ?', 'Céline Dion', 'Lady Gaga', 'Aya Nakamura', 'Mylène Farmer',
      'Elle a interprété « L\'Hymne à l\'amour » d\'Édith Piaf, son premier concert depuis l\'annonce de sa maladie.',
      'Atteinte du syndrome de la personne raide, elle n\'était pas montée sur scène depuis 2020. Lady Gaga, elle, avait chanté « Mon truc en plumes » de Zizi Jeanmaire.'),
    a(2024, 2, 'ESTIMATION', 'Combien de médailles d\'or la France a-t-elle remporté aux JO de Paris 2024 ?', '16', 'médailles d\'or', '2', '',
      '16 médailles d\'or et 64 médailles au total : le meilleur bilan français depuis 1900.',
      'La France a fini 5e au classement des médailles. Les États-Unis et la Chine ont terminé à égalité avec 40 titres chacun ; les Américains sont passés devant grâce aux médailles d\'argent.'),
    a(2024, 2, 'QCM', 'En individuel à Paris 2024, Teddy Riner a décroché son… ?', '3e titre olympique', '1er titre olympique', '2e titre olympique', '4e titre olympique',
      'Après Londres 2012 et Rio 2016. Il a ajouté un titre par équipes quelques jours plus tard.',
      'En finale par équipes contre le Japon, c\'est lui qui a été tiré au sort pour le combat décisif… et il l\'a gagné en quelques secondes.'),
    a(2024, 1, 'QCM', 'Quel pays a remporté l\'Euro 2024 de football en Allemagne ?', 'L\'Espagne', 'L\'Angleterre', 'La France', 'L\'Allemagne',
      'L\'Espagne a battu l\'Angleterre 2-1 en finale à Berlin : son 4e titre, un record.',
      'Lamine Yamal a fêté ses 17 ans la veille de la finale. Il est devenu le plus jeune buteur de l\'histoire de l\'Euro, contre la France en demi-finale.'),
    a(2024, 1, 'QCM', 'Quand la cathédrale Notre-Dame de Paris a-t-elle rouvert après l\'incendie de 2019 ?', 'En décembre 2024', 'En avril 2024', 'En juillet 2025', 'Elle n\'a pas encore rouvert',
      'Réouverture les 7 et 8 décembre 2024, un peu plus de 5 ans après l\'incendie du 15 avril 2019.',
      'Le chantier a mobilisé environ 2 000 artisans. Emmanuel Macron avait promis une reconstruction en 5 ans : pari (presque) tenu.'),
    a(2024, 2, 'QCM', 'Qui a été nommé Premier ministre en janvier 2024, devenant le plus jeune de la Ve République ?', 'Gabriel Attal', 'Jordan Bardella', 'Sébastien Lecornu', 'Laurent Wauquiez',
      'Il avait 34 ans. Il est resté à Matignon jusqu\'en septembre 2024.',
      'Il battait le record de Laurent Fabius, nommé à 37 ans en 1984.'),
    a(2024, 2, 'QCM', 'Quel événement a suivi la dissolution de l\'Assemblée nationale annoncée par Emmanuel Macron le 9 juin 2024 ?', 'Des élections législatives anticipées', 'Une élection présidentielle', 'Un référendum', 'Des élections européennes',
      'Les législatives ont eu lieu les 30 juin et 7 juillet 2024, sans qu\'aucun camp n\'obtienne la majorité.',
      'La dissolution a été annoncée le soir même des élections européennes. Le Nouveau Front populaire est arrivé en tête en sièges, devant le camp présidentiel et le Rassemblement national.'),
    a(2024, 3, 'QCM', 'Quel Premier ministre a été renversé par une motion de censure le 4 décembre 2024, une première depuis 1962 ?', 'Michel Barnier', 'Gabriel Attal', 'Élisabeth Borne', 'François Bayrou',
      'Nommé en septembre 2024, il est resté trois mois à Matignon, le plus court passage de la Ve République à l\'époque.',
      'La dernière censure réussie visait Georges Pompidou, en octobre 1962. François Bayrou lui a succédé le 13 décembre 2024.'),
    a(2024, 1, 'QCM', 'Qui a remporté l\'élection présidentielle américaine de novembre 2024 ?', 'Donald Trump', 'Kamala Harris', 'Joe Biden', 'Ron DeSantis',
      'Il a battu Kamala Harris et a été investi le 20 janvier 2025 pour un second mandat, non consécutif au premier.',
      'Seul Grover Cleveland, à la fin du XIXe siècle, avait déjà fait deux mandats non consécutifs.'),
    a(2024, 2, 'QCM', 'Qui a remporté l\'Eurovision 2024 à Malmö ?', 'Nemo (Suisse)', 'Baby Lasagna (Croatie)', 'Slimane (France)', 'Käärijä (Finlande)',
      'Avec « The Code ». La France, représentée par Slimane et « Mon amour », a terminé 4e.',
      'Nemo est la première personne non binaire à gagner l\'Eurovision. C\'était la 3e victoire de la Suisse, qui avait gagné la toute première édition en 1956.'),
    a(2024, 2, 'QCM', 'Quel film français a été le plus vu en salle en 2024, avec plus de 10 millions d\'entrées ?', 'Un p\'tit truc en plus', 'Le Comte de Monte-Cristo', 'L\'Amour ouf', 'Monsieur Aznavour',
      'Le premier film réalisé par l\'humoriste Artus, tourné avec des acteurs en situation de handicap.',
      '« Le Comte de Monte-Cristo », avec Pierre Niney, a lui dépassé 9 millions d\'entrées : deux films français à ce niveau la même année, du jamais-vu depuis longtemps.'),
    a(2024, 2, 'QCM', 'Quel film a remporté la Palme d\'or à Cannes en 2024, puis l\'Oscar du meilleur film ?', 'Anora', 'Emilia Pérez', 'The Brutalist', 'Conclave',
      'Réalisé par l\'Américain Sean Baker, il a remporté 5 Oscars en mars 2025.',
      'Sean Baker a égalé le record de Walt Disney : 4 Oscars la même soirée pour une seule personne (film, réalisation, scénario, montage).'),
    a(2024, 3, 'QCM', 'Quel cyclone a ravagé Mayotte en décembre 2024 ?', 'Chido', 'Freddy', 'Belal', 'Garance',
      'Le 14 décembre 2024, le cyclone le plus violent à frapper l\'île depuis près d\'un siècle.',
      'Les rafales ont dépassé 200 km/h. Les bidonvilles de l\'île ont été presque entièrement détruits.'),
    a(2024, 3, 'QCM', 'Quel skipper a remporté le Vendée Globe 2024-2025 en battant le record de l\'épreuve ?', 'Charlie Dalin', 'Yoann Richomme', 'Thomas Ruyant', 'Armel Le Cléac\'h',
      'Arrivé en janvier 2025 aux Sables-d\'Olonne, en un peu moins de 65 jours.',
      'Il a pulvérisé de plus de 9 jours le record d\'Armel Le Cléac\'h (74 jours en 2017). Il était 2e de l\'édition précédente.'),
    a(2024, 3, 'VF', 'À cause des JO, le Tour de France 2024 ne s\'est pas terminé à Paris.', 'Vrai', '', '', '',
      'Vrai : il s\'est achevé à Nice, par un contre-la-montre, une première depuis 1905. Tadej Pogačar l\'a remporté.',
      'Le Tour était parti d\'Italie (Florence). Pogačar a aussi gagné le Giro la même année, un doublé que personne n\'avait réussi depuis Marco Pantani en 1998.'),
    a(2024, 4, 'QCM', 'Quelle organisation a reçu le prix Nobel de la paix 2024 ?', 'Nihon Hidankyo, association de survivants d\'Hiroshima et Nagasaki', 'Médecins sans frontières', 'L\'UNRWA', 'La Croix-Rouge',
      'Pour son combat en faveur d\'un monde sans armes nucléaires.',
      'Ces survivants de la bombe atomique s\'appellent les « hibakusha ». L\'association existe depuis 1956.'),
    a(2024, 3, 'QCM', 'Quel footballeur espagnol a remporté le Ballon d\'or 2024 ?', 'Rodri', 'Lamine Yamal', 'Dani Carvajal', 'Pedri',
      'Le milieu de Manchester City, champion d\'Europe avec l\'Espagne.',
      'Vinícius Júnior, donné favori, et le Real Madrid avaient boycotté la cérémonie en apprenant qu\'il ne gagnerait pas.'),

    // ---------------- 2025 ----------------
    a(2025, 1, 'QCM', 'Quel club a remporté sa première Ligue des champions en mai 2025 ?', 'Le Paris Saint-Germain', 'L\'Inter Milan', 'Arsenal', 'Le FC Barcelone',
      'Victoire 5-0 contre l\'Inter Milan à Munich, le plus large écart de l\'histoire en finale.',
      'Désiré Doué, 19 ans, a marqué deux fois en finale. Marseille reste le seul autre club français vainqueur (1993).'),
    a(2025, 1, 'QCM', 'Quel Français a remporté le Ballon d\'or 2025 ?', 'Ousmane Dembélé', 'Kylian Mbappé', 'Michael Olise', 'Désiré Doué',
      'Le joueur du PSG, champion d\'Europe, succède à Karim Benzema (2022) comme Ballon d\'or français.',
      'Il n\'y a eu que six Ballons d\'or français : Kopa, Platini (trois fois), Papin, Zidane, Benzema et Dembélé.'),
    a(2025, 1, 'QCM', 'Quel nom a choisi le pape élu en mai 2025 ?', 'Léon XIV', 'François II', 'Jean-Paul III', 'Pie XIII',
      'Robert Francis Prevost a été élu le 8 mai 2025, après la mort du pape François le 21 avril.',
      'C\'est le premier pape américain. Il a longtemps été missionnaire au Pérou, dont il a aussi la nationalité.'),
    a(2025, 2, 'QCM', 'De quel pays est originaire le pape Léon XIV ?', 'Des États-Unis', 'Du Pérou', 'D\'Italie', 'Des Philippines',
      'Né à Chicago en 1955. Il a aussi la nationalité péruvienne après des années de mission au Pérou.',
      'Son nom rend hommage à Léon XIII, le pape de la doctrine sociale de l\'Église à la fin du XIXe siècle.'),
    a(2025, 2, 'QCM', 'Quel trésor a été volé au Louvre le 19 octobre 2025 ?', 'Des bijoux de la couronne de France', 'La Joconde', 'La Vénus de Milo', 'Le Radeau de La Méduse',
      'Les voleurs sont entrés par une fenêtre de la galerie d\'Apollon à l\'aide d\'un monte-meubles, en quelques minutes seulement.',
      'Le casse a duré environ 7 minutes, en plein jour. La couronne de l\'impératrice Eugénie, abîmée, a été retrouvée près du musée, tombée pendant la fuite.'),
    a(2025, 2, 'QCM', 'Quel ancien président de la République a été incarcéré à la prison de la Santé en octobre 2025 ?', 'Nicolas Sarkozy', 'François Hollande', 'Jacques Chirac', 'Valéry Giscard d\'Estaing',
      'Condamné à 5 ans de prison dans l\'affaire du financement libyen, il a été le premier ex-président français incarcéré.',
      'Il est resté environ trois semaines en détention avant d\'être remis en liberté sous contrôle judiciaire en attendant son procès en appel.'),
    a(2025, 3, 'QCM', 'Qui a été nommé Premier ministre en septembre 2025, après la chute de François Bayrou ?', 'Sébastien Lecornu', 'Gérald Darmanin', 'Bruno Retailleau', 'Catherine Vautrin',
      'Ministre des Armées, il a été nommé le 9 septembre 2025. Il a démissionné le 6 octobre, puis a été reconduit quatre jours plus tard.',
      'Son premier gouvernement n\'a vécu qu\'environ 14 heures : le plus court de la Ve République.'),
    a(2025, 2, 'QCM', 'Qui est devenu chancelier d\'Allemagne en mai 2025 ?', 'Friedrich Merz', 'Olaf Scholz', 'Markus Söder', 'Robert Habeck',
      'Le chef de la CDU a succédé à Olaf Scholz après les élections anticipées de février 2025.',
      'Il n\'a été élu qu\'au second tour de vote au Bundestag : une première dans l\'histoire de l\'Allemagne d\'après-guerre.'),
    a(2025, 3, 'QCM', 'Qui a remporté la finale de Roland-Garros 2025, la plus longue de l\'histoire du tournoi ?', 'Carlos Alcaraz', 'Jannik Sinner', 'Novak Djokovic', 'Alexander Zverev',
      'Il a battu Jannik Sinner en 5 heures et 29 minutes, après avoir sauvé trois balles de match.',
      'Sinner a pris sa revanche un mois plus tard en finale de Wimbledon. Chez les femmes, Coco Gauff a gagné Roland-Garros face à Aryna Sabalenka.'),
    a(2025, 2, 'QCM', 'Qui a remporté le Tour de France 2025 ?', 'Tadej Pogačar', 'Jonas Vingegaard', 'Remco Evenepoel', 'Primož Roglič',
      'Son 4e Tour de France, devant Jonas Vingegaard.',
      'Chez les femmes, la Française Pauline Ferrand-Prévot a remporté le Tour de France Femmes, une victoire française qu\'on attendait depuis 1989.'),
    a(2025, 3, 'VF', 'L\'équipe de France de rugby a remporté le Tournoi des Six Nations 2025.', 'Vrai', '', '', '',
      'Vrai : grâce à une victoire contre l\'Écosse lors de la dernière journée, au Stade de France.',
      'Antoine Dupont s\'était blessé au genou pendant le tournoi. Les Bleus ont tout de même inscrit un nombre record d\'essais.'),
    a(2025, 3, 'QCM', 'Quel club a remporté la première Coupe du monde des clubs à 32 équipes, aux États-Unis en 2025 ?', 'Chelsea', 'Le Paris Saint-Germain', 'Le Real Madrid', 'Manchester City',
      'Chelsea a battu le PSG 3-0 en finale, près de New York.',
      'Donald Trump a remis le trophée… et est resté sur le podium pendant la célébration des joueurs.'),
    a(2025, 3, 'QCM', 'Qui a remporté l\'Eurovision 2025 à Bâle ?', 'JJ (Autriche)', 'KAJ (Suède)', 'Louane (France)', 'Käärijä (Finlande)',
      'Avec « Wasted Love », une chanson aux accents lyriques. L\'Eurovision 2026 s\'est donc tenue à Vienne.',
      'JJ est un contre-ténor, formé à l\'opéra. La France était représentée par Louane avec « Maman ».'),
    a(2025, 3, 'QCM', 'Quelle panne géante a touché l\'Espagne et le Portugal le 28 avril 2025 ?', 'Une panne d\'électricité générale', 'Une panne d\'Internet', 'Une panne des distributeurs de billets', 'Une panne des réseaux téléphoniques seulement',
      'Des dizaines de millions de personnes ont été privées de courant pendant plusieurs heures.',
      'Trains et métros se sont arrêtés, les feux de circulation se sont éteints. Le courant est revenu dans la nuit pour la plupart des foyers.'),
    a(2025, 2, 'QCM', 'Quelle figurine en peluche aux dents pointues a été l\'objet de toutes les convoitises en 2025 ?', 'Labubu', 'Stitch', 'Pikachu', 'Hello Kitty',
      'Créée par l\'artiste Kasing Lung et vendue par la marque chinoise Pop Mart, souvent dans des boîtes « surprise ».',
      'Des files d\'attente de plusieurs heures se sont formées devant les boutiques. Certains exemplaires rares se sont revendus plusieurs milliers d\'euros.'),
    a(2025, 3, 'QCM', 'Quel film d\'animation est devenu en 2025 le film le plus vu de l\'histoire de Netflix ?', 'KPop Demon Hunters', 'Vice-versa 2', 'Le Robot sauvage', 'Vaiana 2',
      'Des chanteuses de K-pop qui chassent les démons : sa chanson « Golden » a aussi cartonné.',
      'Il a dépassé « Red Notice ». Des séances « à chanter » ont même été organisées dans les cinémas américains.'),
    a(2025, 3, 'QCM', 'Quel groupe britannique s\'est reformé en 2025 pour une tournée mondiale, 16 ans après sa séparation ?', 'Oasis', 'Blur', 'The Police', 'Spice Girls',
      'Les frères Liam et Noel Gallagher, brouillés depuis 2009, ont repris la route ensemble.',
      'Des millions de fans ont fait la queue en ligne pour obtenir des billets. Le groupe s\'était séparé après une dispute en coulisses au festival Rock en Seine, à Saint-Cloud.'),
    a(2025, 4, 'QCM', 'Quel économiste français a reçu le prix Nobel d\'économie 2025 ?', 'Philippe Aghion', 'Thomas Piketty', 'Esther Duflo', 'Jean Tirole',
      'Avec Peter Howitt et Joel Mokyr, pour leurs travaux sur la croissance tirée par l\'innovation.',
      'Esther Duflo (2019) et Jean Tirole (2014) l\'avaient reçu avant lui. Le même mois, le Français Michel Devoret a aussi reçu le Nobel de physique.'),
    a(2025, 4, 'QCM', 'Qui a reçu le prix Nobel de la paix 2025 ?', 'María Corina Machado', 'Volodymyr Zelensky', 'Greta Thunberg', 'Donald Trump',
      'Figure de l\'opposition vénézuélienne, pour son combat en faveur de la démocratie.',
      'Elle vivait cachée au Venezuela au moment de l\'annonce.'),
    a(2025, 4, 'QCM', 'À quelle hauteur Armand Duplantis a-t-il porté le record du monde de saut à la perche aux Mondiaux de Tokyo 2025 ?', '6,30 m', '6,14 m', '6,20 m', '6,40 m',
      'Le Suédois a amélioré son propre record pour la 14e fois.',
      'Il bat le record centimètre par centimètre : chaque record lui rapporte une prime. Sergueï Bubka faisait pareil dans les années 1990.'),
    a(2025, 4, 'QCM', 'Quel pilote a remporté le championnat du monde de Formule 1 en 2025 ?', 'Lando Norris', 'Max Verstappen', 'Oscar Piastri', 'Charles Leclerc',
      'Le Britannique de McLaren a été sacré lors de la dernière course, à Abou Dhabi.',
      'Il a devancé Max Verstappen de seulement deux points, mettant fin à 4 ans de domination du Néerlandais.'),
    a(2025, 5, 'QCM', 'Quel écrivain hongrois a reçu le prix Nobel de littérature 2025 ?', 'László Krasznahorkai', 'Imre Kertész', 'Péter Esterházy', 'Magda Szabó',
      'Auteur de « Le Tango de Satan », connu pour ses phrases interminables.',
      'Imre Kertész, autre Hongrois, l\'avait reçu en 2002. Le cinéaste Béla Tarr a adapté plusieurs de ses romans, dont un film de plus de 7 heures.'),
    a(2025, 3, 'QCM', 'Quel film de Jafar Panahi a remporté la Palme d\'or 2025 ?', 'Un simple accident', 'L\'Agent secret', 'Valeur sentimentale', 'Sirat',
      'Le cinéaste iranien, longtemps interdit de tourner et de voyager, était présent à Cannes pour recevoir sa Palme.',
      'Il avait tourné le film clandestinement. Il avait déjà gagné la Caméra d\'or à Cannes en 1995 pour « Le Ballon blanc ».'),
    a(2025, 2, 'QCM', 'Quel célèbre rockeur britannique, « Prince des ténèbres », est mort en juillet 2025 ?', 'Ozzy Osbourne', 'Mick Jagger', 'Rod Stewart', 'Robert Plant',
      'Le chanteur de Black Sabbath est mort quelques semaines après un concert d\'adieu dans sa ville natale de Birmingham.',
      'Ce dernier concert, le 5 juillet 2025, réunissait le groupe d\'origine pour la première fois depuis 20 ans.'),

    // ---------------- 2026 ----------------
    a(2026, 1, 'QCM', 'Quels pays organisent la Coupe du monde de football 2026 ?', 'États-Unis, Canada et Mexique', 'États-Unis seuls', 'Maroc, Espagne et Portugal', 'Arabie saoudite',
      'Du 11 juin au 19 juillet 2026, la première Coupe du monde à 48 équipes.',
      'Le Mexique devient le premier pays à accueillir trois Coupes du monde (1970, 1986, 2026). La finale se joue près de New York.'),
    a(2026, 2, 'ESTIMATION', 'Combien d\'équipes participent à la Coupe du monde de football 2026 ?', '48', 'équipes', '0', '',
      '48 équipes, contre 32 depuis 1998 : 104 matchs au total.',
      'De nouveaux pays comme le Cap-Vert, la Jordanie, l\'Ouzbékistan ou Curaçao se sont qualifiés pour la première fois.'),
    a(2026, 2, 'QCM', 'Quelles villes italiennes ont organisé les Jeux olympiques d\'hiver de 2026 ?', 'Milan et Cortina d\'Ampezzo', 'Rome et Turin', 'Turin et Courmayeur', 'Venise et Bolzano',
      'Du 6 au 22 février 2026. La cérémonie d\'ouverture s\'est déroulée au stade de San Siro, à Milan.',
      'Les prochains Jeux d\'hiver, en 2030, auront lieu dans les Alpes françaises.'),
    a(2026, 2, 'QCM', 'Où auront lieu les Jeux olympiques d\'hiver de 2030 ?', 'Dans les Alpes françaises', 'En Suède', 'En Suisse', 'Au Japon',
      'Attribués en juillet 2024 à la candidature Alpes françaises (Auvergne-Rhône-Alpes et Provence-Alpes-Côte d\'Azur).',
      'La France a déjà accueilli trois fois les Jeux d\'hiver : Chamonix 1924, Grenoble 1968 et Albertville 1992.'),
    a(2026, 3, 'QCM', 'Quel artiste portoricain a assuré le spectacle de la mi-temps du Super Bowl en février 2026 ?', 'Bad Bunny', 'Ricky Martin', 'Daddy Yankee', 'Luis Fonsi',
      'Il a chanté presque entièrement en espagnol, une première pour ce show.',
      'Son album « Debí Tirar Más Fotos » faisait partie des plus écoutés au monde en 2025.'),
    a(2026, 3, 'QCM', 'Dans quelle ville s\'est déroulé l\'Eurovision 2026 ?', 'Vienne', 'Bâle', 'Stockholm', 'Paris',
      'L\'Autriche organisait le concours après la victoire de JJ en 2025.',
      'Vienne avait déjà accueilli l\'Eurovision en 2015, après la victoire de Conchita Wurst.'),
    a(2026, 1, 'VF', 'Les Jeux olympiques d\'été de 2028 auront lieu à Los Angeles.', 'Vrai', '', '', '',
      'Vrai : ce seront les troisièmes Jeux de Los Angeles, après 1932 et 1984. Brisbane suivra en 2032.',
      'Le flag-football, le cricket, la crosse et le squash feront leur entrée au programme.'),
  ];
}
