/**
 * Banque de questions (2) — Cinéma, Musique, Arts & Littérature, Gastronomie, Divers
 * Format : voir Banque1.gs
 */
function banque7_() {
  const C = 'Cinéma', M = 'Musique', A = 'Arts & Littérature', GA = 'Gastronomie', D = 'Divers';
  return [
    // ---------------- CINÉMA ----------------
    [C, 'Animation', 1, 'QCM', 'Quelle princesse Disney est une sirène ?', 'Ariel', 'Belle', 'Jasmine', 'Mulan', '« La Petite Sirène », 1989.', ''],
    [C, 'Animation', 1, 'QCM', 'Comment s\'appelle le cow-boy de « Toy Story » ?', 'Woody', 'Buzz', 'Rex', 'Zig', '', ''],
    [C, 'Animation', 1, 'VF', 'Shrek est un ogre.', 'Vrai', '', '', '', '', ''],
    [C, 'Animation', 1, 'QCM', 'Dans « Le Roi lion », comment s\'appelle le père de Simba ?', 'Mufasa', 'Scar', 'Rafiki', 'Timon', 'Scar est son oncle.', ''],
    [C, 'Acteurs', 2, 'QCM', 'Quel acteur joue Iron Man dans les films Marvel ?', 'Robert Downey Jr.', 'Chris Evans', 'Chris Hemsworth', 'Mark Ruffalo', '', ''],
    [C, 'Films', 2, 'QCM', 'Qui est le grand méchant de la saga Harry Potter ?', 'Voldemort', 'Drago Malefoy', 'Sirius Black', 'Severus Rogue', '', ''],
    [C, 'Films', 2, 'ESTIMATION', 'Combien de films compte la saga Harry Potter principale ?', '8', 'films', '0', '', 'Sept livres, mais le dernier a été découpé en deux films.', ''],
    [C, 'Films', 2, 'QCM', 'Qui a réalisé « Titanic » ?', 'James Cameron', 'Steven Spielberg', 'Ridley Scott', 'Peter Jackson', '', ''],
    [C, 'Festivals', 2, 'VF', 'Le Festival de Cannes décerne la Palme d\'or.', 'Vrai', '', '', '', '', ''],
    [C, 'Films', 3, 'QCM', 'Quel film de Luc Besson raconte l\'histoire de plongeurs en apnée ?', 'Le Grand Bleu', 'Nikita', 'Léon', 'Le Cinquième Élément', 'Sorti en 1988, avec Jean Reno et Jean-Marc Barr.', ''],
    [C, 'Acteurs', 3, 'QCM', 'Quel acteur joue le Joker dans « The Dark Knight » (2008) ?', 'Heath Ledger', 'Joaquin Phoenix', 'Jack Nicholson', 'Jared Leto', 'Oscar posthume du meilleur second rôle.', ''],
    [C, 'Films', 3, 'QCM', 'Dans quel film Louis de Funès joue-t-il Victor Pivert ?', 'Les Aventures de Rabbi Jacob', 'La Grande Vadrouille', 'Le Corniaud', 'Oscar', 'Sorti en 1973.', ''],
    [C, 'Années', 3, 'ESTIMATION', 'En quelle année est sorti le premier « Toy Story » ?', '1995', '', '2', '', 'Premier long métrage entièrement en images de synthèse.', ''],
    [C, 'Années', 3, 'ORDRE', 'Classez ces films par date de sortie.', 'E.T. l\'extra-terrestre | Jurassic Park | Titanic | Avatar', 'Du plus ancien au plus récent', '', '', '1982, 1993, 1997, 2009.', ''],
    [C, 'Films', 3, 'VF', '« Intouchables » est inspiré d\'une histoire vraie.', 'Vrai', '', '', '', 'Celle de Philippe Pozzo di Borgo et d\'Abdel Sellou.', ''],
    [C, 'Animation', 3, 'QCM', 'Quel studio a produit « Toy Story » ?', 'Pixar', 'DreamWorks', 'Illumination', 'Blue Sky', '', ''],
    [C, 'Acteurs', 4, 'QCM', 'Quelle actrice française a remporté l\'Oscar pour « La Môme » ?', 'Marion Cotillard', 'Juliette Binoche', 'Isabelle Huppert', 'Audrey Tautou', 'Pour son interprétation d\'Édith Piaf (2008).', ''],
    [C, 'Festivals', 4, 'QCM', 'Dans quelle ville se tient le festival qui remet l\'Ours d\'or ?', 'Berlin', 'Venise', 'Cannes', 'Toronto', 'Venise remet le Lion d\'or.', ''],
    [C, 'Records', 5, 'QCM', 'Quel film a remporté le tout premier Oscar du meilleur film d\'animation, en 2002 ?', 'Shrek', 'Monstres & Cie', 'Jimmy Neutron', 'L\'Âge de glace', '', ''],
    [C, 'Films', 5, 'QCM', 'Qui a réalisé « Parasite », Palme d\'or 2019 ?', 'Bong Joon-ho', 'Park Chan-wook', 'Hirokazu Kore-eda', 'Kim Ki-duk', 'Premier film non anglophone à remporter l\'Oscar du meilleur film.', ''],
    [C, 'Acteurs', 5, 'QCM', 'Quel acteur a joué James Bond dans le plus de films officiels ?', 'Roger Moore', 'Sean Connery', 'Daniel Craig', 'Pierce Brosnan', 'Sept films, de 1973 à 1985.', ''],

    // ---------------- MUSIQUE ----------------
    [M, 'Instruments', 1, 'QCM', 'Quel instrument à cordes se joue avec un archet ?', 'Le violon', 'La guitare', 'La harpe', 'Le piano', '', ''],
    [M, 'Instruments', 1, 'VF', 'La batterie est un instrument à percussion.', 'Vrai', '', '', '', '', ''],
    [M, 'Pop-rock', 1, 'QCM', 'Qui chante « Thriller » ?', 'Michael Jackson', 'Prince', 'Madonna', 'Stevie Wonder', '', ''],
    [M, 'Vocabulaire', 1, 'QCM', 'Combien de musiciens compte un duo ?', '2', '3', '4', '1', '', ''],
    [M, 'Pop-rock', 2, 'QCM', 'Quel chanteur américain est surnommé « le Boss » ?', 'Bruce Springsteen', 'Bob Dylan', 'Elvis Presley', 'Jon Bon Jovi', '', ''],
    [M, 'Pop-rock', 2, 'QCM', 'De quel pays vient le groupe ABBA ?', 'La Suède', 'La Norvège', 'Le Danemark', 'La Finlande', '', ''],
    [M, 'Instruments', 2, 'ESTIMATION', 'Combien de cordes a un violon ?', '4', 'cordes', '0', '', 'Sol, ré, la, mi.', ''],
    [M, 'Classique', 2, 'VF', 'Mozart a composé l\'opéra « La Flûte enchantée ».', 'Vrai', '', '', '', 'En 1791, l\'année de sa mort.', ''],
    [M, 'Pop-rock', 3, 'QCM', 'Quelle chanteuse a sorti l\'album « 21 » ?', 'Adele', 'Amy Winehouse', 'Duffy', 'Lana Del Rey', 'Sorti en 2011, avec « Rolling in the Deep ».', ''],
    [M, 'Pop-rock', 3, 'QCM', 'De quel instrument jouait Jimi Hendrix ?', 'De la guitare', 'Du saxophone', 'De la batterie', 'De la basse', '', ''],
    [M, 'Classique', 3, 'QCM', 'Qui a composé « La Lettre à Élise » ?', 'Beethoven', 'Mozart', 'Chopin', 'Schubert', '', ''],
    [M, 'Chronologie', 3, 'ORDRE', 'Classez ces chansons par date de sortie.', 'Heartbreak Hotel (Elvis) | Yesterday (Beatles) | Bohemian Rhapsody (Queen) | Smells Like Teen Spirit (Nirvana)', 'De la plus ancienne à la plus récente', '', '', '1956, 1965, 1975, 1991.', ''],
    [M, 'Classique', 3, 'QCM', 'De quel instrument jouait Frédéric Chopin ?', 'Du piano', 'Du violon', 'De l\'orgue', 'De la flûte', '', ''],
    [M, 'Pop-rock', 3, 'QCM', 'Qui chante « Imagine » (1971) ?', 'John Lennon', 'Paul McCartney', 'Bob Dylan', 'David Bowie', '', ''],
    [M, 'Pop-rock', 4, 'QCM', 'Quel est le nom de scène de Stefani Germanotta ?', 'Lady Gaga', 'Katy Perry', 'Pink', 'Sia', '', ''],
    [M, 'Pop-rock', 4, 'ESTIMATION', 'En quelle année Michael Jackson est-il mort ?', '2009', '', '1', '', 'Le 25 juin 2009, à Los Angeles.', ''],
    [M, 'Eurovision', 4, 'VF', 'La France a remporté l\'Eurovision cinq fois.', 'Vrai', '', '', '', '1958, 1960, 1962, 1969 et 1977.', ''],
    [M, 'Classique', 4, 'QCM', 'Quel compositeur russe a écrit « Le Lac des cygnes » ?', 'Tchaïkovski', 'Rachmaninov', 'Stravinsky', 'Moussorgski', '', ''],
    [M, 'Classique', 5, 'QCM', 'Qui a composé « Les Planètes » ?', 'Gustav Holst', 'Edward Elgar', 'Maurice Ravel', 'Claude Debussy', 'Suite orchestrale de 1916 qui a inspiré bien des musiques de films.', ''],
    [M, 'Classique', 5, 'VF', 'Beethoven est né à Vienne.', 'Faux', '', '', '', 'Il est né à Bonn en 1770, puis s\'est installé à Vienne.', ''],
    [M, 'Classique', 5, 'ESTIMATION', 'Combien de symphonies Mozart a-t-il composées environ ?', '41', 'symphonies', '3', '', 'On en compte traditionnellement 41.', ''],

    // ---------------- ARTS & LITTÉRATURE ----------------
    [A, 'Littérature', 1, 'QCM', 'Qui a écrit « Les Trois Mousquetaires » ?', 'Alexandre Dumas', 'Victor Hugo', 'Jules Verne', 'Molière', '', ''],
    [A, 'Poésie', 1, 'QCM', 'Qui a écrit la fable « Le Corbeau et le Renard » ?', 'Jean de La Fontaine', 'Charles Perrault', 'Molière', 'Voltaire', '', ''],
    [A, 'Littérature', 1, 'VF', 'La saga Harry Potter a été écrite par J. K. Rowling.', 'Vrai', '', '', '', '', ''],
    [A, 'Contes', 1, 'QCM', 'Dans quel conte un loup se déguise-t-il en grand-mère ?', 'Le Petit Chaperon rouge', 'Les Trois Petits Cochons', 'Cendrillon', 'Blanche-Neige', '', ''],
    [A, 'Littérature', 2, 'QCM', 'Qui a écrit « Le Tour du monde en quatre-vingts jours » ?', 'Jules Verne', 'Alexandre Dumas', 'Victor Hugo', 'Émile Zola', '', ''],
    [A, 'Sculpture', 2, 'QCM', 'Dans quelle ville se trouve la statue du Manneken-Pis ?', 'Bruxelles', 'Amsterdam', 'Anvers', 'Liège', '', ''],
    [A, 'BD', 2, 'VF', 'Tintin a été créé par Hergé.', 'Vrai', '', '', '', 'En 1929. Hergé est le pseudonyme de Georges Remi (R.G.).', ''],
    [A, 'BD', 2, 'QCM', 'Comment s\'appelle le chien de Tintin ?', 'Milou', 'Idéfix', 'Rantanplan', 'Pluto', '', ''],
    [A, 'Littérature', 3, 'QCM', 'Quel écrivain a créé le commissaire Maigret ?', 'Georges Simenon', 'Agatha Christie', 'Maurice Leblanc', 'Gaston Leroux', '', ''],
    [A, 'Peinture', 3, 'QCM', 'Qui a peint « Les Tournesols » ?', 'Vincent van Gogh', 'Claude Monet', 'Paul Gauguin', 'Paul Cézanne', '', ''],
    [A, 'Architecture', 3, 'QCM', 'Quel architecte est célèbre pour la Sagrada Família à Barcelone ?', 'Antoni Gaudí', 'Le Corbusier', 'Gustave Eiffel', 'Frank Gehry', 'Chantier commencé en 1882 et toujours en cours.', ''],
    [A, 'Littérature', 3, 'ORDRE', 'Classez ces écrivains selon leur date de naissance.', 'Molière | Voltaire | Victor Hugo | Marcel Pagnol', 'Du plus ancien au plus récent', '', '', '1622, 1694, 1802, 1895.', ''],
    [A, 'Littérature', 4, 'QCM', 'Qui a écrit « Madame Bovary » ?', 'Gustave Flaubert', 'Honoré de Balzac', 'Stendhal', 'Guy de Maupassant', '', ''],
    [A, 'Littérature', 4, 'QCM', 'Qui a écrit le roman « 1984 » ?', 'George Orwell', 'Aldous Huxley', 'Ray Bradbury', 'H. G. Wells', 'Publié en 1949. On lui doit « Big Brother ».', ''],
    [A, 'Littérature', 4, 'ESTIMATION', 'En quelle année a été publié « Le Petit Prince » ?', '1943', '', '2', '', 'D\'abord publié à New York.', ''],
    [A, 'Peinture', 4, 'VF', '« Le Cri » a été peint par Edvard Munch.', 'Vrai', '', '', '', 'Peintre norvégien, 1893.', ''],
    [A, 'Littérature', 4, 'QCM', 'Quel écrivain est l\'auteur de la série des « Rougon-Macquart » ?', 'Émile Zola', 'Honoré de Balzac', 'Victor Hugo', 'Gustave Flaubert', 'Vingt romans, dont « Germinal ».', ''],
    [A, 'Personnages', 4, 'VF', 'Victor Hugo est enterré au Panthéon.', 'Vrai', '', '', '', 'Depuis 1885, après des funérailles nationales.', ''],
    [A, 'Peinture', 5, 'QCM', 'Qui a peint « Le Radeau de la Méduse » ?', 'Théodore Géricault', 'Eugène Delacroix', 'Jacques-Louis David', 'Jean-Auguste-Dominique Ingres', 'Exposé au Louvre, 1819.', ''],
    [A, 'Littérature', 5, 'QCM', 'Qui a écrit « La Divine Comédie » ?', 'Dante', 'Pétrarque', 'Boccace', 'Machiavel', 'Au début du XIVe siècle.', ''],

    // ---------------- GASTRONOMIE ----------------
    [GA, 'Fruits', 1, 'QCM', 'Quel fruit jaune a une forme allongée et courbée ?', 'La banane', 'Le citron', 'La mangue', 'L\'ananas', '', ''],
    [GA, 'Cuisine', 1, 'VF', 'Le chocolat est fabriqué à partir de fèves de cacao.', 'Vrai', '', '', '', '', ''],
    [GA, 'Pain', 1, 'QCM', 'Quel ingrédient fait lever la pâte à pain ?', 'La levure', 'Le sel', 'Le sucre', 'Le beurre', '', ''],
    [GA, 'Cuisine', 1, 'ESTIMATION', 'Combien d\'œufs y a-t-il dans une douzaine ?', '12', 'œufs', '0', '', '', ''],
    [GA, 'Monde', 2, 'QCM', 'De quel pays vient la paella ?', 'L\'Espagne', 'L\'Italie', 'Le Portugal', 'Le Mexique', 'Spécialité de Valence.', ''],
    [GA, 'Fromages', 2, 'QCM', 'Quel fromage met-on sur une pizza margherita ?', 'La mozzarella', 'Le parmesan', 'Le gruyère', 'La feta', '', ''],
    [GA, 'Cuisine', 2, 'VF', 'Le croque-monsieur est composé de jambon et de fromage.', 'Vrai', '', '', '', 'Avec un œuf au plat, il devient un croque-madame.', ''],
    [GA, 'Boissons', 2, 'QCM', 'Quel alcool est la base du mojito ?', 'Le rhum', 'La vodka', 'Le gin', 'La tequila', 'Cocktail cubain.', ''],
    [GA, 'Régions', 3, 'QCM', 'Quelle ville est célèbre pour sa moutarde ?', 'Dijon', 'Lyon', 'Bordeaux', 'Nancy', '', ''],
    [GA, 'Monde', 3, 'QCM', 'Quel est l\'ingrédient principal du houmous ?', 'Le pois chiche', 'L\'aubergine', 'La lentille', 'Le haricot blanc', '', ''],
    [GA, 'Desserts', 3, 'QCM', 'De quel pays vient le tiramisu ?', 'L\'Italie', 'La France', 'L\'Autriche', 'L\'Espagne', '', ''],
    [GA, 'Cuisine', 3, 'ORDRE', 'Classez ces cuissons de viande.', 'Bleu | Saignant | À point | Bien cuit', 'Du moins cuit au plus cuit', '', '', '', ''],
    [GA, 'Régions', 3, 'QCM', 'Quelle ville française est surnommée « la capitale de la gastronomie » ?', 'Lyon', 'Paris', 'Bordeaux', 'Marseille', 'Célèbre pour ses « bouchons » et ses « mères » lyonnaises.', ''],
    [GA, 'Monde', 4, 'QCM', 'Quel légume est la base du gaspacho ?', 'La tomate', 'La courgette', 'La carotte', 'Le poireau', 'Soupe froide andalouse.', ''],
    [GA, 'Fromages', 4, 'QCM', 'Quel fromage AOP est fabriqué dans le massif du Jura ?', 'Le comté', 'Le reblochon', 'Le cantal', 'Le munster', '', ''],
    [GA, 'Régions', 4, 'VF', 'Le cassoulet est une spécialité du Sud-Ouest.', 'Vrai', '', '', '', 'Castelnaudary, Carcassonne et Toulouse s\'en disputent la paternité.', ''],
    [GA, 'Cuisine', 4, 'QCM', 'Comment appelle-t-on une viande cuite lentement dans sa propre graisse ?', 'Un confit', 'Un braisé', 'Un sauté', 'Un poché', 'Comme le confit de canard.', ''],
    [GA, 'Épices', 5, 'QCM', 'Quelle épice donne sa couleur au risotto alla milanese ?', 'Le safran', 'Le curcuma', 'Le paprika', 'Le cumin', '', ''],
    [GA, 'Botanique', 5, 'VF', 'La vanille est le fruit d\'une orchidée.', 'Vrai', '', '', '', 'Une orchidée grimpante originaire du Mexique.', ''],
    [GA, 'Nutrition', 5, 'ESTIMATION', 'Combien de kilocalories apporte 1 gramme de lipides (graisses) ?', '9', 'kcal', '0', '', 'Contre environ 4 kcal pour les glucides et les protéines.', ''],

    // ---------------- DIVERS ----------------
    [D, 'Maths', 1, 'QCM', 'Combien de côtés a un triangle ?', '3', '4', '5', '6', '', ''],
    [D, 'Calendrier', 1, 'QCM', 'Combien de mois compte une année ?', '12', '10', '11', '13', '', ''],
    [D, 'Calendrier', 1, 'VF', 'Un siècle correspond à 100 ans.', 'Vrai', '', '', '', '', ''],
    [D, 'Couleurs', 1, 'QCM', 'Quelle couleur obtient-on en mélangeant du rouge et du blanc ?', 'Du rose', 'De l\'orange', 'Du violet', 'Du marron', '', ''],
    [D, 'Temps', 1, 'ORDRE', 'Classez ces durées.', 'Seconde | Minute | Heure | Jour | Semaine', 'De la plus courte à la plus longue', '', '', '', ''],
    [D, 'Monnaies', 2, 'QCM', 'Quelle est la monnaie du Japon ?', 'Le yen', 'Le yuan', 'Le won', 'Le dollar', 'Le yuan est la monnaie chinoise, le won la coréenne.', ''],
    [D, 'Langue française', 2, 'QCM', 'Quel est le féminin de « acteur » ?', 'Actrice', 'Acteuse', 'Acteure', 'Actresse', '', ''],
    [D, 'Séries', 2, 'QCM', 'Quel est le prénom du père dans « Les Simpson » ?', 'Homer', 'Bart', 'Ned', 'Moe', '', ''],
    [D, 'Jeux', 3, 'ESTIMATION', 'Combien de cases compte un échiquier ?', '64', 'cases', '0', '', '8 × 8.', ''],
    [D, 'Maths', 3, 'ESTIMATION', 'Combien de minutes compte une journée ?', '1440', 'min', '0', '', '24 × 60.', ''],
    [D, 'Monnaies', 3, 'QCM', 'Quelle est la monnaie du Royaume-Uni ?', 'La livre sterling', 'L\'euro', 'Le dollar', 'Le franc', '', ''],
    [D, 'Maths', 3, 'QCM', 'Comment appelle-t-on un polygone à 5 côtés ?', 'Un pentagone', 'Un hexagone', 'Un octogone', 'Un heptagone', '', ''],
    [D, 'Jeux', 3, 'QCM', 'Combien de pièces chaque joueur a-t-il au début d\'une partie d\'échecs ?', '16', '12', '20', '18', '8 pions et 8 pièces.', ''],
    [D, 'Vocabulaire', 4, 'QCM', 'Comment appelle-t-on une personne qui ne consomme aucun produit d\'origine animale ?', 'Végan', 'Végétarien', 'Flexitarien', 'Pescétarien', '', ''],
    [D, 'Sciences', 4, 'QCM', 'Que mesure l\'échelle de Richter ?', 'La magnitude des séismes', 'La force du vent', 'La température', 'Les précipitations', '', ''],
    [D, 'Tech', 5, 'VF', 'Selon le Système international, un kilooctet vaut exactement 1 000 octets.', 'Vrai', '', '', '', '1 024 octets correspondent à un « kibioctet » (Kio).', 'Question piège, accepter le débat.'],
    [D, 'Vocabulaire', 5, 'QCM', 'Comment appelle-t-on la peur du nombre 13 ?', 'La triskaïdékaphobie', 'L\'hexakosioihexekontahexaphobie', 'La tétraphobie', 'La numérophobie', 'L\'hexakosioi… est la peur du nombre 666 !', ''],
    [D, 'Jeux', 5, 'QCM', 'Dans quel pays le jeu de go a-t-il été inventé ?', 'En Chine', 'Au Japon', 'En Corée', 'En Inde', 'Il y a plus de 2 500 ans.', ''],
    [D, 'Maths', 3, 'QCM', 'Combien vaut la somme des angles d\'un triangle ?', '180°', '360°', '90°', '270°', '', ''],
  ];
}
