/**
 * Banque de questions — thème « Insolite » : faits étonnants, idées reçues, records bizarres.
 * q(catégorie, difficulté, type, question, réponse, choix2, choix3, choix4, explication, indices MJ, anecdote MJ)
 * L'explication s'affiche pour tout le monde ; l'anecdote (« Pour animer ») est réservée au maître du jeu.
 */
function banqueInsolite_() {
  const T = 'Insolite';
  const q = (cat, diff, type, texte, rep, c2, c3, c4, expl, ind, anec) =>
    [T, cat, diff, type, texte, rep, c2 || '', c3 || '', c4 || '', expl || '', ind || '', '', '', '', '', anec || ''];
  return [
    // ---------------- Animaux étonnants ----------------
    q('Animaux', 3, 'QCM', 'Quel minuscule animal a survécu à un séjour dans le vide spatial ?', 'Le tardigrade', 'La fourmi', 'Le cafard', 'La puce d\'eau',
      'En 2007, des tardigrades exposés au vide et aux rayons de l\'espace pendant 10 jours ont survécu et se sont reproduits.',
      'On l\'appelle aussi « ourson d\'eau ».', 'Il mesure moins d\'un millimètre. Déshydraté, il peut survivre des années, supporter des températures proches du zéro absolu et des pressions énormes.'),
    q('Animaux', 1, 'VF', 'Les wombats font des crottes en forme de cube.', 'Vrai', '', '', '',
      'Vrai ! Leur intestin a des zones plus ou moins élastiques qui façonnent des cubes d\'environ 2 cm.',
      '', 'Des chercheurs ont reçu un prix Ig Nobel en 2019 pour avoir percé ce mystère. Les cubes ne roulent pas : le wombat les dépose sur des rochers pour marquer son territoire.'),
    q('Animaux', 1, 'VF', 'Le cœur d\'une crevette se trouve dans sa tête.', 'Vrai', '', '', '',
      'Vrai : il est logé dans le céphalothorax, la partie « tête » de la crevette.',
      '', 'Quand on « étête » une crevette, on retire donc aussi son cœur, son estomac et une bonne partie de ses organes.'),
    q('Animaux', 1, 'QCM', 'Pourquoi les flamants roses sont-ils roses ?', 'À cause de leur nourriture', 'À cause du soleil', 'C\'est génétique', 'Pour attirer les femelles uniquement',
      'Ils mangent des petits crustacés et des algues riches en caroténoïdes, les pigments de la carotte.',
      '', 'Les poussins naissent gris-blanc. En zoo, sans alimentation adaptée, les flamants deviennent tout pâles : on leur donne des compléments pour garder leur couleur.'),
    q('Animaux', 2, 'VF', 'Les loutres de mer se tiennent par la patte pour ne pas dériver en dormant.', 'Vrai', '', '', '',
      'Vrai : elles forment parfois des « radeaux » et s\'enroulent aussi dans les algues pour rester en place.',
      '', 'Elles ont une poche de peau sous chaque bras où elles rangent leur caillou préféré, qui leur sert à casser les coquillages.'),
    q('Animaux', 2, 'VF', 'Un escargot peut avoir plusieurs milliers de dents.', 'Vrai', '', '', '',
      'Vrai : sa langue, la radula, est couverte de rangées de minuscules dents (jusqu\'à plus de 10 000 chez certaines espèces).',
      '', 'Ses dents s\'usent en râpant les feuilles et sont remplacées en permanence, comme sur un tapis roulant.'),
    q('Animaux', 2, 'VF', 'Les éléphants sont incapables de sauter.', 'Vrai', '', '', '',
      'Vrai : trop lourds et avec des os de pattes orientés vers le bas, ils gardent toujours un pied au sol.',
      '', 'Même en « courant » (jusqu\'à 25 km/h), un éléphant n\'a jamais ses quatre pieds en l\'air en même temps.'),
    q('Animaux', 2, 'QCM', 'De quelle couleur est la « sueur » de l\'hippopotame ?', 'Rouge-orangé', 'Bleue', 'Verte', 'Noire',
      'Cette sécrétion rouge sert de crème solaire et d\'antibactérien. On l\'appelle parfois « sueur de sang ».',
      '', 'Il ne s\'agit ni de sang ni de vraie sueur : ce sont deux pigments, l\'acide hipposudorique (rouge) et l\'acide norhipposudorique (orange).'),
    q('Animaux', 2, 'VF', 'Les papillons goûtent avec leurs pattes.', 'Vrai', '', '', '',
      'Vrai : leurs pattes portent des récepteurs gustatifs. Les femelles « goûtent » les feuilles pour y pondre au bon endroit.',
      '', 'Les mouches aussi ! C\'est pour ça qu\'elles se frottent les pattes : elles nettoient leurs capteurs de goût.'),
    q('Animaux', 3, 'VF', 'Les dauphins dorment avec un œil ouvert.', 'Vrai', '', '', '',
      'Vrai : une moitié de leur cerveau dort pendant que l\'autre reste en éveil pour respirer et surveiller.',
      '', 'Ce sommeil « unihémisphérique » existe aussi chez certains oiseaux, comme les canards placés en bordure de groupe.'),
    q('Animaux', 3, 'QCM', 'Combien d\'yeux peut avoir une coquille Saint-Jacques ?', 'Jusqu\'à 200', 'Aucun', '2', '8',
      'Ils sont alignés sur le bord du manteau et fonctionnent avec de minuscules miroirs.',
      '', 'Chaque œil contient un miroir fait de cristaux de guanine qui concentre la lumière, un principe proche de celui de certains télescopes.'),
    q('Mots et objets', 3, 'QCM', 'D\'où viendrait le verbe « baragouiner » ?', 'Du breton « bara » (pain) et « gwin » (vin)', 'Du latin « barbarus »', 'De l\'arabe « baraka »', 'De l\'italien « baracca »',
      'Les soldats bretons auraient demandé du pain et du vin dans leur langue, incompréhensible pour les autres Français.',
      '', 'On attribue souvent cette origine à la guerre de Cent Ans ou aux soldats bretons en garnison. Les linguistes la trouvent plausible, sans certitude absolue.'),
    q('Animaux', 3, 'VF', 'Les huîtres peuvent changer de sexe au cours de leur vie.', 'Vrai', '', '', '',
      'Vrai : l\'huître creuse est souvent mâle en premier, puis alterne selon les saisons et la température de l\'eau.',
      '', 'On parle d\'hermaphrodisme successif. Une même huître peut changer plusieurs fois de sexe dans sa vie.'),
    q('Animaux', 4, 'VF', 'Il existe une méduse considérée comme « biologiquement immortelle ».', 'Vrai', '', '', '',
      'Vrai : Turritopsis dohrnii peut retourner à son stade juvénile (polype) quand elle est stressée ou vieillit.',
      '', 'Elle ne mesure que 4,5 mm. Elle peut quand même mourir, mangée ou malade, mais elle peut recommencer son cycle de vie en boucle.'),
    q('Animaux', 4, 'QCM', 'Combien de temps un paresseux met-il à digérer un repas ?', 'Plusieurs semaines', '2 heures', '1 journée', '6 mois',
      'Jusqu\'à un mois pour une ration de feuilles ! Il descend de son arbre environ une fois par semaine pour faire ses besoins.',
      '', 'Des algues vertes poussent dans sa fourrure et le camouflent. Une espèce de papillon vit même uniquement dans le pelage des paresseux.'),
    q('Animaux', 5, 'QCM', 'Quel animal a la plus longue durée de vie connue parmi les vertébrés ?', 'Le requin du Groenland', 'La tortue géante', 'L\'éléphant', 'Le perroquet',
      'Des datations au carbone 14 estiment que certains individus auraient au moins 270 à 400 ans.',
      '', 'Il grandit d\'environ 1 cm par an et n\'atteindrait sa maturité sexuelle que vers 150 ans. Certains nageaient donc déjà sous Louis XIV.'),

    // ---------------- Idées reçues ----------------
    q('Idées reçues', 1, 'VF', 'Les poissons rouges ont une mémoire de 3 secondes.', 'Faux', '', '', '',
      'Faux : des expériences montrent qu\'ils se souviennent de choses pendant des mois.',
      '', 'On a appris à des poissons rouges à pousser un levier pour avoir à manger à une heure précise de la journée.'),
    q('Idées reçues', 1, 'VF', 'Les taureaux s\'énervent quand ils voient la couleur rouge.', 'Faux', '', '', '',
      'Faux : ils ne distinguent pas bien le rouge. C\'est le mouvement de la cape qui les fait charger.',
      '', 'La muleta est rouge pour… cacher le sang aux yeux du public. Des tests avec des capes bleues ou blanches donnent le même résultat.'),
    q('Idées reçues', 1, 'VF', 'On n\'utilise que 10 % de notre cerveau.', 'Faux', '', '', '',
      'Faux : l\'imagerie montre que toutes les zones du cerveau servent, même si elles ne sont pas actives en même temps.',
      '', 'Le cerveau pèse 2 % de notre poids mais consomme environ 20 % de notre énergie : un organe inutile à 90 % n\'aurait pas survécu à l\'évolution.'),
    q('Idées reçues', 1, 'VF', 'La foudre ne tombe jamais deux fois au même endroit.', 'Faux', '', '', '',
      'Faux : l\'Empire State Building est frappé une vingtaine de fois par an en moyenne.',
      '', 'Le garde forestier américain Roy Sullivan a été touché sept fois par la foudre entre 1942 et 1977… et a survécu à chaque fois.'),
    q('Idées reçues', 2, 'VF', 'Les Vikings portaient des casques à cornes.', 'Faux', '', '', '',
      'Faux : aucun casque à cornes viking n\'a été retrouvé. L\'image vient des costumes d\'un opéra de Wagner (1876).',
      '', 'Le seul casque viking complet connu, le casque de Gjermundbu, trouvé en Norvège, est tout simple et arrondi.'),
    q('Idées reçues', 2, 'VF', 'Les autruches mettent la tête dans le sable quand elles ont peur.', 'Faux', '', '', '',
      'Faux : elles se couchent au sol, cou allongé, pour se faire discrètes. De loin, on dirait que leur tête a disparu.',
      '', 'Elles creusent aussi des trous pour leurs œufs et y retournent régulièrement la tête pour les tourner.'),
    q('Idées reçues', 2, 'VF', 'Napoléon était particulièrement petit pour son époque.', 'Faux', '', '', '',
      'Faux : il mesurait environ 1,69 m, un peu plus que la moyenne des Français de l\'époque.',
      '', 'La confusion vient des pouces : 5 pieds 2 pouces français font 1,69 m, mais en pouces anglais on a compris 1,57 m. Les caricaturistes anglais ont fait le reste.'),
    q('Idées reçues', 2, 'VF', 'La Grande Muraille de Chine est visible depuis la Lune à l\'œil nu.', 'Faux', '', '', '',
      'Faux : elle est bien trop étroite. Depuis la Lune, on ne distingue aucune construction humaine.',
      '', 'Même depuis la Station spatiale internationale (400 km), les astronautes ont beaucoup de mal à la voir. Le premier astronaute chinois, Yang Liwei, a confirmé ne pas l\'avoir vue.'),
    q('Idées reçues', 3, 'VF', 'Les chauves-souris sont aveugles.', 'Faux', '', '', '',
      'Faux : elles voient, parfois très bien. Beaucoup utilisent en plus l\'écholocation pour chasser dans le noir.',
      '', 'Les grandes roussettes (renards volants) n\'utilisent même pas d\'écholocation : elles se repèrent grâce à leur excellente vue.'),
    q('Idées reçues', 3, 'VF', 'Le sang est bleu dans les veines, avant de toucher l\'oxygène de l\'air.', 'Faux', '', '', '',
      'Faux : il est toujours rouge, plus foncé dans les veines. Les veines paraissent bleues à cause de la façon dont la peau filtre la lumière.',
      '', 'L\'expression « sang bleu » viendrait des nobles espagnols à la peau pâle, dont les veines se voyaient bien.'),
    q('Idées reçues', 3, 'VF', 'Marie-Antoinette a dit : « S\'ils n\'ont pas de pain, qu\'ils mangent de la brioche ».', 'Faux', '', '', '',
      'Faux : aucune source ne le prouve. Rousseau attribue une phrase semblable à « une grande princesse » dans un texte écrit quand Marie-Antoinette était enfant.',
      '', 'Le passage des « Confessions » de Rousseau date d\'environ 1765 ; Marie-Antoinette avait 10 ans et vivait encore à Vienne.'),

    // ---------------- Records et bizarreries ----------------
    q('Records', 1, 'QCM', 'Combien de temps a duré la guerre la plus courte de l\'histoire (Royaume-Uni contre Zanzibar, 1896) ?', 'Moins d\'une heure', 'Une journée', 'Une semaine', 'Un mois',
      'Environ 38 à 45 minutes, selon les sources, le 27 août 1896.',
      '', 'Le palais du sultan a été bombardé par la marine britannique. Zanzibar a dû payer les obus tirés contre lui.'),
    q('Records', 2, 'QCM', 'Que filmait la toute première webcam, en 1991 à Cambridge ?', 'Une cafetière', 'Un aquarium', 'La porte d\'un bureau', 'Un chat',
      'Des chercheurs voulaient savoir, sans se déplacer, s\'il restait du café dans la machine du couloir.',
      '', 'La « Trojan Room coffee pot » a été mise sur Internet en 1993 et est devenue une attraction mondiale. La cafetière a été vendue aux enchères en 2001.'),
    q('Animaux', 2, 'QCM', 'De quelle couleur est la langue d\'une girafe ?', 'Bleu-noir', 'Rose', 'Jaune', 'Rouge vif',
      'Sa couleur foncée la protégerait des coups de soleil pendant les longues heures passées à brouter.',
      '', 'Elle mesure jusqu\'à 50 cm et sert à attraper les feuilles entre les épines des acacias.'),
    q('Records', 2, 'ESTIMATION', 'Pendant combien d\'années l\'Américain Charles Osborne a-t-il eu le hoquet sans interruption ?', '68', 'ans', '5', '',
      'De 1922 à 1990 ! Un record du Guinness.',
      '', 'Il a hoqueté environ 430 millions de fois, s\'est marié deux fois et a eu 8 enfants. Le hoquet s\'est arrêté tout seul un an avant sa mort.'),
    q('Records', 2, 'QCM', 'Quel est le seul aliment qui ne se périme pratiquement jamais ?', 'Le miel', 'Le riz', 'Le sucre', 'Le chocolat noir',
      'Très sucré, acide et pauvre en eau, il empêche les bactéries de se développer.',
      '', 'Des archéologues ont trouvé des pots de miel dans des tombes égyptiennes vieilles de plus de 3 000 ans, encore consommables.'),
    q('Records', 3, 'ESTIMATION', 'Combien mesurait Robert Wadlow, l\'homme le plus grand de l\'histoire (en cm) ?', '272', 'cm', '5', '',
      '2,72 m, mesuré en 1940. Il chaussait du 76 !',
      '', 'Sa croissance ne s\'est jamais arrêtée à cause d\'une anomalie de l\'hypophyse. Il est mort à 22 ans ; son cercueil a été porté par 12 personnes.'),
    q('Records', 3, 'QCM', 'Quel est le premier objet vendu sur eBay en 1995 ?', 'Un pointeur laser cassé', 'Une Game Boy', 'Une carte Pokémon', 'Un vélo',
      'Il est parti pour 14,83 dollars. L\'acheteur collectionnait les pointeurs laser cassés !',
      '', 'Le site s\'appelait encore AuctionWeb. Son fondateur Pierre Omidyar, né à Paris, avait écrit à l\'acheteur pour vérifier qu\'il savait que le pointeur ne marchait pas.'),
    q('Records', 3, 'QCM', 'Quel pays possède le plus de pyramides au monde ?', 'Le Soudan', 'L\'Égypte', 'Le Mexique', 'Le Pérou',
      'Plus de 200 pyramides nubiennes, plus petites et plus pointues que celles d\'Égypte, notamment à Méroé.',
      '', 'Elles ont été construites par les rois et reines du royaume de Koush, qui a même régné sur l\'Égypte (la 25e dynastie des « pharaons noirs »).'),
    q('Records', 4, 'QCM', 'Quelle est la plus vieille entreprise du monde encore en activité (jusqu\'en 2006 indépendante) ?', 'Kongō Gumi, constructeur de temples japonais', 'Une brasserie bavaroise', 'Une banque italienne', 'Un fabricant de cloches français',
      'Fondée en 578 au Japon, elle a été dirigée par la même famille pendant plus de 1 400 ans.',
      '', 'Elle a construit le temple Shitennō-ji d\'Osaka. En difficulté financière, elle a été rachetée en 2006 et existe toujours comme filiale.'),
    q('Records', 5, 'QCM', 'Quelle commune française a le nom le plus long ?', 'Saint-Remy-en-Bouzemont-Saint-Genest-et-Isson', 'Châtillon-sur-Chalaronne', 'Saint-Germain-de-Tallevende-la-Lande-Vaumont', 'Y',
      'Dans la Marne : 38 lettres, 45 caractères avec les tirets.',
      '', 'À l\'inverse, la commune de Y, dans la Somme, a le nom le plus court de France. Ses habitants s\'appellent les Ypsiloniens.'),
    q('Records', 1, 'VF', 'Il existe en France une commune qui s\'appelle simplement « Y ».', 'Vrai', '', '', '',
      'Vrai : dans la Somme, environ 90 habitants, les Ypsiloniens.',
      '', 'Il existe aussi une commune « Eu » (Seine-Maritime) et « Ay » (Marne, aujourd\'hui Aÿ-Champagne).'),

    // ---------------- Histoire insolite ----------------
    q('Histoire insolite', 1, 'VF', 'Cléopâtre a vécu plus près de nous que de la construction de la grande pyramide de Khéops.', 'Vrai', '', '', '',
      'Vrai : la pyramide date d\'environ 2560 av. J.-C., Cléopâtre est morte en 30 av. J.-C. Environ 2 500 ans d\'un côté, 2 050 de l\'autre.',
      '', 'Pour Cléopâtre, les pyramides étaient déjà des monuments antiques, plus vieux pour elle que Charlemagne ne l\'est pour nous.'),
    q('Histoire insolite', 2, 'VF', 'L\'université d\'Oxford est plus ancienne que l\'Empire aztèque.', 'Vrai', '', '', '',
      'Vrai : on y enseigne dès 1096, tandis que Tenochtitlan, la capitale aztèque, a été fondée vers 1325.',
      '', 'La Sorbonne (fondée vers 1257) est aussi plus ancienne que Tenochtitlan.'),
    q('Histoire insolite', 2, 'VF', 'La tour Eiffel devait être démontée au bout de 20 ans.', 'Vrai', '', '', '',
      'Vrai : elle a été sauvée grâce à son utilité scientifique, notamment pour la radio (TSF).',
      '', 'En 1914, son antenne a intercepté des messages allemands avant la bataille de la Marne. Sans la radio, elle aurait peut-être disparu en 1909.'),
    q('Histoire insolite', 2, 'QCM', 'De quelle couleur était la statue de la Liberté à son inauguration en 1886 ?', 'Cuivrée (brun-orangé)', 'Blanche', 'Dorée', 'Grise',
      'Elle a la couleur du cuivre. Le vert-de-gris est apparu en une trentaine d\'années avec l\'oxydation.',
      '', 'Quand elle a verdi, le Congrès américain a envisagé de la repeindre. On a finalement décidé que cette patine la protégeait.'),
    q('Histoire insolite', 3, 'VF', 'Au Moyen Âge, des animaux ont été jugés au tribunal.', 'Vrai', '', '', '',
      'Vrai : en 1386, à Falaise (Normandie), une truie a été condamnée et pendue pour avoir tué un enfant.',
      '', 'On a aussi fait des procès aux charançons, aux rats ou aux sauterelles, avec des avocats commis d\'office pour les défendre !'),
    q('Histoire insolite', 3, 'VF', 'Au XIXe siècle, le ketchup était vendu comme un médicament.', 'Vrai', '', '', '',
      'Vrai : dans les années 1830, un médecin américain vendait des pilules de tomate contre l\'indigestion.',
      '', 'Le mot « ketchup » viendrait d\'une sauce de poisson fermenté d\'Asie du Sud-Est. La tomate n\'y a été ajoutée qu\'au XIXe siècle.'),
    q('Histoire insolite', 3, 'QCM', 'De quelle couleur étaient la plupart des carottes avant le XVIIe siècle ?', 'Violettes ou jaunes', 'Oranges', 'Bleues', 'Rouges',
      'La carotte orange a été popularisée par les maraîchers hollandais au XVIIe siècle.',
      '', 'Une légende dit qu\'ils l\'auraient sélectionnée en hommage à la maison d\'Orange-Nassau. C\'est sympathique, mais pas prouvé.'),
    q('Histoire insolite', 4, 'VF', 'Albert Einstein s\'est vu proposer la présidence de l\'État d\'Israël.', 'Vrai', '', '', '',
      'Vrai, en 1952. Il a refusé, se disant dépourvu « d\'aptitude naturelle et d\'expérience pour traiter avec les gens ».',
      '', 'Il avait 73 ans. Il a expliqué qu\'il était « profondément touché », mais qu\'il se sentait plus à l\'aise avec les équations.'),
    q('Histoire insolite', 4, 'QCM', 'Qui a volé la Joconde au Louvre en 1911 ?', 'Un vitrier italien', 'Arsène Lupin', 'Pablo Picasso', 'Un gardien du musée',
      'Vincenzo Peruggia, qui avait travaillé au Louvre. Il l\'a gardée 2 ans chez lui, à Paris, avant d\'être arrêté à Florence.',
      '', 'Guillaume Apollinaire a été brièvement emprisonné, et Picasso interrogé ! Le vol a rendu la Joconde mondialement célèbre.'),
    q('Histoire insolite', 5, 'VF', 'Le président américain Abraham Lincoln est au temple de la renommée de la lutte.', 'Vrai', '', '', '',
      'Vrai : il a perdu un seul combat sur environ 300 dans sa jeunesse, selon la légende. Il est entré au Wrestling Hall of Fame en 1992.',
      '', 'Il mesurait 1,93 m, le plus grand président américain. Il aurait défié des spectateurs en lançant : « Je suis le plus costaud du coin ! »'),

    // ---------------- Monde bizarre ----------------
    q('Monde bizarre', 1, 'QCM', 'Quel animal est le symbole officiel de l\'Écosse ?', 'La licorne', 'Le lion', 'Le cerf', 'Le dragon',
      'La licorne, symbole de pureté et de puissance, figure dans les armoiries écossaises depuis le XIIe siècle.',
      '', 'Sur les armoiries du Royaume-Uni, la licorne écossaise fait face au lion anglais. Elle est enchaînée : on disait qu\'une licorne libre était indomptable.'),
    q('Monde bizarre', 2, 'VF', 'Il y a plus de moutons que d\'habitants en Nouvelle-Zélande.', 'Vrai', '', '', '',
      'Vrai : environ 25 millions de moutons pour un peu plus de 5 millions d\'habitants.',
      '', 'Dans les années 1980, il y en avait 70 millions, soit 22 par habitant !'),
    q('Monde bizarre', 2, 'VF', 'En Suisse, il est interdit de n\'avoir qu\'un seul cochon d\'Inde.', 'Vrai', '', '', '',
      'Vrai : animal social, il doit vivre avec au moins un congénère selon la loi sur la protection des animaux (2008).',
      '', 'Un service de « location de cochon d\'Inde » existe même pour tenir compagnie à un animal devenu veuf.'),
    q('Monde bizarre', 2, 'QCM', 'Dans quel pays n\'y a-t-il (presque) pas de moustiques ?', 'L\'Islande', 'La Norvège', 'Le Groenland', 'La Finlande',
      'Les cycles de gel et dégel y empêcheraient les larves de se développer.',
      '', 'Un premier moustique a pourtant été capturé en Islande en 2025, sans doute signe du réchauffement.'),
    q('Monde bizarre', 3, 'VF', 'Le Canada compte plus de lacs que tous les autres pays du monde réunis.', 'Vrai', '', '', '',
      'Vrai : il possède environ 60 % des lacs de la planète.',
      '', 'On en compte plus de 2 millions, dont environ 31 000 de plus de 3 km². Merci les glaciers de la dernière ère glaciaire !'),
    q('Monde bizarre', 3, 'QCM', 'Quel est le premier pays à fêter le Nouvel An ?', 'Les Kiribati', 'Le Japon', 'La Nouvelle-Zélande', 'Les Samoa américaines',
      'L\'île Kiritimati (Christmas), aux Kiribati, est dans le fuseau UTC+14.',
      '', 'Les Samoa américaines, à quelques centaines de kilomètres, sont parmi les derniers : presque 25 heures d\'écart entre voisins.'),
    q('Monde bizarre', 3, 'VF', 'Il a déjà neigé dans le Sahara.', 'Vrai', '', '', '',
      'Vrai : notamment en 1979, 2016, 2018 et 2022 autour d\'Aïn Sefra, en Algérie.',
      '', 'Les températures nocturnes dans le désert peuvent passer sous zéro. Il suffit alors d\'un peu d\'humidité.'),
    q('Monde bizarre', 4, 'VF', 'La tour Eiffel grandit d\'une dizaine de centimètres en été.', 'Vrai', '', '', '',
      'Vrai : le fer se dilate avec la chaleur. Elle peut prendre jusqu\'à une quinzaine de centimètres.',
      '', 'Au soleil, un côté se dilate plus que l\'autre : son sommet s\'éloigne légèrement du soleil au cours de la journée.'),
    q('Monde bizarre', 4, 'VF', 'Les bananes sont légèrement radioactives.', 'Vrai', '', '', '',
      'Vrai, grâce au potassium 40 qu\'elles contiennent. Mais il faudrait en manger des millions d\'un coup pour que ce soit dangereux.',
      '', 'Les physiciens parlent même de la « dose équivalente banane » pour expliquer la radioactivité au public.'),
    q('Monde bizarre', 5, 'VF', 'Sur Vénus, un jour dure plus longtemps qu\'une année.', 'Vrai', '', '', '',
      'Vrai : Vénus tourne sur elle-même en 243 jours terrestres, et autour du Soleil en 225 jours.',
      '', 'Elle tourne en plus à l\'envers : sur Vénus, le Soleil se lève à l\'ouest et se couche à l\'est.'),

    // ---------------- Mots et objets ----------------
    q('Mots et objets', 1, 'QCM', 'D\'où vient le mot « robot » ?', 'Du tchèque', 'Du japonais', 'De l\'anglais', 'Du latin',
      'De « robota », la corvée. Il apparaît en 1920 dans une pièce de théâtre de Karel Čapek.',
      '', 'C\'est Josef, le frère de Karel Čapek, qui lui aurait soufflé le mot. Dans la pièce, les robots finissent par se révolter contre les humains.'),
    q('Mots et objets', 2, 'QCM', 'Dans quel pays a été inventé le jeu Tetris ?', 'En URSS', 'Au Japon', 'Aux États-Unis', 'En Corée du Sud',
      'Créé en 1984 par Alexeï Pajitnov, informaticien à Moscou.',
      '', 'Pajitnov n\'a touché ses premiers droits qu\'en 1996. Le nom mélange « tétra » (4, le nombre de carrés par pièce) et « tennis », son sport préféré.'),
    q('Mots et objets', 2, 'VF', 'La Joconde n\'a ni sourcils ni cils.', 'Vrai', '', '', '',
      'Vrai, à l\'œil nu. Un examen en haute résolution a retrouvé la trace d\'un sourcil effacé par le temps ou les restaurations.',
      '', 'Le tableau mesure seulement 77 cm sur 53. Beaucoup de visiteurs sont surpris par sa petite taille.'),
    q('Mots et objets', 3, 'QCM', 'Quel mot a longtemps été présenté comme le plus long du dictionnaire français ?', 'Anticonstitutionnellement', 'Intergouvernementalisations', 'Hippopotomonstrosesquippedaliophobie', 'Désinstitutionnalisation',
      '25 lettres. On trouve aujourd\'hui plus long, comme « intergouvernementalisations » (27 lettres).',
      '', 'La peur des mots longs s\'appelle… l\'hippopotomonstrosesquippedaliophobie. Les linguistes ont un certain sens de l\'humour.'),
    q('Mots et objets', 3, 'VF', 'Une pomme flotte sur l\'eau parce qu\'elle contient environ 25 % d\'air.', 'Vrai', '', '', '',
      'Vrai : sa chair est pleine de petites poches d\'air, ce qui la rend moins dense que l\'eau.',
      '', 'C\'est ce qui permet le jeu traditionnel d\'Halloween aux États-Unis : attraper des pommes dans une bassine avec les dents.'),
    q('Mots et objets', 4, 'QCM', 'Combien de fois environ un cœur humain bat-il en une vie de 80 ans ?', '3 milliards', '30 millions', '300 millions', '30 milliards',
      'Environ 100 000 battements par jour, soit près de 3 milliards en 80 ans.',
      '', 'Il pompe environ 7 000 litres de sang par jour : de quoi remplir une petite piscine hors-sol chaque jour.'),
    q('Mots et objets', 4, 'QCM', 'Quel est le groupe sanguin le plus rare chez l\'humain ?', 'Le « sang doré » (Rh nul)', 'AB négatif', 'O négatif', 'B positif',
      'Moins de 50 personnes connues dans le monde. Il ne possède aucun antigène du système Rhésus.',
      '', 'On l\'appelle « sang doré » car il peut être transfusé à toute personne ayant un groupe Rhésus rare, mais ses porteurs ne peuvent recevoir que du Rh nul.'),
    q('Mots et objets', 5, 'VF', 'Le son se propage plus vite dans l\'eau que dans l\'air.', 'Vrai', '', '', '',
      'Vrai : environ 1 500 m/s dans l\'eau contre 340 m/s dans l\'air, plus de quatre fois plus vite.',
      '', 'Dans l\'acier, il file à près de 6 000 m/s. C\'est pour ça que, dans les westerns, on colle l\'oreille aux rails pour entendre le train arriver.'),
  ];
}
